var data = {lines:[
{"lineNum":"    1","line":"const builtin = @import(\"builtin\");"},
{"lineNum":"    2","line":"const std = @import(\"../std.zig\");"},
{"lineNum":"    3","line":"const debug = std.debug;"},
{"lineNum":"    4","line":"const assert = debug.assert;"},
{"lineNum":"    5","line":"const testing = std.testing;"},
{"lineNum":"    6","line":"const mem = std.mem;"},
{"lineNum":"    7","line":"const fmt = std.fmt;"},
{"lineNum":"    8","line":"const ascii = std.ascii;"},
{"lineNum":"    9","line":"const Allocator = mem.Allocator;"},
{"lineNum":"   10","line":"const math = std.math;"},
{"lineNum":"   11","line":"const windows = std.os.windows;"},
{"lineNum":"   12","line":"const os = std.os;"},
{"lineNum":"   13","line":"const fs = std.fs;"},
{"lineNum":"   14","line":"const process = std.process;"},
{"lineNum":"   15","line":"const native_os = builtin.target.os.tag;"},
{"lineNum":"   16","line":""},
{"lineNum":"   17","line":"pub const sep_windows = \'\\\\\';"},
{"lineNum":"   18","line":"pub const sep_posix = \'/\';"},
{"lineNum":"   19","line":"pub const sep = switch (native_os) {"},
{"lineNum":"   20","line":"    .windows, .uefi => sep_windows,"},
{"lineNum":"   21","line":"    else => sep_posix,"},
{"lineNum":"   22","line":"};"},
{"lineNum":"   23","line":""},
{"lineNum":"   24","line":"pub const sep_str_windows = \"\\\\\";"},
{"lineNum":"   25","line":"pub const sep_str_posix = \"/\";"},
{"lineNum":"   26","line":"pub const sep_str = switch (native_os) {"},
{"lineNum":"   27","line":"    .windows, .uefi => sep_str_windows,"},
{"lineNum":"   28","line":"    else => sep_str_posix,"},
{"lineNum":"   29","line":"};"},
{"lineNum":"   30","line":""},
{"lineNum":"   31","line":"pub const delimiter_windows = \';\';"},
{"lineNum":"   32","line":"pub const delimiter_posix = \':\';"},
{"lineNum":"   33","line":"pub const delimiter = if (native_os == .windows) delimiter_windows else delimiter_posix;"},
{"lineNum":"   34","line":""},
{"lineNum":"   35","line":"/// Returns if the given byte is a valid path separator"},
{"lineNum":"   36","line":"pub fn isSep(byte: u8) bool {","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"   37","line":"    return switch (native_os) {","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"   38","line":"        .windows => byte == \'/\' or byte == \'\\\\\',"},
{"lineNum":"   39","line":"        .uefi => byte == \'\\\\\',"},
{"lineNum":"   40","line":"        else => byte == \'/\',"},
{"lineNum":"   41","line":"    };"},
{"lineNum":"   42","line":"}"},
{"lineNum":"   43","line":""},
{"lineNum":"   44","line":"/// This is different from mem.join in that the separator will not be repeated if"},
{"lineNum":"   45","line":"/// it is found at the end or beginning of a pair of consecutive paths."},
{"lineNum":"   46","line":"fn joinSepMaybeZ(allocator: Allocator, separator: u8, comptime sepPredicate: fn (u8) bool, paths: []const []const u8, zero: bool) ![]u8 {","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"   47","line":"    if (paths.len == 0) return if (zero) try allocator.dupe(u8, &[1]u8{0}) else &[0]u8{};","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"   48","line":""},
{"lineNum":"   49","line":"    // Find first non-empty path index."},
{"lineNum":"   50","line":"    const first_path_index = blk: {","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"   51","line":"        for (paths, 0..) |path, index| {","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"   52","line":"            if (path.len == 0) continue else break :blk index;","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"   53","line":"        }"},
{"lineNum":"   54","line":""},
{"lineNum":"   55","line":"        // All paths provided were empty, so return early."},
{"lineNum":"   56","line":"        return if (zero) try allocator.dupe(u8, &[1]u8{0}) else &[0]u8{};","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"   57","line":"    };"},
{"lineNum":"   58","line":""},
{"lineNum":"   59","line":"    // Calculate length needed for resulting joined path buffer."},
{"lineNum":"   60","line":"    const total_len = blk: {"},
{"lineNum":"   61","line":"        var sum: usize = paths[first_path_index].len;","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"   62","line":"        var prev_path = paths[first_path_index];","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"   63","line":"        assert(prev_path.len > 0);","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"   64","line":"        var i: usize = first_path_index + 1;","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"   65","line":"        while (i < paths.len) : (i += 1) {","class":"lineNoCov","hits":"0","possible_hits":"3",},
{"lineNum":"   66","line":"            const this_path = paths[i];","class":"lineNoCov","hits":"0","possible_hits":"2",},
{"lineNum":"   67","line":"            if (this_path.len == 0) continue;","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"   68","line":"            const prev_sep = sepPredicate(prev_path[prev_path.len - 1]);","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"   69","line":"            const this_sep = sepPredicate(this_path[0]);","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"   70","line":"            sum += @boolToInt(!prev_sep and !this_sep);","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"   71","line":"            sum += if (prev_sep and this_sep) this_path.len - 1 else this_path.len;","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"   72","line":"            prev_path = this_path;","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"   73","line":"        }"},
{"lineNum":"   74","line":""},
{"lineNum":"   75","line":"        if (zero) sum += 1;","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"   76","line":"        break :blk sum;","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"   77","line":"    };"},
{"lineNum":"   78","line":""},
{"lineNum":"   79","line":"    const buf = try allocator.alloc(u8, total_len);","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"   80","line":"    errdefer allocator.free(buf);"},
{"lineNum":"   81","line":""},
{"lineNum":"   82","line":"    mem.copy(u8, buf, paths[first_path_index]);","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"   83","line":"    var buf_index: usize = paths[first_path_index].len;","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"   84","line":"    var prev_path = paths[first_path_index];","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"   85","line":"    assert(prev_path.len > 0);","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"   86","line":"    var i: usize = first_path_index + 1;","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"   87","line":"    while (i < paths.len) : (i += 1) {","class":"lineNoCov","hits":"0","possible_hits":"3",},
{"lineNum":"   88","line":"        const this_path = paths[i];","class":"lineNoCov","hits":"0","possible_hits":"2",},
{"lineNum":"   89","line":"        if (this_path.len == 0) continue;","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"   90","line":"        const prev_sep = sepPredicate(prev_path[prev_path.len - 1]);","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"   91","line":"        const this_sep = sepPredicate(this_path[0]);","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"   92","line":"        if (!prev_sep and !this_sep) {","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"   93","line":"            buf[buf_index] = separator;","class":"lineNoCov","hits":"0","possible_hits":"2",},
{"lineNum":"   94","line":"            buf_index += 1;","class":"lineNoCov","hits":"0","possible_hits":"2",},
{"lineNum":"   95","line":"        }"},
{"lineNum":"   96","line":"        const adjusted_path = if (prev_sep and this_sep) this_path[1..] else this_path;","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"   97","line":"        mem.copy(u8, buf[buf_index..], adjusted_path);","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"   98","line":"        buf_index += adjusted_path.len;","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"   99","line":"        prev_path = this_path;","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"  100","line":"    }"},
{"lineNum":"  101","line":""},
{"lineNum":"  102","line":"    if (zero) buf[buf.len - 1] = 0;","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"  103","line":""},
{"lineNum":"  104","line":"    // No need for shrink since buf is exactly the correct size."},
{"lineNum":"  105","line":"    return buf;","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"  106","line":"}"},
{"lineNum":"  107","line":""},
{"lineNum":"  108","line":"/// Naively combines a series of paths with the native path seperator."},
{"lineNum":"  109","line":"/// Allocates memory for the result, which must be freed by the caller."},
{"lineNum":"  110","line":"pub fn join(allocator: Allocator, paths: []const []const u8) ![]u8 {","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"  111","line":"    return joinSepMaybeZ(allocator, sep, isSep, paths, false);","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"  112","line":"}"},
{"lineNum":"  113","line":""},
{"lineNum":"  114","line":"/// Naively combines a series of paths with the native path seperator and null terminator."},
{"lineNum":"  115","line":"/// Allocates memory for the result, which must be freed by the caller."},
{"lineNum":"  116","line":"pub fn joinZ(allocator: Allocator, paths: []const []const u8) ![:0]u8 {"},
{"lineNum":"  117","line":"    const out = try joinSepMaybeZ(allocator, sep, isSep, paths, true);"},
{"lineNum":"  118","line":"    return out[0 .. out.len - 1 :0];"},
{"lineNum":"  119","line":"}"},
{"lineNum":"  120","line":""},
{"lineNum":"  121","line":"fn testJoinMaybeZUefi(paths: []const []const u8, expected: []const u8, zero: bool) !void {"},
{"lineNum":"  122","line":"    const uefiIsSep = struct {"},
{"lineNum":"  123","line":"        fn isSep(byte: u8) bool {"},
{"lineNum":"  124","line":"            return byte == \'\\\\\';"},
{"lineNum":"  125","line":"        }"},
{"lineNum":"  126","line":"    }.isSep;"},
{"lineNum":"  127","line":"    const actual = try joinSepMaybeZ(testing.allocator, sep_windows, uefiIsSep, paths, zero);"},
{"lineNum":"  128","line":"    defer testing.allocator.free(actual);"},
{"lineNum":"  129","line":"    try testing.expectEqualSlices(u8, expected, if (zero) actual[0 .. actual.len - 1 :0] else actual);"},
{"lineNum":"  130","line":"}"},
{"lineNum":"  131","line":""},
{"lineNum":"  132","line":"fn testJoinMaybeZWindows(paths: []const []const u8, expected: []const u8, zero: bool) !void {"},
{"lineNum":"  133","line":"    const windowsIsSep = struct {"},
{"lineNum":"  134","line":"        fn isSep(byte: u8) bool {"},
{"lineNum":"  135","line":"            return byte == \'/\' or byte == \'\\\\\';"},
{"lineNum":"  136","line":"        }"},
{"lineNum":"  137","line":"    }.isSep;"},
{"lineNum":"  138","line":"    const actual = try joinSepMaybeZ(testing.allocator, sep_windows, windowsIsSep, paths, zero);"},
{"lineNum":"  139","line":"    defer testing.allocator.free(actual);"},
{"lineNum":"  140","line":"    try testing.expectEqualSlices(u8, expected, if (zero) actual[0 .. actual.len - 1 :0] else actual);"},
{"lineNum":"  141","line":"}"},
{"lineNum":"  142","line":""},
{"lineNum":"  143","line":"fn testJoinMaybeZPosix(paths: []const []const u8, expected: []const u8, zero: bool) !void {"},
{"lineNum":"  144","line":"    const posixIsSep = struct {"},
{"lineNum":"  145","line":"        fn isSep(byte: u8) bool {"},
{"lineNum":"  146","line":"            return byte == \'/\';"},
{"lineNum":"  147","line":"        }"},
{"lineNum":"  148","line":"    }.isSep;"},
{"lineNum":"  149","line":"    const actual = try joinSepMaybeZ(testing.allocator, sep_posix, posixIsSep, paths, zero);"},
{"lineNum":"  150","line":"    defer testing.allocator.free(actual);"},
{"lineNum":"  151","line":"    try testing.expectEqualSlices(u8, expected, if (zero) actual[0 .. actual.len - 1 :0] else actual);"},
{"lineNum":"  152","line":"}"},
{"lineNum":"  153","line":""},
{"lineNum":"  154","line":"test \"join\" {"},
{"lineNum":"  155","line":"    {"},
{"lineNum":"  156","line":"        const actual: []u8 = try join(testing.allocator, &[_][]const u8{});"},
{"lineNum":"  157","line":"        defer testing.allocator.free(actual);"},
{"lineNum":"  158","line":"        try testing.expectEqualSlices(u8, \"\", actual);"},
{"lineNum":"  159","line":"    }"},
{"lineNum":"  160","line":"    {"},
{"lineNum":"  161","line":"        const actual: [:0]u8 = try joinZ(testing.allocator, &[_][]const u8{});"},
{"lineNum":"  162","line":"        defer testing.allocator.free(actual);"},
{"lineNum":"  163","line":"        try testing.expectEqualSlices(u8, \"\", actual);"},
{"lineNum":"  164","line":"    }"},
{"lineNum":"  165","line":"    for (&[_]bool{ false, true }) |zero| {"},
{"lineNum":"  166","line":"        try testJoinMaybeZWindows(&[_][]const u8{}, \"\", zero);"},
{"lineNum":"  167","line":"        try testJoinMaybeZWindows(&[_][]const u8{ \"c:\\\\a\\\\b\", \"c\" }, \"c:\\\\a\\\\b\\\\c\", zero);"},
{"lineNum":"  168","line":"        try testJoinMaybeZWindows(&[_][]const u8{ \"c:\\\\a\\\\b\", \"c\" }, \"c:\\\\a\\\\b\\\\c\", zero);"},
{"lineNum":"  169","line":"        try testJoinMaybeZWindows(&[_][]const u8{ \"c:\\\\a\\\\b\\\\\", \"c\" }, \"c:\\\\a\\\\b\\\\c\", zero);"},
{"lineNum":"  170","line":""},
{"lineNum":"  171","line":"        try testJoinMaybeZWindows(&[_][]const u8{ \"c:\\\\\", \"a\", \"b\\\\\", \"c\" }, \"c:\\\\a\\\\b\\\\c\", zero);"},
{"lineNum":"  172","line":"        try testJoinMaybeZWindows(&[_][]const u8{ \"c:\\\\a\\\\\", \"b\\\\\", \"c\" }, \"c:\\\\a\\\\b\\\\c\", zero);"},
{"lineNum":"  173","line":""},
{"lineNum":"  174","line":"        try testJoinMaybeZWindows("},
{"lineNum":"  175","line":"            &[_][]const u8{ \"c:\\\\home\\\\andy\\\\dev\\\\zig\\\\build\\\\lib\\\\zig\\\\std\", \"io.zig\" },"},
{"lineNum":"  176","line":"            \"c:\\\\home\\\\andy\\\\dev\\\\zig\\\\build\\\\lib\\\\zig\\\\std\\\\io.zig\","},
{"lineNum":"  177","line":"            zero,"},
{"lineNum":"  178","line":"        );"},
{"lineNum":"  179","line":""},
{"lineNum":"  180","line":"        try testJoinMaybeZUefi(&[_][]const u8{ \"EFI\", \"Boot\", \"bootx64.efi\" }, \"EFI\\\\Boot\\\\bootx64.efi\", zero);"},
{"lineNum":"  181","line":"        try testJoinMaybeZUefi(&[_][]const u8{ \"EFI\\\\Boot\", \"bootx64.efi\" }, \"EFI\\\\Boot\\\\bootx64.efi\", zero);"},
{"lineNum":"  182","line":"        try testJoinMaybeZUefi(&[_][]const u8{ \"EFI\\\\\", \"\\\\Boot\", \"bootx64.efi\" }, \"EFI\\\\Boot\\\\bootx64.efi\", zero);"},
{"lineNum":"  183","line":"        try testJoinMaybeZUefi(&[_][]const u8{ \"EFI\\\\\", \"\\\\Boot\\\\\", \"\\\\bootx64.efi\" }, \"EFI\\\\Boot\\\\bootx64.efi\", zero);"},
{"lineNum":"  184","line":""},
{"lineNum":"  185","line":"        try testJoinMaybeZWindows(&[_][]const u8{ \"c:\\\\\", \"a\", \"b/\", \"c\" }, \"c:\\\\a\\\\b/c\", zero);"},
{"lineNum":"  186","line":"        try testJoinMaybeZWindows(&[_][]const u8{ \"c:\\\\a/\", \"b\\\\\", \"/c\" }, \"c:\\\\a/b\\\\c\", zero);"},
{"lineNum":"  187","line":""},
{"lineNum":"  188","line":"        try testJoinMaybeZWindows(&[_][]const u8{ \"\", \"c:\\\\\", \"\", \"\", \"a\", \"b\\\\\", \"c\", \"\" }, \"c:\\\\a\\\\b\\\\c\", zero);"},
{"lineNum":"  189","line":"        try testJoinMaybeZWindows(&[_][]const u8{ \"c:\\\\a/\", \"\", \"b\\\\\", \"\", \"/c\" }, \"c:\\\\a/b\\\\c\", zero);"},
{"lineNum":"  190","line":"        try testJoinMaybeZWindows(&[_][]const u8{ \"\", \"\" }, \"\", zero);"},
{"lineNum":"  191","line":""},
{"lineNum":"  192","line":"        try testJoinMaybeZPosix(&[_][]const u8{}, \"\", zero);"},
{"lineNum":"  193","line":"        try testJoinMaybeZPosix(&[_][]const u8{ \"/a/b\", \"c\" }, \"/a/b/c\", zero);"},
{"lineNum":"  194","line":"        try testJoinMaybeZPosix(&[_][]const u8{ \"/a/b/\", \"c\" }, \"/a/b/c\", zero);"},
{"lineNum":"  195","line":""},
{"lineNum":"  196","line":"        try testJoinMaybeZPosix(&[_][]const u8{ \"/\", \"a\", \"b/\", \"c\" }, \"/a/b/c\", zero);"},
{"lineNum":"  197","line":"        try testJoinMaybeZPosix(&[_][]const u8{ \"/a/\", \"b/\", \"c\" }, \"/a/b/c\", zero);"},
{"lineNum":"  198","line":""},
{"lineNum":"  199","line":"        try testJoinMaybeZPosix("},
{"lineNum":"  200","line":"            &[_][]const u8{ \"/home/andy/dev/zig/build/lib/zig/std\", \"io.zig\" },"},
{"lineNum":"  201","line":"            \"/home/andy/dev/zig/build/lib/zig/std/io.zig\","},
{"lineNum":"  202","line":"            zero,"},
{"lineNum":"  203","line":"        );"},
{"lineNum":"  204","line":""},
{"lineNum":"  205","line":"        try testJoinMaybeZPosix(&[_][]const u8{ \"a\", \"/c\" }, \"a/c\", zero);"},
{"lineNum":"  206","line":"        try testJoinMaybeZPosix(&[_][]const u8{ \"a/\", \"/c\" }, \"a/c\", zero);"},
{"lineNum":"  207","line":""},
{"lineNum":"  208","line":"        try testJoinMaybeZPosix(&[_][]const u8{ \"\", \"/\", \"a\", \"\", \"b/\", \"c\", \"\" }, \"/a/b/c\", zero);"},
{"lineNum":"  209","line":"        try testJoinMaybeZPosix(&[_][]const u8{ \"/a/\", \"\", \"\", \"b/\", \"c\" }, \"/a/b/c\", zero);"},
{"lineNum":"  210","line":"        try testJoinMaybeZPosix(&[_][]const u8{ \"\", \"\" }, \"\", zero);"},
{"lineNum":"  211","line":"    }"},
{"lineNum":"  212","line":"}"},
{"lineNum":"  213","line":""},
{"lineNum":"  214","line":"pub fn isAbsoluteZ(path_c: [*:0]const u8) bool {","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"  215","line":"    if (native_os == .windows) {"},
{"lineNum":"  216","line":"        return isAbsoluteWindowsZ(path_c);"},
{"lineNum":"  217","line":"    } else {"},
{"lineNum":"  218","line":"        return isAbsolutePosixZ(path_c);","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"  219","line":"    }"},
{"lineNum":"  220","line":"}"},
{"lineNum":"  221","line":""},
{"lineNum":"  222","line":"pub fn isAbsolute(path: []const u8) bool {"},
{"lineNum":"  223","line":"    if (native_os == .windows) {"},
{"lineNum":"  224","line":"        return isAbsoluteWindows(path);"},
{"lineNum":"  225","line":"    } else {"},
{"lineNum":"  226","line":"        return isAbsolutePosix(path);"},
{"lineNum":"  227","line":"    }"},
{"lineNum":"  228","line":"}"},
{"lineNum":"  229","line":""},
{"lineNum":"  230","line":"fn isAbsoluteWindowsImpl(comptime T: type, path: []const T) bool {"},
{"lineNum":"  231","line":"    if (path.len < 1)"},
{"lineNum":"  232","line":"        return false;"},
{"lineNum":"  233","line":""},
{"lineNum":"  234","line":"    if (path[0] == \'/\')"},
{"lineNum":"  235","line":"        return true;"},
{"lineNum":"  236","line":""},
{"lineNum":"  237","line":"    if (path[0] == \'\\\\\')"},
{"lineNum":"  238","line":"        return true;"},
{"lineNum":"  239","line":""},
{"lineNum":"  240","line":"    if (path.len < 3)"},
{"lineNum":"  241","line":"        return false;"},
{"lineNum":"  242","line":""},
{"lineNum":"  243","line":"    if (path[1] == \':\') {"},
{"lineNum":"  244","line":"        if (path[2] == \'/\')"},
{"lineNum":"  245","line":"            return true;"},
{"lineNum":"  246","line":"        if (path[2] == \'\\\\\')"},
{"lineNum":"  247","line":"            return true;"},
{"lineNum":"  248","line":"    }"},
{"lineNum":"  249","line":""},
{"lineNum":"  250","line":"    return false;"},
{"lineNum":"  251","line":"}"},
{"lineNum":"  252","line":""},
{"lineNum":"  253","line":"pub fn isAbsoluteWindows(path: []const u8) bool {"},
{"lineNum":"  254","line":"    return isAbsoluteWindowsImpl(u8, path);"},
{"lineNum":"  255","line":"}"},
{"lineNum":"  256","line":""},
{"lineNum":"  257","line":"pub fn isAbsoluteWindowsW(path_w: [*:0]const u16) bool {"},
{"lineNum":"  258","line":"    return isAbsoluteWindowsImpl(u16, mem.sliceTo(path_w, 0));"},
{"lineNum":"  259","line":"}"},
{"lineNum":"  260","line":""},
{"lineNum":"  261","line":"pub fn isAbsoluteWindowsWTF16(path: []const u16) bool {"},
{"lineNum":"  262","line":"    return isAbsoluteWindowsImpl(u16, path);"},
{"lineNum":"  263","line":"}"},
{"lineNum":"  264","line":""},
{"lineNum":"  265","line":"pub fn isAbsoluteWindowsZ(path_c: [*:0]const u8) bool {"},
{"lineNum":"  266","line":"    return isAbsoluteWindowsImpl(u8, mem.sliceTo(path_c, 0));"},
{"lineNum":"  267","line":"}"},
{"lineNum":"  268","line":""},
{"lineNum":"  269","line":"pub fn isAbsolutePosix(path: []const u8) bool {","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"  270","line":"    return path.len > 0 and path[0] == sep_posix;","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"  271","line":"}"},
{"lineNum":"  272","line":""},
{"lineNum":"  273","line":"pub fn isAbsolutePosixZ(path_c: [*:0]const u8) bool {","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"  274","line":"    return isAbsolutePosix(mem.sliceTo(path_c, 0));","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"  275","line":"}"},
{"lineNum":"  276","line":""},
{"lineNum":"  277","line":"test \"isAbsoluteWindows\" {"},
{"lineNum":"  278","line":"    try testIsAbsoluteWindows(\"\", false);"},
{"lineNum":"  279","line":"    try testIsAbsoluteWindows(\"/\", true);"},
{"lineNum":"  280","line":"    try testIsAbsoluteWindows(\"//\", true);"},
{"lineNum":"  281","line":"    try testIsAbsoluteWindows(\"//server\", true);"},
{"lineNum":"  282","line":"    try testIsAbsoluteWindows(\"//server/file\", true);"},
{"lineNum":"  283","line":"    try testIsAbsoluteWindows(\"\\\\\\\\server\\\\file\", true);"},
{"lineNum":"  284","line":"    try testIsAbsoluteWindows(\"\\\\\\\\server\", true);"},
{"lineNum":"  285","line":"    try testIsAbsoluteWindows(\"\\\\\\\\\", true);"},
{"lineNum":"  286","line":"    try testIsAbsoluteWindows(\"c\", false);"},
{"lineNum":"  287","line":"    try testIsAbsoluteWindows(\"c:\", false);"},
{"lineNum":"  288","line":"    try testIsAbsoluteWindows(\"c:\\\\\", true);"},
{"lineNum":"  289","line":"    try testIsAbsoluteWindows(\"c:/\", true);"},
{"lineNum":"  290","line":"    try testIsAbsoluteWindows(\"c://\", true);"},
{"lineNum":"  291","line":"    try testIsAbsoluteWindows(\"C:/Users/\", true);"},
{"lineNum":"  292","line":"    try testIsAbsoluteWindows(\"C:\\\\Users\\\\\", true);"},
{"lineNum":"  293","line":"    try testIsAbsoluteWindows(\"C:cwd/another\", false);"},
{"lineNum":"  294","line":"    try testIsAbsoluteWindows(\"C:cwd\\\\another\", false);"},
{"lineNum":"  295","line":"    try testIsAbsoluteWindows(\"directory/directory\", false);"},
{"lineNum":"  296","line":"    try testIsAbsoluteWindows(\"directory\\\\directory\", false);"},
{"lineNum":"  297","line":"    try testIsAbsoluteWindows(\"/usr/local\", true);"},
{"lineNum":"  298","line":"}"},
{"lineNum":"  299","line":""},
{"lineNum":"  300","line":"test \"isAbsolutePosix\" {"},
{"lineNum":"  301","line":"    try testIsAbsolutePosix(\"\", false);"},
{"lineNum":"  302","line":"    try testIsAbsolutePosix(\"/home/foo\", true);"},
{"lineNum":"  303","line":"    try testIsAbsolutePosix(\"/home/foo/..\", true);"},
{"lineNum":"  304","line":"    try testIsAbsolutePosix(\"bar/\", false);"},
{"lineNum":"  305","line":"    try testIsAbsolutePosix(\"./baz\", false);"},
{"lineNum":"  306","line":"}"},
{"lineNum":"  307","line":""},
{"lineNum":"  308","line":"fn testIsAbsoluteWindows(path: []const u8, expected_result: bool) !void {"},
{"lineNum":"  309","line":"    try testing.expectEqual(expected_result, isAbsoluteWindows(path));"},
{"lineNum":"  310","line":"}"},
{"lineNum":"  311","line":""},
{"lineNum":"  312","line":"fn testIsAbsolutePosix(path: []const u8, expected_result: bool) !void {"},
{"lineNum":"  313","line":"    try testing.expectEqual(expected_result, isAbsolutePosix(path));"},
{"lineNum":"  314","line":"}"},
{"lineNum":"  315","line":""},
{"lineNum":"  316","line":"pub const WindowsPath = struct {"},
{"lineNum":"  317","line":"    is_abs: bool,"},
{"lineNum":"  318","line":"    kind: Kind,"},
{"lineNum":"  319","line":"    disk_designator: []const u8,"},
{"lineNum":"  320","line":""},
{"lineNum":"  321","line":"    pub const Kind = enum {"},
{"lineNum":"  322","line":"        None,"},
{"lineNum":"  323","line":"        Drive,"},
{"lineNum":"  324","line":"        NetworkShare,"},
{"lineNum":"  325","line":"    };"},
{"lineNum":"  326","line":"};"},
{"lineNum":"  327","line":""},
{"lineNum":"  328","line":"pub fn windowsParsePath(path: []const u8) WindowsPath {"},
{"lineNum":"  329","line":"    if (path.len >= 2 and path[1] == \':\') {"},
{"lineNum":"  330","line":"        return WindowsPath{"},
{"lineNum":"  331","line":"            .is_abs = isAbsoluteWindows(path),"},
{"lineNum":"  332","line":"            .kind = WindowsPath.Kind.Drive,"},
{"lineNum":"  333","line":"            .disk_designator = path[0..2],"},
{"lineNum":"  334","line":"        };"},
{"lineNum":"  335","line":"    }"},
{"lineNum":"  336","line":"    if (path.len >= 1 and (path[0] == \'/\' or path[0] == \'\\\\\') and"},
{"lineNum":"  337","line":"        (path.len == 1 or (path[1] != \'/\' and path[1] != \'\\\\\')))"},
{"lineNum":"  338","line":"    {"},
{"lineNum":"  339","line":"        return WindowsPath{"},
{"lineNum":"  340","line":"            .is_abs = true,"},
{"lineNum":"  341","line":"            .kind = WindowsPath.Kind.None,"},
{"lineNum":"  342","line":"            .disk_designator = path[0..0],"},
{"lineNum":"  343","line":"        };"},
{"lineNum":"  344","line":"    }"},
{"lineNum":"  345","line":"    const relative_path = WindowsPath{"},
{"lineNum":"  346","line":"        .kind = WindowsPath.Kind.None,"},
{"lineNum":"  347","line":"        .disk_designator = &[_]u8{},"},
{"lineNum":"  348","line":"        .is_abs = false,"},
{"lineNum":"  349","line":"    };"},
{"lineNum":"  350","line":"    if (path.len < \"//a/b\".len) {"},
{"lineNum":"  351","line":"        return relative_path;"},
{"lineNum":"  352","line":"    }"},
{"lineNum":"  353","line":""},
{"lineNum":"  354","line":"    inline for (\"/\\\\\") |this_sep| {"},
{"lineNum":"  355","line":"        const two_sep = [_]u8{ this_sep, this_sep };"},
{"lineNum":"  356","line":"        if (mem.startsWith(u8, path, &two_sep)) {"},
{"lineNum":"  357","line":"            if (path[2] == this_sep) {"},
{"lineNum":"  358","line":"                return relative_path;"},
{"lineNum":"  359","line":"            }"},
{"lineNum":"  360","line":""},
{"lineNum":"  361","line":"            var it = mem.tokenize(u8, path, &[_]u8{this_sep});"},
{"lineNum":"  362","line":"            _ = (it.next() orelse return relative_path);"},
{"lineNum":"  363","line":"            _ = (it.next() orelse return relative_path);"},
{"lineNum":"  364","line":"            return WindowsPath{"},
{"lineNum":"  365","line":"                .is_abs = isAbsoluteWindows(path),"},
{"lineNum":"  366","line":"                .kind = WindowsPath.Kind.NetworkShare,"},
{"lineNum":"  367","line":"                .disk_designator = path[0..it.index],"},
{"lineNum":"  368","line":"            };"},
{"lineNum":"  369","line":"        }"},
{"lineNum":"  370","line":"    }"},
{"lineNum":"  371","line":"    return relative_path;"},
{"lineNum":"  372","line":"}"},
{"lineNum":"  373","line":""},
{"lineNum":"  374","line":"test \"windowsParsePath\" {"},
{"lineNum":"  375","line":"    {"},
{"lineNum":"  376","line":"        const parsed = windowsParsePath(\"//a/b\");"},
{"lineNum":"  377","line":"        try testing.expect(parsed.is_abs);"},
{"lineNum":"  378","line":"        try testing.expect(parsed.kind == WindowsPath.Kind.NetworkShare);"},
{"lineNum":"  379","line":"        try testing.expect(mem.eql(u8, parsed.disk_designator, \"//a/b\"));"},
{"lineNum":"  380","line":"    }"},
{"lineNum":"  381","line":"    {"},
{"lineNum":"  382","line":"        const parsed = windowsParsePath(\"\\\\\\\\a\\\\b\");"},
{"lineNum":"  383","line":"        try testing.expect(parsed.is_abs);"},
{"lineNum":"  384","line":"        try testing.expect(parsed.kind == WindowsPath.Kind.NetworkShare);"},
{"lineNum":"  385","line":"        try testing.expect(mem.eql(u8, parsed.disk_designator, \"\\\\\\\\a\\\\b\"));"},
{"lineNum":"  386","line":"    }"},
{"lineNum":"  387","line":"    {"},
{"lineNum":"  388","line":"        const parsed = windowsParsePath(\"\\\\\\\\a\\\\\");"},
{"lineNum":"  389","line":"        try testing.expect(!parsed.is_abs);"},
{"lineNum":"  390","line":"        try testing.expect(parsed.kind == WindowsPath.Kind.None);"},
{"lineNum":"  391","line":"        try testing.expect(mem.eql(u8, parsed.disk_designator, \"\"));"},
{"lineNum":"  392","line":"    }"},
{"lineNum":"  393","line":"    {"},
{"lineNum":"  394","line":"        const parsed = windowsParsePath(\"/usr/local\");"},
{"lineNum":"  395","line":"        try testing.expect(parsed.is_abs);"},
{"lineNum":"  396","line":"        try testing.expect(parsed.kind == WindowsPath.Kind.None);"},
{"lineNum":"  397","line":"        try testing.expect(mem.eql(u8, parsed.disk_designator, \"\"));"},
{"lineNum":"  398","line":"    }"},
{"lineNum":"  399","line":"    {"},
{"lineNum":"  400","line":"        const parsed = windowsParsePath(\"c:../\");"},
{"lineNum":"  401","line":"        try testing.expect(!parsed.is_abs);"},
{"lineNum":"  402","line":"        try testing.expect(parsed.kind == WindowsPath.Kind.Drive);"},
{"lineNum":"  403","line":"        try testing.expect(mem.eql(u8, parsed.disk_designator, \"c:\"));"},
{"lineNum":"  404","line":"    }"},
{"lineNum":"  405","line":"}"},
{"lineNum":"  406","line":""},
{"lineNum":"  407","line":"pub fn diskDesignator(path: []const u8) []const u8 {"},
{"lineNum":"  408","line":"    if (native_os == .windows) {"},
{"lineNum":"  409","line":"        return diskDesignatorWindows(path);"},
{"lineNum":"  410","line":"    } else {"},
{"lineNum":"  411","line":"        return \"\";"},
{"lineNum":"  412","line":"    }"},
{"lineNum":"  413","line":"}"},
{"lineNum":"  414","line":""},
{"lineNum":"  415","line":"pub fn diskDesignatorWindows(path: []const u8) []const u8 {"},
{"lineNum":"  416","line":"    return windowsParsePath(path).disk_designator;"},
{"lineNum":"  417","line":"}"},
{"lineNum":"  418","line":""},
{"lineNum":"  419","line":"fn networkShareServersEql(ns1: []const u8, ns2: []const u8) bool {"},
{"lineNum":"  420","line":"    const sep1 = ns1[0];"},
{"lineNum":"  421","line":"    const sep2 = ns2[0];"},
{"lineNum":"  422","line":""},
{"lineNum":"  423","line":"    var it1 = mem.tokenize(u8, ns1, &[_]u8{sep1});"},
{"lineNum":"  424","line":"    var it2 = mem.tokenize(u8, ns2, &[_]u8{sep2});"},
{"lineNum":"  425","line":""},
{"lineNum":"  426","line":"    // TODO ASCII is wrong, we actually need full unicode support to compare paths."},
{"lineNum":"  427","line":"    return ascii.eqlIgnoreCase(it1.next().?, it2.next().?);"},
{"lineNum":"  428","line":"}"},
{"lineNum":"  429","line":""},
{"lineNum":"  430","line":"fn compareDiskDesignators(kind: WindowsPath.Kind, p1: []const u8, p2: []const u8) bool {"},
{"lineNum":"  431","line":"    switch (kind) {"},
{"lineNum":"  432","line":"        WindowsPath.Kind.None => {"},
{"lineNum":"  433","line":"            assert(p1.len == 0);"},
{"lineNum":"  434","line":"            assert(p2.len == 0);"},
{"lineNum":"  435","line":"            return true;"},
{"lineNum":"  436","line":"        },"},
{"lineNum":"  437","line":"        WindowsPath.Kind.Drive => {"},
{"lineNum":"  438","line":"            return ascii.toUpper(p1[0]) == ascii.toUpper(p2[0]);"},
{"lineNum":"  439","line":"        },"},
{"lineNum":"  440","line":"        WindowsPath.Kind.NetworkShare => {"},
{"lineNum":"  441","line":"            const sep1 = p1[0];"},
{"lineNum":"  442","line":"            const sep2 = p2[0];"},
{"lineNum":"  443","line":""},
{"lineNum":"  444","line":"            var it1 = mem.tokenize(u8, p1, &[_]u8{sep1});"},
{"lineNum":"  445","line":"            var it2 = mem.tokenize(u8, p2, &[_]u8{sep2});"},
{"lineNum":"  446","line":""},
{"lineNum":"  447","line":"            // TODO ASCII is wrong, we actually need full unicode support to compare paths."},
{"lineNum":"  448","line":"            return ascii.eqlIgnoreCase(it1.next().?, it2.next().?) and ascii.eqlIgnoreCase(it1.next().?, it2.next().?);"},
{"lineNum":"  449","line":"        },"},
{"lineNum":"  450","line":"    }"},
{"lineNum":"  451","line":"}"},
{"lineNum":"  452","line":""},
{"lineNum":"  453","line":"/// On Windows, this calls `resolveWindows` and on POSIX it calls `resolvePosix`."},
{"lineNum":"  454","line":"pub fn resolve(allocator: Allocator, paths: []const []const u8) ![]u8 {"},
{"lineNum":"  455","line":"    if (native_os == .windows) {"},
{"lineNum":"  456","line":"        return resolveWindows(allocator, paths);"},
{"lineNum":"  457","line":"    } else {"},
{"lineNum":"  458","line":"        return resolvePosix(allocator, paths);"},
{"lineNum":"  459","line":"    }"},
{"lineNum":"  460","line":"}"},
{"lineNum":"  461","line":""},
{"lineNum":"  462","line":"/// This function is like a series of `cd` statements executed one after another."},
{"lineNum":"  463","line":"/// It resolves \".\" and \"..\", but will not convert relative path to absolute path, use std.fs.Dir.realpath instead."},
{"lineNum":"  464","line":"/// The result does not have a trailing path separator."},
{"lineNum":"  465","line":"/// Each drive has its own current working directory."},
{"lineNum":"  466","line":"/// Path separators are canonicalized to \'\\\\\' and drives are canonicalized to capital letters."},
{"lineNum":"  467","line":"/// Note: all usage of this function should be audited due to the existence of symlinks."},
{"lineNum":"  468","line":"/// Without performing actual syscalls, resolving `..` could be incorrect."},
{"lineNum":"  469","line":"/// This API may break in the future: https://github.com/ziglang/zig/issues/13613"},
{"lineNum":"  470","line":"pub fn resolveWindows(allocator: Allocator, paths: []const []const u8) ![]u8 {"},
{"lineNum":"  471","line":"    assert(paths.len > 0);"},
{"lineNum":"  472","line":""},
{"lineNum":"  473","line":"    // determine which disk designator we will result with, if any"},
{"lineNum":"  474","line":"    var result_drive_buf = \"_:\".*;"},
{"lineNum":"  475","line":"    var disk_designator: []const u8 = \"\";"},
{"lineNum":"  476","line":"    var drive_kind = WindowsPath.Kind.None;"},
{"lineNum":"  477","line":"    var have_abs_path = false;"},
{"lineNum":"  478","line":"    var first_index: usize = 0;"},
{"lineNum":"  479","line":"    for (paths, 0..) |p, i| {"},
{"lineNum":"  480","line":"        const parsed = windowsParsePath(p);"},
{"lineNum":"  481","line":"        if (parsed.is_abs) {"},
{"lineNum":"  482","line":"            have_abs_path = true;"},
{"lineNum":"  483","line":"            first_index = i;"},
{"lineNum":"  484","line":"        }"},
{"lineNum":"  485","line":"        switch (parsed.kind) {"},
{"lineNum":"  486","line":"            .Drive => {"},
{"lineNum":"  487","line":"                result_drive_buf[0] = ascii.toUpper(parsed.disk_designator[0]);"},
{"lineNum":"  488","line":"                disk_designator = result_drive_buf[0..];"},
{"lineNum":"  489","line":"                drive_kind = WindowsPath.Kind.Drive;"},
{"lineNum":"  490","line":"            },"},
{"lineNum":"  491","line":"            .NetworkShare => {"},
{"lineNum":"  492","line":"                disk_designator = parsed.disk_designator;"},
{"lineNum":"  493","line":"                drive_kind = WindowsPath.Kind.NetworkShare;"},
{"lineNum":"  494","line":"            },"},
{"lineNum":"  495","line":"            .None => {},"},
{"lineNum":"  496","line":"        }"},
{"lineNum":"  497","line":"    }"},
{"lineNum":"  498","line":""},
{"lineNum":"  499","line":"    // if we will result with a disk designator, loop again to determine"},
{"lineNum":"  500","line":"    // which is the last time the disk designator is absolutely specified, if any"},
{"lineNum":"  501","line":"    // and count up the max bytes for paths related to this disk designator"},
{"lineNum":"  502","line":"    if (drive_kind != WindowsPath.Kind.None) {"},
{"lineNum":"  503","line":"        have_abs_path = false;"},
{"lineNum":"  504","line":"        first_index = 0;"},
{"lineNum":"  505","line":"        var correct_disk_designator = false;"},
{"lineNum":"  506","line":""},
{"lineNum":"  507","line":"        for (paths, 0..) |p, i| {"},
{"lineNum":"  508","line":"            const parsed = windowsParsePath(p);"},
{"lineNum":"  509","line":"            if (parsed.kind != WindowsPath.Kind.None) {"},
{"lineNum":"  510","line":"                if (parsed.kind == drive_kind) {"},
{"lineNum":"  511","line":"                    correct_disk_designator = compareDiskDesignators(drive_kind, disk_designator, parsed.disk_designator);"},
{"lineNum":"  512","line":"                } else {"},
{"lineNum":"  513","line":"                    continue;"},
{"lineNum":"  514","line":"                }"},
{"lineNum":"  515","line":"            }"},
{"lineNum":"  516","line":"            if (!correct_disk_designator) {"},
{"lineNum":"  517","line":"                continue;"},
{"lineNum":"  518","line":"            }"},
{"lineNum":"  519","line":"            if (parsed.is_abs) {"},
{"lineNum":"  520","line":"                first_index = i;"},
{"lineNum":"  521","line":"                have_abs_path = true;"},
{"lineNum":"  522","line":"            }"},
{"lineNum":"  523","line":"        }"},
{"lineNum":"  524","line":"    }"},
{"lineNum":"  525","line":""},
{"lineNum":"  526","line":"    // Allocate result and fill in the disk designator."},
{"lineNum":"  527","line":"    var result = std.ArrayList(u8).init(allocator);"},
{"lineNum":"  528","line":"    defer result.deinit();"},
{"lineNum":"  529","line":""},
{"lineNum":"  530","line":"    const disk_designator_len: usize = l: {"},
{"lineNum":"  531","line":"        if (!have_abs_path) break :l 0;"},
{"lineNum":"  532","line":"        switch (drive_kind) {"},
{"lineNum":"  533","line":"            .Drive => {"},
{"lineNum":"  534","line":"                try result.appendSlice(disk_designator);"},
{"lineNum":"  535","line":"                break :l disk_designator.len;"},
{"lineNum":"  536","line":"            },"},
{"lineNum":"  537","line":"            .NetworkShare => {"},
{"lineNum":"  538","line":"                var it = mem.tokenize(u8, paths[first_index], \"/\\\\\");"},
{"lineNum":"  539","line":"                const server_name = it.next().?;"},
{"lineNum":"  540","line":"                const other_name = it.next().?;"},
{"lineNum":"  541","line":""},
{"lineNum":"  542","line":"                try result.ensureUnusedCapacity(2 + 1 + server_name.len + other_name.len);"},
{"lineNum":"  543","line":"                result.appendSliceAssumeCapacity(\"\\\\\\\\\");"},
{"lineNum":"  544","line":"                result.appendSliceAssumeCapacity(server_name);"},
{"lineNum":"  545","line":"                result.appendAssumeCapacity(\'\\\\\');"},
{"lineNum":"  546","line":"                result.appendSliceAssumeCapacity(other_name);"},
{"lineNum":"  547","line":""},
{"lineNum":"  548","line":"                break :l result.items.len;"},
{"lineNum":"  549","line":"            },"},
{"lineNum":"  550","line":"            .None => {"},
{"lineNum":"  551","line":"                break :l 1;"},
{"lineNum":"  552","line":"            },"},
{"lineNum":"  553","line":"        }"},
{"lineNum":"  554","line":"    };"},
{"lineNum":"  555","line":""},
{"lineNum":"  556","line":"    var correct_disk_designator = true;"},
{"lineNum":"  557","line":"    var negative_count: usize = 0;"},
{"lineNum":"  558","line":""},
{"lineNum":"  559","line":"    for (paths[first_index..]) |p| {"},
{"lineNum":"  560","line":"        const parsed = windowsParsePath(p);"},
{"lineNum":"  561","line":""},
{"lineNum":"  562","line":"        if (parsed.kind != .None) {"},
{"lineNum":"  563","line":"            if (parsed.kind == drive_kind) {"},
{"lineNum":"  564","line":"                const dd = result.items[0..disk_designator_len];"},
{"lineNum":"  565","line":"                correct_disk_designator = compareDiskDesignators(drive_kind, dd, parsed.disk_designator);"},
{"lineNum":"  566","line":"            } else {"},
{"lineNum":"  567","line":"                continue;"},
{"lineNum":"  568","line":"            }"},
{"lineNum":"  569","line":"        }"},
{"lineNum":"  570","line":"        if (!correct_disk_designator) {"},
{"lineNum":"  571","line":"            continue;"},
{"lineNum":"  572","line":"        }"},
{"lineNum":"  573","line":"        var it = mem.tokenize(u8, p[parsed.disk_designator.len..], \"/\\\\\");"},
{"lineNum":"  574","line":"        while (it.next()) |component| {"},
{"lineNum":"  575","line":"            if (mem.eql(u8, component, \".\")) {"},
{"lineNum":"  576","line":"                continue;"},
{"lineNum":"  577","line":"            } else if (mem.eql(u8, component, \"..\")) {"},
{"lineNum":"  578","line":"                if (result.items.len == 0) {"},
{"lineNum":"  579","line":"                    negative_count += 1;"},
{"lineNum":"  580","line":"                    continue;"},
{"lineNum":"  581","line":"                }"},
{"lineNum":"  582","line":"                while (true) {"},
{"lineNum":"  583","line":"                    if (result.items.len == disk_designator_len) {"},
{"lineNum":"  584","line":"                        break;"},
{"lineNum":"  585","line":"                    }"},
{"lineNum":"  586","line":"                    const end_with_sep = switch (result.items[result.items.len - 1]) {"},
{"lineNum":"  587","line":"                        \'\\\\\', \'/\' => true,"},
{"lineNum":"  588","line":"                        else => false,"},
{"lineNum":"  589","line":"                    };"},
{"lineNum":"  590","line":"                    result.items.len -= 1;"},
{"lineNum":"  591","line":"                    if (end_with_sep or result.items.len == 0) break;"},
{"lineNum":"  592","line":"                }"},
{"lineNum":"  593","line":"            } else if (!have_abs_path and result.items.len == 0) {"},
{"lineNum":"  594","line":"                try result.appendSlice(component);"},
{"lineNum":"  595","line":"            } else {"},
{"lineNum":"  596","line":"                try result.ensureUnusedCapacity(1 + component.len);"},
{"lineNum":"  597","line":"                result.appendAssumeCapacity(\'\\\\\');"},
{"lineNum":"  598","line":"                result.appendSliceAssumeCapacity(component);"},
{"lineNum":"  599","line":"            }"},
{"lineNum":"  600","line":"        }"},
{"lineNum":"  601","line":"    }"},
{"lineNum":"  602","line":""},
{"lineNum":"  603","line":"    if (disk_designator_len != 0 and result.items.len == disk_designator_len) {"},
{"lineNum":"  604","line":"        try result.append(\'\\\\\');"},
{"lineNum":"  605","line":"        return result.toOwnedSlice();"},
{"lineNum":"  606","line":"    }"},
{"lineNum":"  607","line":""},
{"lineNum":"  608","line":"    if (result.items.len == 0) {"},
{"lineNum":"  609","line":"        if (negative_count == 0) {"},
{"lineNum":"  610","line":"            return allocator.dupe(u8, \".\");"},
{"lineNum":"  611","line":"        } else {"},
{"lineNum":"  612","line":"            const real_result = try allocator.alloc(u8, 3 * negative_count - 1);"},
{"lineNum":"  613","line":"            var count = negative_count - 1;"},
{"lineNum":"  614","line":"            var i: usize = 0;"},
{"lineNum":"  615","line":"            while (count > 0) : (count -= 1) {"},
{"lineNum":"  616","line":"                real_result[i..][0..3].* = \"..\\\\\".*;"},
{"lineNum":"  617","line":"                i += 3;"},
{"lineNum":"  618","line":"            }"},
{"lineNum":"  619","line":"            real_result[i..][0..2].* = \"..\".*;"},
{"lineNum":"  620","line":"            return real_result;"},
{"lineNum":"  621","line":"        }"},
{"lineNum":"  622","line":"    }"},
{"lineNum":"  623","line":""},
{"lineNum":"  624","line":"    if (negative_count == 0) {"},
{"lineNum":"  625","line":"        return result.toOwnedSlice();"},
{"lineNum":"  626","line":"    } else {"},
{"lineNum":"  627","line":"        const real_result = try allocator.alloc(u8, 3 * negative_count + result.items.len);"},
{"lineNum":"  628","line":"        var count = negative_count;"},
{"lineNum":"  629","line":"        var i: usize = 0;"},
{"lineNum":"  630","line":"        while (count > 0) : (count -= 1) {"},
{"lineNum":"  631","line":"            real_result[i..][0..3].* = \"..\\\\\".*;"},
{"lineNum":"  632","line":"            i += 3;"},
{"lineNum":"  633","line":"        }"},
{"lineNum":"  634","line":"        mem.copy(u8, real_result[i..], result.items);"},
{"lineNum":"  635","line":"        return real_result;"},
{"lineNum":"  636","line":"    }"},
{"lineNum":"  637","line":"}"},
{"lineNum":"  638","line":""},
{"lineNum":"  639","line":"/// This function is like a series of `cd` statements executed one after another."},
{"lineNum":"  640","line":"/// It resolves \".\" and \"..\", but will not convert relative path to absolute path, use std.fs.Dir.realpath instead."},
{"lineNum":"  641","line":"/// The result does not have a trailing path separator."},
{"lineNum":"  642","line":"/// This function does not perform any syscalls. Executing this series of path"},
{"lineNum":"  643","line":"/// lookups on the actual filesystem may produce different results due to"},
{"lineNum":"  644","line":"/// symlinks."},
{"lineNum":"  645","line":"pub fn resolvePosix(allocator: Allocator, paths: []const []const u8) Allocator.Error![]u8 {"},
{"lineNum":"  646","line":"    assert(paths.len > 0);"},
{"lineNum":"  647","line":""},
{"lineNum":"  648","line":"    var result = std.ArrayList(u8).init(allocator);"},
{"lineNum":"  649","line":"    defer result.deinit();"},
{"lineNum":"  650","line":""},
{"lineNum":"  651","line":"    var negative_count: usize = 0;"},
{"lineNum":"  652","line":"    var is_abs = false;"},
{"lineNum":"  653","line":""},
{"lineNum":"  654","line":"    for (paths) |p| {"},
{"lineNum":"  655","line":"        if (isAbsolutePosix(p)) {"},
{"lineNum":"  656","line":"            is_abs = true;"},
{"lineNum":"  657","line":"            negative_count = 0;"},
{"lineNum":"  658","line":"            result.clearRetainingCapacity();"},
{"lineNum":"  659","line":"        }"},
{"lineNum":"  660","line":"        var it = mem.tokenize(u8, p, \"/\");"},
{"lineNum":"  661","line":"        while (it.next()) |component| {"},
{"lineNum":"  662","line":"            if (mem.eql(u8, component, \".\")) {"},
{"lineNum":"  663","line":"                continue;"},
{"lineNum":"  664","line":"            } else if (mem.eql(u8, component, \"..\")) {"},
{"lineNum":"  665","line":"                if (result.items.len == 0) {"},
{"lineNum":"  666","line":"                    negative_count += @boolToInt(!is_abs);"},
{"lineNum":"  667","line":"                    continue;"},
{"lineNum":"  668","line":"                }"},
{"lineNum":"  669","line":"                while (true) {"},
{"lineNum":"  670","line":"                    const ends_with_slash = result.items[result.items.len - 1] == \'/\';"},
{"lineNum":"  671","line":"                    result.items.len -= 1;"},
{"lineNum":"  672","line":"                    if (ends_with_slash or result.items.len == 0) break;"},
{"lineNum":"  673","line":"                }"},
{"lineNum":"  674","line":"            } else if (result.items.len > 0 or is_abs) {"},
{"lineNum":"  675","line":"                try result.ensureUnusedCapacity(1 + component.len);"},
{"lineNum":"  676","line":"                result.appendAssumeCapacity(\'/\');"},
{"lineNum":"  677","line":"                result.appendSliceAssumeCapacity(component);"},
{"lineNum":"  678","line":"            } else {"},
{"lineNum":"  679","line":"                try result.appendSlice(component);"},
{"lineNum":"  680","line":"            }"},
{"lineNum":"  681","line":"        }"},
{"lineNum":"  682","line":"    }"},
{"lineNum":"  683","line":""},
{"lineNum":"  684","line":"    if (result.items.len == 0) {"},
{"lineNum":"  685","line":"        if (is_abs) {"},
{"lineNum":"  686","line":"            return allocator.dupe(u8, \"/\");"},
{"lineNum":"  687","line":"        }"},
{"lineNum":"  688","line":"        if (negative_count == 0) {"},
{"lineNum":"  689","line":"            return allocator.dupe(u8, \".\");"},
{"lineNum":"  690","line":"        } else {"},
{"lineNum":"  691","line":"            const real_result = try allocator.alloc(u8, 3 * negative_count - 1);"},
{"lineNum":"  692","line":"            var count = negative_count - 1;"},
{"lineNum":"  693","line":"            var i: usize = 0;"},
{"lineNum":"  694","line":"            while (count > 0) : (count -= 1) {"},
{"lineNum":"  695","line":"                real_result[i..][0..3].* = \"../\".*;"},
{"lineNum":"  696","line":"                i += 3;"},
{"lineNum":"  697","line":"            }"},
{"lineNum":"  698","line":"            real_result[i..][0..2].* = \"..\".*;"},
{"lineNum":"  699","line":"            return real_result;"},
{"lineNum":"  700","line":"        }"},
{"lineNum":"  701","line":"    }"},
{"lineNum":"  702","line":""},
{"lineNum":"  703","line":"    if (negative_count == 0) {"},
{"lineNum":"  704","line":"        return result.toOwnedSlice();"},
{"lineNum":"  705","line":"    } else {"},
{"lineNum":"  706","line":"        const real_result = try allocator.alloc(u8, 3 * negative_count + result.items.len);"},
{"lineNum":"  707","line":"        var count = negative_count;"},
{"lineNum":"  708","line":"        var i: usize = 0;"},
{"lineNum":"  709","line":"        while (count > 0) : (count -= 1) {"},
{"lineNum":"  710","line":"            real_result[i..][0..3].* = \"../\".*;"},
{"lineNum":"  711","line":"            i += 3;"},
{"lineNum":"  712","line":"        }"},
{"lineNum":"  713","line":"        mem.copy(u8, real_result[i..], result.items);"},
{"lineNum":"  714","line":"        return real_result;"},
{"lineNum":"  715","line":"    }"},
{"lineNum":"  716","line":"}"},
{"lineNum":"  717","line":""},
{"lineNum":"  718","line":"test \"resolve\" {"},
{"lineNum":"  719","line":"    try testResolveWindows(&[_][]const u8{ \"a\\\\b\\\\c\\\\\", \"..\\\\..\\\\..\" }, \".\");"},
{"lineNum":"  720","line":"    try testResolveWindows(&[_][]const u8{\".\"}, \".\");"},
{"lineNum":"  721","line":""},
{"lineNum":"  722","line":"    try testResolvePosix(&[_][]const u8{ \"a/b/c/\", \"../../..\" }, \".\");"},
{"lineNum":"  723","line":"    try testResolvePosix(&[_][]const u8{\".\"}, \".\");"},
{"lineNum":"  724","line":"}"},
{"lineNum":"  725","line":""},
{"lineNum":"  726","line":"test \"resolveWindows\" {"},
{"lineNum":"  727","line":"    try testResolveWindows("},
{"lineNum":"  728","line":"        &[_][]const u8{ \"Z:\\\\\", \"/usr/local\", \"lib\\\\zig\\\\std\\\\array_list.zig\" },"},
{"lineNum":"  729","line":"        \"Z:\\\\usr\\\\local\\\\lib\\\\zig\\\\std\\\\array_list.zig\","},
{"lineNum":"  730","line":"    );"},
{"lineNum":"  731","line":"    try testResolveWindows("},
{"lineNum":"  732","line":"        &[_][]const u8{ \"z:\\\\\", \"usr/local\", \"lib\\\\zig\" },"},
{"lineNum":"  733","line":"        \"Z:\\\\usr\\\\local\\\\lib\\\\zig\","},
{"lineNum":"  734","line":"    );"},
{"lineNum":"  735","line":""},
{"lineNum":"  736","line":"    try testResolveWindows(&[_][]const u8{ \"c:\\\\a\\\\b\\\\c\", \"/hi\", \"ok\" }, \"C:\\\\hi\\\\ok\");"},
{"lineNum":"  737","line":"    try testResolveWindows(&[_][]const u8{ \"c:/blah\\\\blah\", \"d:/games\", \"c:../a\" }, \"C:\\\\blah\\\\a\");"},
{"lineNum":"  738","line":"    try testResolveWindows(&[_][]const u8{ \"c:/blah\\\\blah\", \"d:/games\", \"C:../a\" }, \"C:\\\\blah\\\\a\");"},
{"lineNum":"  739","line":"    try testResolveWindows(&[_][]const u8{ \"c:/ignore\", \"d:\\\\a/b\\\\c/d\", \"\\\\e.exe\" }, \"D:\\\\e.exe\");"},
{"lineNum":"  740","line":"    try testResolveWindows(&[_][]const u8{ \"c:/ignore\", \"c:/some/file\" }, \"C:\\\\some\\\\file\");"},
{"lineNum":"  741","line":"    try testResolveWindows(&[_][]const u8{ \"d:/ignore\", \"d:some/dir//\" }, \"D:\\\\ignore\\\\some\\\\dir\");"},
{"lineNum":"  742","line":"    try testResolveWindows(&[_][]const u8{ \"//server/share\", \"..\", \"relative\\\\\" }, \"\\\\\\\\server\\\\share\\\\relative\");"},
{"lineNum":"  743","line":"    try testResolveWindows(&[_][]const u8{ \"c:/\", \"//\" }, \"C:\\\\\");"},
{"lineNum":"  744","line":"    try testResolveWindows(&[_][]const u8{ \"c:/\", \"//dir\" }, \"C:\\\\dir\");"},
{"lineNum":"  745","line":"    try testResolveWindows(&[_][]const u8{ \"c:/\", \"//server/share\" }, \"\\\\\\\\server\\\\share\\\\\");"},
{"lineNum":"  746","line":"    try testResolveWindows(&[_][]const u8{ \"c:/\", \"//server//share\" }, \"\\\\\\\\server\\\\share\\\\\");"},
{"lineNum":"  747","line":"    try testResolveWindows(&[_][]const u8{ \"c:/\", \"///some//dir\" }, \"C:\\\\some\\\\dir\");"},
{"lineNum":"  748","line":"    try testResolveWindows(&[_][]const u8{ \"C:\\\\foo\\\\tmp.3\\\\\", \"..\\\\tmp.3\\\\cycles\\\\root.js\" }, \"C:\\\\foo\\\\tmp.3\\\\cycles\\\\root.js\");"},
{"lineNum":"  749","line":""},
{"lineNum":"  750","line":"    // Keep relative paths relative."},
{"lineNum":"  751","line":"    try testResolveWindows(&[_][]const u8{\"a/b\"}, \"a\\\\b\");"},
{"lineNum":"  752","line":"}"},
{"lineNum":"  753","line":""},
{"lineNum":"  754","line":"test \"resolvePosix\" {"},
{"lineNum":"  755","line":"    try testResolvePosix(&.{ \"/a/b\", \"c\" }, \"/a/b/c\");"},
{"lineNum":"  756","line":"    try testResolvePosix(&.{ \"/a/b\", \"c\", \"//d\", \"e///\" }, \"/d/e\");"},
{"lineNum":"  757","line":"    try testResolvePosix(&.{ \"/a/b/c\", \"..\", \"../\" }, \"/a\");"},
{"lineNum":"  758","line":"    try testResolvePosix(&.{ \"/\", \"..\", \"..\" }, \"/\");"},
{"lineNum":"  759","line":"    try testResolvePosix(&.{\"/a/b/c/\"}, \"/a/b/c\");"},
{"lineNum":"  760","line":""},
{"lineNum":"  761","line":"    try testResolvePosix(&.{ \"/var/lib\", \"../\", \"file/\" }, \"/var/file\");"},
{"lineNum":"  762","line":"    try testResolvePosix(&.{ \"/var/lib\", \"/../\", \"file/\" }, \"/file\");"},
{"lineNum":"  763","line":"    try testResolvePosix(&.{ \"/some/dir\", \".\", \"/absolute/\" }, \"/absolute\");"},
{"lineNum":"  764","line":"    try testResolvePosix(&.{ \"/foo/tmp.3/\", \"../tmp.3/cycles/root.js\" }, \"/foo/tmp.3/cycles/root.js\");"},
{"lineNum":"  765","line":""},
{"lineNum":"  766","line":"    // Keep relative paths relative."},
{"lineNum":"  767","line":"    try testResolvePosix(&.{\"a/b\"}, \"a/b\");"},
{"lineNum":"  768","line":"    try testResolvePosix(&.{\".\"}, \".\");"},
{"lineNum":"  769","line":"    try testResolvePosix(&.{ \".\", \"src/test.zig\", \"..\", \"../test/cases.zig\" }, \"test/cases.zig\");"},
{"lineNum":"  770","line":"}"},
{"lineNum":"  771","line":""},
{"lineNum":"  772","line":"fn testResolveWindows(paths: []const []const u8, expected: []const u8) !void {"},
{"lineNum":"  773","line":"    const actual = try resolveWindows(testing.allocator, paths);"},
{"lineNum":"  774","line":"    defer testing.allocator.free(actual);"},
{"lineNum":"  775","line":"    try testing.expectEqualStrings(expected, actual);"},
{"lineNum":"  776","line":"}"},
{"lineNum":"  777","line":""},
{"lineNum":"  778","line":"fn testResolvePosix(paths: []const []const u8, expected: []const u8) !void {"},
{"lineNum":"  779","line":"    const actual = try resolvePosix(testing.allocator, paths);"},
{"lineNum":"  780","line":"    defer testing.allocator.free(actual);"},
{"lineNum":"  781","line":"    try testing.expectEqualStrings(expected, actual);"},
{"lineNum":"  782","line":"}"},
{"lineNum":"  783","line":""},
{"lineNum":"  784","line":"/// Strip the last component from a file path."},
{"lineNum":"  785","line":"///"},
{"lineNum":"  786","line":"/// If the path is a file in the current directory (no directory component)"},
{"lineNum":"  787","line":"/// then returns null."},
{"lineNum":"  788","line":"///"},
{"lineNum":"  789","line":"/// If the path is the root directory, returns null."},
{"lineNum":"  790","line":"pub fn dirname(path: []const u8) ?[]const u8 {"},
{"lineNum":"  791","line":"    if (native_os == .windows) {"},
{"lineNum":"  792","line":"        return dirnameWindows(path);"},
{"lineNum":"  793","line":"    } else {"},
{"lineNum":"  794","line":"        return dirnamePosix(path);"},
{"lineNum":"  795","line":"    }"},
{"lineNum":"  796","line":"}"},
{"lineNum":"  797","line":""},
{"lineNum":"  798","line":"pub fn dirnameWindows(path: []const u8) ?[]const u8 {"},
{"lineNum":"  799","line":"    if (path.len == 0)"},
{"lineNum":"  800","line":"        return null;"},
{"lineNum":"  801","line":""},
{"lineNum":"  802","line":"    const root_slice = diskDesignatorWindows(path);"},
{"lineNum":"  803","line":"    if (path.len == root_slice.len)"},
{"lineNum":"  804","line":"        return null;"},
{"lineNum":"  805","line":""},
{"lineNum":"  806","line":"    const have_root_slash = path.len > root_slice.len and (path[root_slice.len] == \'/\' or path[root_slice.len] == \'\\\\\');"},
{"lineNum":"  807","line":""},
{"lineNum":"  808","line":"    var end_index: usize = path.len - 1;"},
{"lineNum":"  809","line":""},
{"lineNum":"  810","line":"    while (path[end_index] == \'/\' or path[end_index] == \'\\\\\') {"},
{"lineNum":"  811","line":"        if (end_index == 0)"},
{"lineNum":"  812","line":"            return null;"},
{"lineNum":"  813","line":"        end_index -= 1;"},
{"lineNum":"  814","line":"    }"},
{"lineNum":"  815","line":""},
{"lineNum":"  816","line":"    while (path[end_index] != \'/\' and path[end_index] != \'\\\\\') {"},
{"lineNum":"  817","line":"        if (end_index == 0)"},
{"lineNum":"  818","line":"            return null;"},
{"lineNum":"  819","line":"        end_index -= 1;"},
{"lineNum":"  820","line":"    }"},
{"lineNum":"  821","line":""},
{"lineNum":"  822","line":"    if (have_root_slash and end_index == root_slice.len) {"},
{"lineNum":"  823","line":"        end_index += 1;"},
{"lineNum":"  824","line":"    }"},
{"lineNum":"  825","line":""},
{"lineNum":"  826","line":"    if (end_index == 0)"},
{"lineNum":"  827","line":"        return null;"},
{"lineNum":"  828","line":""},
{"lineNum":"  829","line":"    return path[0..end_index];"},
{"lineNum":"  830","line":"}"},
{"lineNum":"  831","line":""},
{"lineNum":"  832","line":"pub fn dirnamePosix(path: []const u8) ?[]const u8 {"},
{"lineNum":"  833","line":"    if (path.len == 0)"},
{"lineNum":"  834","line":"        return null;"},
{"lineNum":"  835","line":""},
{"lineNum":"  836","line":"    var end_index: usize = path.len - 1;"},
{"lineNum":"  837","line":"    while (path[end_index] == \'/\') {"},
{"lineNum":"  838","line":"        if (end_index == 0)"},
{"lineNum":"  839","line":"            return null;"},
{"lineNum":"  840","line":"        end_index -= 1;"},
{"lineNum":"  841","line":"    }"},
{"lineNum":"  842","line":""},
{"lineNum":"  843","line":"    while (path[end_index] != \'/\') {"},
{"lineNum":"  844","line":"        if (end_index == 0)"},
{"lineNum":"  845","line":"            return null;"},
{"lineNum":"  846","line":"        end_index -= 1;"},
{"lineNum":"  847","line":"    }"},
{"lineNum":"  848","line":""},
{"lineNum":"  849","line":"    if (end_index == 0 and path[0] == \'/\')"},
{"lineNum":"  850","line":"        return path[0..1];"},
{"lineNum":"  851","line":""},
{"lineNum":"  852","line":"    if (end_index == 0)"},
{"lineNum":"  853","line":"        return null;"},
{"lineNum":"  854","line":""},
{"lineNum":"  855","line":"    return path[0..end_index];"},
{"lineNum":"  856","line":"}"},
{"lineNum":"  857","line":""},
{"lineNum":"  858","line":"test \"dirnamePosix\" {"},
{"lineNum":"  859","line":"    try testDirnamePosix(\"/a/b/c\", \"/a/b\");"},
{"lineNum":"  860","line":"    try testDirnamePosix(\"/a/b/c///\", \"/a/b\");"},
{"lineNum":"  861","line":"    try testDirnamePosix(\"/a\", \"/\");"},
{"lineNum":"  862","line":"    try testDirnamePosix(\"/\", null);"},
{"lineNum":"  863","line":"    try testDirnamePosix(\"//\", null);"},
{"lineNum":"  864","line":"    try testDirnamePosix(\"///\", null);"},
{"lineNum":"  865","line":"    try testDirnamePosix(\"////\", null);"},
{"lineNum":"  866","line":"    try testDirnamePosix(\"\", null);"},
{"lineNum":"  867","line":"    try testDirnamePosix(\"a\", null);"},
{"lineNum":"  868","line":"    try testDirnamePosix(\"a/\", null);"},
{"lineNum":"  869","line":"    try testDirnamePosix(\"a//\", null);"},
{"lineNum":"  870","line":"}"},
{"lineNum":"  871","line":""},
{"lineNum":"  872","line":"test \"dirnameWindows\" {"},
{"lineNum":"  873","line":"    try testDirnameWindows(\"c:\\\\\", null);"},
{"lineNum":"  874","line":"    try testDirnameWindows(\"c:\\\\foo\", \"c:\\\\\");"},
{"lineNum":"  875","line":"    try testDirnameWindows(\"c:\\\\foo\\\\\", \"c:\\\\\");"},
{"lineNum":"  876","line":"    try testDirnameWindows(\"c:\\\\foo\\\\bar\", \"c:\\\\foo\");"},
{"lineNum":"  877","line":"    try testDirnameWindows(\"c:\\\\foo\\\\bar\\\\\", \"c:\\\\foo\");"},
{"lineNum":"  878","line":"    try testDirnameWindows(\"c:\\\\foo\\\\bar\\\\baz\", \"c:\\\\foo\\\\bar\");"},
{"lineNum":"  879","line":"    try testDirnameWindows(\"\\\\\", null);"},
{"lineNum":"  880","line":"    try testDirnameWindows(\"\\\\foo\", \"\\\\\");"},
{"lineNum":"  881","line":"    try testDirnameWindows(\"\\\\foo\\\\\", \"\\\\\");"},
{"lineNum":"  882","line":"    try testDirnameWindows(\"\\\\foo\\\\bar\", \"\\\\foo\");"},
{"lineNum":"  883","line":"    try testDirnameWindows(\"\\\\foo\\\\bar\\\\\", \"\\\\foo\");"},
{"lineNum":"  884","line":"    try testDirnameWindows(\"\\\\foo\\\\bar\\\\baz\", \"\\\\foo\\\\bar\");"},
{"lineNum":"  885","line":"    try testDirnameWindows(\"c:\", null);"},
{"lineNum":"  886","line":"    try testDirnameWindows(\"c:foo\", null);"},
{"lineNum":"  887","line":"    try testDirnameWindows(\"c:foo\\\\\", null);"},
{"lineNum":"  888","line":"    try testDirnameWindows(\"c:foo\\\\bar\", \"c:foo\");"},
{"lineNum":"  889","line":"    try testDirnameWindows(\"c:foo\\\\bar\\\\\", \"c:foo\");"},
{"lineNum":"  890","line":"    try testDirnameWindows(\"c:foo\\\\bar\\\\baz\", \"c:foo\\\\bar\");"},
{"lineNum":"  891","line":"    try testDirnameWindows(\"file:stream\", null);"},
{"lineNum":"  892","line":"    try testDirnameWindows(\"dir\\\\file:stream\", \"dir\");"},
{"lineNum":"  893","line":"    try testDirnameWindows(\"\\\\\\\\unc\\\\share\", null);"},
{"lineNum":"  894","line":"    try testDirnameWindows(\"\\\\\\\\unc\\\\share\\\\foo\", \"\\\\\\\\unc\\\\share\\\\\");"},
{"lineNum":"  895","line":"    try testDirnameWindows(\"\\\\\\\\unc\\\\share\\\\foo\\\\\", \"\\\\\\\\unc\\\\share\\\\\");"},
{"lineNum":"  896","line":"    try testDirnameWindows(\"\\\\\\\\unc\\\\share\\\\foo\\\\bar\", \"\\\\\\\\unc\\\\share\\\\foo\");"},
{"lineNum":"  897","line":"    try testDirnameWindows(\"\\\\\\\\unc\\\\share\\\\foo\\\\bar\\\\\", \"\\\\\\\\unc\\\\share\\\\foo\");"},
{"lineNum":"  898","line":"    try testDirnameWindows(\"\\\\\\\\unc\\\\share\\\\foo\\\\bar\\\\baz\", \"\\\\\\\\unc\\\\share\\\\foo\\\\bar\");"},
{"lineNum":"  899","line":"    try testDirnameWindows(\"/a/b/\", \"/a\");"},
{"lineNum":"  900","line":"    try testDirnameWindows(\"/a/b\", \"/a\");"},
{"lineNum":"  901","line":"    try testDirnameWindows(\"/a\", \"/\");"},
{"lineNum":"  902","line":"    try testDirnameWindows(\"\", null);"},
{"lineNum":"  903","line":"    try testDirnameWindows(\"/\", null);"},
{"lineNum":"  904","line":"    try testDirnameWindows(\"////\", null);"},
{"lineNum":"  905","line":"    try testDirnameWindows(\"foo\", null);"},
{"lineNum":"  906","line":"}"},
{"lineNum":"  907","line":""},
{"lineNum":"  908","line":"fn testDirnamePosix(input: []const u8, expected_output: ?[]const u8) !void {"},
{"lineNum":"  909","line":"    if (dirnamePosix(input)) |output| {"},
{"lineNum":"  910","line":"        try testing.expect(mem.eql(u8, output, expected_output.?));"},
{"lineNum":"  911","line":"    } else {"},
{"lineNum":"  912","line":"        try testing.expect(expected_output == null);"},
{"lineNum":"  913","line":"    }"},
{"lineNum":"  914","line":"}"},
{"lineNum":"  915","line":""},
{"lineNum":"  916","line":"fn testDirnameWindows(input: []const u8, expected_output: ?[]const u8) !void {"},
{"lineNum":"  917","line":"    if (dirnameWindows(input)) |output| {"},
{"lineNum":"  918","line":"        try testing.expect(mem.eql(u8, output, expected_output.?));"},
{"lineNum":"  919","line":"    } else {"},
{"lineNum":"  920","line":"        try testing.expect(expected_output == null);"},
{"lineNum":"  921","line":"    }"},
{"lineNum":"  922","line":"}"},
{"lineNum":"  923","line":""},
{"lineNum":"  924","line":"pub fn basename(path: []const u8) []const u8 {"},
{"lineNum":"  925","line":"    if (native_os == .windows) {"},
{"lineNum":"  926","line":"        return basenameWindows(path);"},
{"lineNum":"  927","line":"    } else {"},
{"lineNum":"  928","line":"        return basenamePosix(path);"},
{"lineNum":"  929","line":"    }"},
{"lineNum":"  930","line":"}"},
{"lineNum":"  931","line":""},
{"lineNum":"  932","line":"pub fn basenamePosix(path: []const u8) []const u8 {"},
{"lineNum":"  933","line":"    if (path.len == 0)"},
{"lineNum":"  934","line":"        return &[_]u8{};"},
{"lineNum":"  935","line":""},
{"lineNum":"  936","line":"    var end_index: usize = path.len - 1;"},
{"lineNum":"  937","line":"    while (path[end_index] == \'/\') {"},
{"lineNum":"  938","line":"        if (end_index == 0)"},
{"lineNum":"  939","line":"            return &[_]u8{};"},
{"lineNum":"  940","line":"        end_index -= 1;"},
{"lineNum":"  941","line":"    }"},
{"lineNum":"  942","line":"    var start_index: usize = end_index;"},
{"lineNum":"  943","line":"    end_index += 1;"},
{"lineNum":"  944","line":"    while (path[start_index] != \'/\') {"},
{"lineNum":"  945","line":"        if (start_index == 0)"},
{"lineNum":"  946","line":"            return path[0..end_index];"},
{"lineNum":"  947","line":"        start_index -= 1;"},
{"lineNum":"  948","line":"    }"},
{"lineNum":"  949","line":""},
{"lineNum":"  950","line":"    return path[start_index + 1 .. end_index];"},
{"lineNum":"  951","line":"}"},
{"lineNum":"  952","line":""},
{"lineNum":"  953","line":"pub fn basenameWindows(path: []const u8) []const u8 {"},
{"lineNum":"  954","line":"    if (path.len == 0)"},
{"lineNum":"  955","line":"        return &[_]u8{};"},
{"lineNum":"  956","line":""},
{"lineNum":"  957","line":"    var end_index: usize = path.len - 1;"},
{"lineNum":"  958","line":"    while (true) {"},
{"lineNum":"  959","line":"        const byte = path[end_index];"},
{"lineNum":"  960","line":"        if (byte == \'/\' or byte == \'\\\\\') {"},
{"lineNum":"  961","line":"            if (end_index == 0)"},
{"lineNum":"  962","line":"                return &[_]u8{};"},
{"lineNum":"  963","line":"            end_index -= 1;"},
{"lineNum":"  964","line":"            continue;"},
{"lineNum":"  965","line":"        }"},
{"lineNum":"  966","line":"        if (byte == \':\' and end_index == 1) {"},
{"lineNum":"  967","line":"            return &[_]u8{};"},
{"lineNum":"  968","line":"        }"},
{"lineNum":"  969","line":"        break;"},
{"lineNum":"  970","line":"    }"},
{"lineNum":"  971","line":""},
{"lineNum":"  972","line":"    var start_index: usize = end_index;"},
{"lineNum":"  973","line":"    end_index += 1;"},
{"lineNum":"  974","line":"    while (path[start_index] != \'/\' and path[start_index] != \'\\\\\' and"},
{"lineNum":"  975","line":"        !(path[start_index] == \':\' and start_index == 1))"},
{"lineNum":"  976","line":"    {"},
{"lineNum":"  977","line":"        if (start_index == 0)"},
{"lineNum":"  978","line":"            return path[0..end_index];"},
{"lineNum":"  979","line":"        start_index -= 1;"},
{"lineNum":"  980","line":"    }"},
{"lineNum":"  981","line":""},
{"lineNum":"  982","line":"    return path[start_index + 1 .. end_index];"},
{"lineNum":"  983","line":"}"},
{"lineNum":"  984","line":""},
{"lineNum":"  985","line":"test \"basename\" {"},
{"lineNum":"  986","line":"    try testBasename(\"\", \"\");"},
{"lineNum":"  987","line":"    try testBasename(\"/\", \"\");"},
{"lineNum":"  988","line":"    try testBasename(\"/dir/basename.ext\", \"basename.ext\");"},
{"lineNum":"  989","line":"    try testBasename(\"/basename.ext\", \"basename.ext\");"},
{"lineNum":"  990","line":"    try testBasename(\"basename.ext\", \"basename.ext\");"},
{"lineNum":"  991","line":"    try testBasename(\"basename.ext/\", \"basename.ext\");"},
{"lineNum":"  992","line":"    try testBasename(\"basename.ext//\", \"basename.ext\");"},
{"lineNum":"  993","line":"    try testBasename(\"/aaa/bbb\", \"bbb\");"},
{"lineNum":"  994","line":"    try testBasename(\"/aaa/\", \"aaa\");"},
{"lineNum":"  995","line":"    try testBasename(\"/aaa/b\", \"b\");"},
{"lineNum":"  996","line":"    try testBasename(\"/a/b\", \"b\");"},
{"lineNum":"  997","line":"    try testBasename(\"//a\", \"a\");"},
{"lineNum":"  998","line":""},
{"lineNum":"  999","line":"    try testBasenamePosix(\"\\\\dir\\\\basename.ext\", \"\\\\dir\\\\basename.ext\");"},
{"lineNum":" 1000","line":"    try testBasenamePosix(\"\\\\basename.ext\", \"\\\\basename.ext\");"},
{"lineNum":" 1001","line":"    try testBasenamePosix(\"basename.ext\", \"basename.ext\");"},
{"lineNum":" 1002","line":"    try testBasenamePosix(\"basename.ext\\\\\", \"basename.ext\\\\\");"},
{"lineNum":" 1003","line":"    try testBasenamePosix(\"basename.ext\\\\\\\\\", \"basename.ext\\\\\\\\\");"},
{"lineNum":" 1004","line":"    try testBasenamePosix(\"foo\", \"foo\");"},
{"lineNum":" 1005","line":""},
{"lineNum":" 1006","line":"    try testBasenameWindows(\"\\\\dir\\\\basename.ext\", \"basename.ext\");"},
{"lineNum":" 1007","line":"    try testBasenameWindows(\"\\\\basename.ext\", \"basename.ext\");"},
{"lineNum":" 1008","line":"    try testBasenameWindows(\"basename.ext\", \"basename.ext\");"},
{"lineNum":" 1009","line":"    try testBasenameWindows(\"basename.ext\\\\\", \"basename.ext\");"},
{"lineNum":" 1010","line":"    try testBasenameWindows(\"basename.ext\\\\\\\\\", \"basename.ext\");"},
{"lineNum":" 1011","line":"    try testBasenameWindows(\"foo\", \"foo\");"},
{"lineNum":" 1012","line":"    try testBasenameWindows(\"C:\", \"\");"},
{"lineNum":" 1013","line":"    try testBasenameWindows(\"C:.\", \".\");"},
{"lineNum":" 1014","line":"    try testBasenameWindows(\"C:\\\\\", \"\");"},
{"lineNum":" 1015","line":"    try testBasenameWindows(\"C:\\\\dir\\\\base.ext\", \"base.ext\");"},
{"lineNum":" 1016","line":"    try testBasenameWindows(\"C:\\\\basename.ext\", \"basename.ext\");"},
{"lineNum":" 1017","line":"    try testBasenameWindows(\"C:basename.ext\", \"basename.ext\");"},
{"lineNum":" 1018","line":"    try testBasenameWindows(\"C:basename.ext\\\\\", \"basename.ext\");"},
{"lineNum":" 1019","line":"    try testBasenameWindows(\"C:basename.ext\\\\\\\\\", \"basename.ext\");"},
{"lineNum":" 1020","line":"    try testBasenameWindows(\"C:foo\", \"foo\");"},
{"lineNum":" 1021","line":"    try testBasenameWindows(\"file:stream\", \"file:stream\");"},
{"lineNum":" 1022","line":"}"},
{"lineNum":" 1023","line":""},
{"lineNum":" 1024","line":"fn testBasename(input: []const u8, expected_output: []const u8) !void {"},
{"lineNum":" 1025","line":"    try testing.expectEqualSlices(u8, expected_output, basename(input));"},
{"lineNum":" 1026","line":"}"},
{"lineNum":" 1027","line":""},
{"lineNum":" 1028","line":"fn testBasenamePosix(input: []const u8, expected_output: []const u8) !void {"},
{"lineNum":" 1029","line":"    try testing.expectEqualSlices(u8, expected_output, basenamePosix(input));"},
{"lineNum":" 1030","line":"}"},
{"lineNum":" 1031","line":""},
{"lineNum":" 1032","line":"fn testBasenameWindows(input: []const u8, expected_output: []const u8) !void {"},
{"lineNum":" 1033","line":"    try testing.expectEqualSlices(u8, expected_output, basenameWindows(input));"},
{"lineNum":" 1034","line":"}"},
{"lineNum":" 1035","line":""},
{"lineNum":" 1036","line":"/// Returns the relative path from `from` to `to`. If `from` and `to` each"},
{"lineNum":" 1037","line":"/// resolve to the same path (after calling `resolve` on each), a zero-length"},
{"lineNum":" 1038","line":"/// string is returned."},
{"lineNum":" 1039","line":"/// On Windows this canonicalizes the drive to a capital letter and paths to `\\\\`."},
{"lineNum":" 1040","line":"pub fn relative(allocator: Allocator, from: []const u8, to: []const u8) ![]u8 {"},
{"lineNum":" 1041","line":"    if (native_os == .windows) {"},
{"lineNum":" 1042","line":"        return relativeWindows(allocator, from, to);"},
{"lineNum":" 1043","line":"    } else {"},
{"lineNum":" 1044","line":"        return relativePosix(allocator, from, to);"},
{"lineNum":" 1045","line":"    }"},
{"lineNum":" 1046","line":"}"},
{"lineNum":" 1047","line":""},
{"lineNum":" 1048","line":"pub fn relativeWindows(allocator: Allocator, from: []const u8, to: []const u8) ![]u8 {"},
{"lineNum":" 1049","line":"    const cwd = try process.getCwdAlloc(allocator);"},
{"lineNum":" 1050","line":"    defer allocator.free(cwd);"},
{"lineNum":" 1051","line":"    const resolved_from = try resolveWindows(allocator, &[_][]const u8{ cwd, from });"},
{"lineNum":" 1052","line":"    defer allocator.free(resolved_from);"},
{"lineNum":" 1053","line":""},
{"lineNum":" 1054","line":"    var clean_up_resolved_to = true;"},
{"lineNum":" 1055","line":"    const resolved_to = try resolveWindows(allocator, &[_][]const u8{ cwd, to });"},
{"lineNum":" 1056","line":"    defer if (clean_up_resolved_to) allocator.free(resolved_to);"},
{"lineNum":" 1057","line":""},
{"lineNum":" 1058","line":"    const parsed_from = windowsParsePath(resolved_from);"},
{"lineNum":" 1059","line":"    const parsed_to = windowsParsePath(resolved_to);"},
{"lineNum":" 1060","line":"    const result_is_to = x: {"},
{"lineNum":" 1061","line":"        if (parsed_from.kind != parsed_to.kind) {"},
{"lineNum":" 1062","line":"            break :x true;"},
{"lineNum":" 1063","line":"        } else switch (parsed_from.kind) {"},
{"lineNum":" 1064","line":"            .NetworkShare => {"},
{"lineNum":" 1065","line":"                break :x !networkShareServersEql(parsed_to.disk_designator, parsed_from.disk_designator);"},
{"lineNum":" 1066","line":"            },"},
{"lineNum":" 1067","line":"            .Drive => {"},
{"lineNum":" 1068","line":"                break :x ascii.toUpper(parsed_from.disk_designator[0]) != ascii.toUpper(parsed_to.disk_designator[0]);"},
{"lineNum":" 1069","line":"            },"},
{"lineNum":" 1070","line":"            .None => {"},
{"lineNum":" 1071","line":"                break :x false;"},
{"lineNum":" 1072","line":"            },"},
{"lineNum":" 1073","line":"        }"},
{"lineNum":" 1074","line":"    };"},
{"lineNum":" 1075","line":""},
{"lineNum":" 1076","line":"    if (result_is_to) {"},
{"lineNum":" 1077","line":"        clean_up_resolved_to = false;"},
{"lineNum":" 1078","line":"        return resolved_to;"},
{"lineNum":" 1079","line":"    }"},
{"lineNum":" 1080","line":""},
{"lineNum":" 1081","line":"    var from_it = mem.tokenize(u8, resolved_from, \"/\\\\\");"},
{"lineNum":" 1082","line":"    var to_it = mem.tokenize(u8, resolved_to, \"/\\\\\");"},
{"lineNum":" 1083","line":"    while (true) {"},
{"lineNum":" 1084","line":"        const from_component = from_it.next() orelse return allocator.dupe(u8, to_it.rest());"},
{"lineNum":" 1085","line":"        const to_rest = to_it.rest();"},
{"lineNum":" 1086","line":"        if (to_it.next()) |to_component| {"},
{"lineNum":" 1087","line":"            // TODO ASCII is wrong, we actually need full unicode support to compare paths."},
{"lineNum":" 1088","line":"            if (ascii.eqlIgnoreCase(from_component, to_component))"},
{"lineNum":" 1089","line":"                continue;"},
{"lineNum":" 1090","line":"        }"},
{"lineNum":" 1091","line":"        var up_index_end = \"..\".len;"},
{"lineNum":" 1092","line":"        while (from_it.next()) |_| {"},
{"lineNum":" 1093","line":"            up_index_end += \"\\\\..\".len;"},
{"lineNum":" 1094","line":"        }"},
{"lineNum":" 1095","line":"        const result = try allocator.alloc(u8, up_index_end + @boolToInt(to_rest.len > 0) + to_rest.len);"},
{"lineNum":" 1096","line":"        errdefer allocator.free(result);"},
{"lineNum":" 1097","line":""},
{"lineNum":" 1098","line":"        result[0..2].* = \"..\".*;"},
{"lineNum":" 1099","line":"        var result_index: usize = 2;"},
{"lineNum":" 1100","line":"        while (result_index < up_index_end) {"},
{"lineNum":" 1101","line":"            result[result_index..][0..3].* = \"\\\\..\".*;"},
{"lineNum":" 1102","line":"            result_index += 3;"},
{"lineNum":" 1103","line":"        }"},
{"lineNum":" 1104","line":""},
{"lineNum":" 1105","line":"        var rest_it = mem.tokenize(u8, to_rest, \"/\\\\\");"},
{"lineNum":" 1106","line":"        while (rest_it.next()) |to_component| {"},
{"lineNum":" 1107","line":"            result[result_index] = \'\\\\\';"},
{"lineNum":" 1108","line":"            result_index += 1;"},
{"lineNum":" 1109","line":"            mem.copy(u8, result[result_index..], to_component);"},
{"lineNum":" 1110","line":"            result_index += to_component.len;"},
{"lineNum":" 1111","line":"        }"},
{"lineNum":" 1112","line":""},
{"lineNum":" 1113","line":"        return allocator.realloc(result, result_index);"},
{"lineNum":" 1114","line":"    }"},
{"lineNum":" 1115","line":""},
{"lineNum":" 1116","line":"    return [_]u8{};"},
{"lineNum":" 1117","line":"}"},
{"lineNum":" 1118","line":""},
{"lineNum":" 1119","line":"pub fn relativePosix(allocator: Allocator, from: []const u8, to: []const u8) ![]u8 {"},
{"lineNum":" 1120","line":"    const cwd = try process.getCwdAlloc(allocator);"},
{"lineNum":" 1121","line":"    defer allocator.free(cwd);"},
{"lineNum":" 1122","line":"    const resolved_from = try resolvePosix(allocator, &[_][]const u8{ cwd, from });"},
{"lineNum":" 1123","line":"    defer allocator.free(resolved_from);"},
{"lineNum":" 1124","line":"    const resolved_to = try resolvePosix(allocator, &[_][]const u8{ cwd, to });"},
{"lineNum":" 1125","line":"    defer allocator.free(resolved_to);"},
{"lineNum":" 1126","line":""},
{"lineNum":" 1127","line":"    var from_it = mem.tokenize(u8, resolved_from, \"/\");"},
{"lineNum":" 1128","line":"    var to_it = mem.tokenize(u8, resolved_to, \"/\");"},
{"lineNum":" 1129","line":"    while (true) {"},
{"lineNum":" 1130","line":"        const from_component = from_it.next() orelse return allocator.dupe(u8, to_it.rest());"},
{"lineNum":" 1131","line":"        const to_rest = to_it.rest();"},
{"lineNum":" 1132","line":"        if (to_it.next()) |to_component| {"},
{"lineNum":" 1133","line":"            if (mem.eql(u8, from_component, to_component))"},
{"lineNum":" 1134","line":"                continue;"},
{"lineNum":" 1135","line":"        }"},
{"lineNum":" 1136","line":"        var up_count: usize = 1;"},
{"lineNum":" 1137","line":"        while (from_it.next()) |_| {"},
{"lineNum":" 1138","line":"            up_count += 1;"},
{"lineNum":" 1139","line":"        }"},
{"lineNum":" 1140","line":"        const up_index_end = up_count * \"../\".len;"},
{"lineNum":" 1141","line":"        const result = try allocator.alloc(u8, up_index_end + to_rest.len);"},
{"lineNum":" 1142","line":"        errdefer allocator.free(result);"},
{"lineNum":" 1143","line":""},
{"lineNum":" 1144","line":"        var result_index: usize = 0;"},
{"lineNum":" 1145","line":"        while (result_index < up_index_end) {"},
{"lineNum":" 1146","line":"            result[result_index..][0..3].* = \"../\".*;"},
{"lineNum":" 1147","line":"            result_index += 3;"},
{"lineNum":" 1148","line":"        }"},
{"lineNum":" 1149","line":"        if (to_rest.len == 0) {"},
{"lineNum":" 1150","line":"            // shave off the trailing slash"},
{"lineNum":" 1151","line":"            return allocator.realloc(result, result_index - 1);"},
{"lineNum":" 1152","line":"        }"},
{"lineNum":" 1153","line":""},
{"lineNum":" 1154","line":"        mem.copy(u8, result[result_index..], to_rest);"},
{"lineNum":" 1155","line":"        return result;"},
{"lineNum":" 1156","line":"    }"},
{"lineNum":" 1157","line":""},
{"lineNum":" 1158","line":"    return [_]u8{};"},
{"lineNum":" 1159","line":"}"},
{"lineNum":" 1160","line":""},
{"lineNum":" 1161","line":"test \"relative\" {"},
{"lineNum":" 1162","line":"    try testRelativeWindows(\"c:/blah\\\\blah\", \"d:/games\", \"D:\\\\games\");"},
{"lineNum":" 1163","line":"    try testRelativeWindows(\"c:/aaaa/bbbb\", \"c:/aaaa\", \"..\");"},
{"lineNum":" 1164","line":"    try testRelativeWindows(\"c:/aaaa/bbbb\", \"c:/cccc\", \"..\\\\..\\\\cccc\");"},
{"lineNum":" 1165","line":"    try testRelativeWindows(\"c:/aaaa/bbbb\", \"c:/aaaa/bbbb\", \"\");"},
{"lineNum":" 1166","line":"    try testRelativeWindows(\"c:/aaaa/bbbb\", \"c:/aaaa/cccc\", \"..\\\\cccc\");"},
{"lineNum":" 1167","line":"    try testRelativeWindows(\"c:/aaaa/\", \"c:/aaaa/cccc\", \"cccc\");"},
{"lineNum":" 1168","line":"    try testRelativeWindows(\"c:/\", \"c:\\\\aaaa\\\\bbbb\", \"aaaa\\\\bbbb\");"},
{"lineNum":" 1169","line":"    try testRelativeWindows(\"c:/aaaa/bbbb\", \"d:\\\\\", \"D:\\\\\");"},
{"lineNum":" 1170","line":"    try testRelativeWindows(\"c:/AaAa/bbbb\", \"c:/aaaa/bbbb\", \"\");"},
{"lineNum":" 1171","line":"    try testRelativeWindows(\"c:/aaaaa/\", \"c:/aaaa/cccc\", \"..\\\\aaaa\\\\cccc\");"},
{"lineNum":" 1172","line":"    try testRelativeWindows(\"C:\\\\foo\\\\bar\\\\baz\\\\quux\", \"C:\\\\\", \"..\\\\..\\\\..\\\\..\");"},
{"lineNum":" 1173","line":"    try testRelativeWindows(\"C:\\\\foo\\\\test\", \"C:\\\\foo\\\\test\\\\bar\\\\package.json\", \"bar\\\\package.json\");"},
{"lineNum":" 1174","line":"    try testRelativeWindows(\"C:\\\\foo\\\\bar\\\\baz-quux\", \"C:\\\\foo\\\\bar\\\\baz\", \"..\\\\baz\");"},
{"lineNum":" 1175","line":"    try testRelativeWindows(\"C:\\\\foo\\\\bar\\\\baz\", \"C:\\\\foo\\\\bar\\\\baz-quux\", \"..\\\\baz-quux\");"},
{"lineNum":" 1176","line":"    try testRelativeWindows(\"\\\\\\\\foo\\\\bar\", \"\\\\\\\\foo\\\\bar\\\\baz\", \"baz\");"},
{"lineNum":" 1177","line":"    try testRelativeWindows(\"\\\\\\\\foo\\\\bar\\\\baz\", \"\\\\\\\\foo\\\\bar\", \"..\");"},
{"lineNum":" 1178","line":"    try testRelativeWindows(\"\\\\\\\\foo\\\\bar\\\\baz-quux\", \"\\\\\\\\foo\\\\bar\\\\baz\", \"..\\\\baz\");"},
{"lineNum":" 1179","line":"    try testRelativeWindows(\"\\\\\\\\foo\\\\bar\\\\baz\", \"\\\\\\\\foo\\\\bar\\\\baz-quux\", \"..\\\\baz-quux\");"},
{"lineNum":" 1180","line":"    try testRelativeWindows(\"C:\\\\baz-quux\", \"C:\\\\baz\", \"..\\\\baz\");"},
{"lineNum":" 1181","line":"    try testRelativeWindows(\"C:\\\\baz\", \"C:\\\\baz-quux\", \"..\\\\baz-quux\");"},
{"lineNum":" 1182","line":"    try testRelativeWindows(\"\\\\\\\\foo\\\\baz-quux\", \"\\\\\\\\foo\\\\baz\", \"..\\\\baz\");"},
{"lineNum":" 1183","line":"    try testRelativeWindows(\"\\\\\\\\foo\\\\baz\", \"\\\\\\\\foo\\\\baz-quux\", \"..\\\\baz-quux\");"},
{"lineNum":" 1184","line":"    try testRelativeWindows(\"C:\\\\baz\", \"\\\\\\\\foo\\\\bar\\\\baz\", \"\\\\\\\\foo\\\\bar\\\\baz\");"},
{"lineNum":" 1185","line":"    try testRelativeWindows(\"\\\\\\\\foo\\\\bar\\\\baz\", \"C:\\\\baz\", \"C:\\\\baz\");"},
{"lineNum":" 1186","line":""},
{"lineNum":" 1187","line":"    try testRelativeWindows(\"a/b/c\", \"a\\\\b\", \"..\");"},
{"lineNum":" 1188","line":"    try testRelativeWindows(\"a/b/c\", \"a\", \"..\\\\..\");"},
{"lineNum":" 1189","line":"    try testRelativeWindows(\"a/b/c\", \"a\\\\b\\\\c\\\\d\", \"d\");"},
{"lineNum":" 1190","line":""},
{"lineNum":" 1191","line":"    try testRelativePosix(\"/var/lib\", \"/var\", \"..\");"},
{"lineNum":" 1192","line":"    try testRelativePosix(\"/var/lib\", \"/bin\", \"../../bin\");"},
{"lineNum":" 1193","line":"    try testRelativePosix(\"/var/lib\", \"/var/lib\", \"\");"},
{"lineNum":" 1194","line":"    try testRelativePosix(\"/var/lib\", \"/var/apache\", \"../apache\");"},
{"lineNum":" 1195","line":"    try testRelativePosix(\"/var/\", \"/var/lib\", \"lib\");"},
{"lineNum":" 1196","line":"    try testRelativePosix(\"/\", \"/var/lib\", \"var/lib\");"},
{"lineNum":" 1197","line":"    try testRelativePosix(\"/foo/test\", \"/foo/test/bar/package.json\", \"bar/package.json\");"},
{"lineNum":" 1198","line":"    try testRelativePosix(\"/Users/a/web/b/test/mails\", \"/Users/a/web/b\", \"../..\");"},
{"lineNum":" 1199","line":"    try testRelativePosix(\"/foo/bar/baz-quux\", \"/foo/bar/baz\", \"../baz\");"},
{"lineNum":" 1200","line":"    try testRelativePosix(\"/foo/bar/baz\", \"/foo/bar/baz-quux\", \"../baz-quux\");"},
{"lineNum":" 1201","line":"    try testRelativePosix(\"/baz-quux\", \"/baz\", \"../baz\");"},
{"lineNum":" 1202","line":"    try testRelativePosix(\"/baz\", \"/baz-quux\", \"../baz-quux\");"},
{"lineNum":" 1203","line":"}"},
{"lineNum":" 1204","line":""},
{"lineNum":" 1205","line":"fn testRelativePosix(from: []const u8, to: []const u8, expected_output: []const u8) !void {"},
{"lineNum":" 1206","line":"    const result = try relativePosix(testing.allocator, from, to);"},
{"lineNum":" 1207","line":"    defer testing.allocator.free(result);"},
{"lineNum":" 1208","line":"    try testing.expectEqualStrings(expected_output, result);"},
{"lineNum":" 1209","line":"}"},
{"lineNum":" 1210","line":""},
{"lineNum":" 1211","line":"fn testRelativeWindows(from: []const u8, to: []const u8, expected_output: []const u8) !void {"},
{"lineNum":" 1212","line":"    const result = try relativeWindows(testing.allocator, from, to);"},
{"lineNum":" 1213","line":"    defer testing.allocator.free(result);"},
{"lineNum":" 1214","line":"    try testing.expectEqualStrings(expected_output, result);"},
{"lineNum":" 1215","line":"}"},
{"lineNum":" 1216","line":""},
{"lineNum":" 1217","line":"/// Returns the extension of the file name (if any)."},
{"lineNum":" 1218","line":"/// This function will search for the file extension (separated by a `.`) and will return the text after the `.`."},
{"lineNum":" 1219","line":"/// Files that end with `.`, or that start with `.` and have no other `.` in their name,"},
{"lineNum":" 1220","line":"/// are considered to have no extension."},
{"lineNum":" 1221","line":"/// Examples:"},
{"lineNum":" 1222","line":"/// - `\"main.zig\"`      ⇒ `\".zig\"`"},
{"lineNum":" 1223","line":"/// - `\"src/main.zig\"`  ⇒ `\".zig\"`"},
{"lineNum":" 1224","line":"/// - `\".gitignore\"`    ⇒ `\"\"`"},
{"lineNum":" 1225","line":"/// - `\".image.png\"`    ⇒ `\".png\"`"},
{"lineNum":" 1226","line":"/// - `\"keep.\"`         ⇒ `\".\"`"},
{"lineNum":" 1227","line":"/// - `\"src.keep.me\"`   ⇒ `\".me\"`"},
{"lineNum":" 1228","line":"/// - `\"/src/keep.me\"`  ⇒ `\".me\"`"},
{"lineNum":" 1229","line":"/// - `\"/src/keep.me/\"` ⇒ `\".me\"`"},
{"lineNum":" 1230","line":"/// The returned slice is guaranteed to have its pointer within the start and end"},
{"lineNum":" 1231","line":"/// pointer address range of `path`, even if it is length zero."},
{"lineNum":" 1232","line":"pub fn extension(path: []const u8) []const u8 {"},
{"lineNum":" 1233","line":"    const filename = basename(path);"},
{"lineNum":" 1234","line":"    const index = mem.lastIndexOfScalar(u8, filename, \'.\') orelse return path[path.len..];"},
{"lineNum":" 1235","line":"    if (index == 0) return path[path.len..];"},
{"lineNum":" 1236","line":"    return filename[index..];"},
{"lineNum":" 1237","line":"}"},
{"lineNum":" 1238","line":""},
{"lineNum":" 1239","line":"fn testExtension(path: []const u8, expected: []const u8) !void {"},
{"lineNum":" 1240","line":"    try testing.expectEqualStrings(expected, extension(path));"},
{"lineNum":" 1241","line":"}"},
{"lineNum":" 1242","line":""},
{"lineNum":" 1243","line":"test \"extension\" {"},
{"lineNum":" 1244","line":"    try testExtension(\"\", \"\");"},
{"lineNum":" 1245","line":"    try testExtension(\".\", \"\");"},
{"lineNum":" 1246","line":"    try testExtension(\"a.\", \".\");"},
{"lineNum":" 1247","line":"    try testExtension(\"abc.\", \".\");"},
{"lineNum":" 1248","line":"    try testExtension(\".a\", \"\");"},
{"lineNum":" 1249","line":"    try testExtension(\".file\", \"\");"},
{"lineNum":" 1250","line":"    try testExtension(\".gitignore\", \"\");"},
{"lineNum":" 1251","line":"    try testExtension(\".image.png\", \".png\");"},
{"lineNum":" 1252","line":"    try testExtension(\"file.ext\", \".ext\");"},
{"lineNum":" 1253","line":"    try testExtension(\"file.ext.\", \".\");"},
{"lineNum":" 1254","line":"    try testExtension(\"very-long-file.bruh\", \".bruh\");"},
{"lineNum":" 1255","line":"    try testExtension(\"a.b.c\", \".c\");"},
{"lineNum":" 1256","line":"    try testExtension(\"a.b.c/\", \".c\");"},
{"lineNum":" 1257","line":""},
{"lineNum":" 1258","line":"    try testExtension(\"/\", \"\");"},
{"lineNum":" 1259","line":"    try testExtension(\"/.\", \"\");"},
{"lineNum":" 1260","line":"    try testExtension(\"/a.\", \".\");"},
{"lineNum":" 1261","line":"    try testExtension(\"/abc.\", \".\");"},
{"lineNum":" 1262","line":"    try testExtension(\"/.a\", \"\");"},
{"lineNum":" 1263","line":"    try testExtension(\"/.file\", \"\");"},
{"lineNum":" 1264","line":"    try testExtension(\"/.gitignore\", \"\");"},
{"lineNum":" 1265","line":"    try testExtension(\"/file.ext\", \".ext\");"},
{"lineNum":" 1266","line":"    try testExtension(\"/file.ext.\", \".\");"},
{"lineNum":" 1267","line":"    try testExtension(\"/very-long-file.bruh\", \".bruh\");"},
{"lineNum":" 1268","line":"    try testExtension(\"/a.b.c\", \".c\");"},
{"lineNum":" 1269","line":"    try testExtension(\"/a.b.c/\", \".c\");"},
{"lineNum":" 1270","line":""},
{"lineNum":" 1271","line":"    try testExtension(\"/foo/bar/bam/\", \"\");"},
{"lineNum":" 1272","line":"    try testExtension(\"/foo/bar/bam/.\", \"\");"},
{"lineNum":" 1273","line":"    try testExtension(\"/foo/bar/bam/a.\", \".\");"},
{"lineNum":" 1274","line":"    try testExtension(\"/foo/bar/bam/abc.\", \".\");"},
{"lineNum":" 1275","line":"    try testExtension(\"/foo/bar/bam/.a\", \"\");"},
{"lineNum":" 1276","line":"    try testExtension(\"/foo/bar/bam/.file\", \"\");"},
{"lineNum":" 1277","line":"    try testExtension(\"/foo/bar/bam/.gitignore\", \"\");"},
{"lineNum":" 1278","line":"    try testExtension(\"/foo/bar/bam/file.ext\", \".ext\");"},
{"lineNum":" 1279","line":"    try testExtension(\"/foo/bar/bam/file.ext.\", \".\");"},
{"lineNum":" 1280","line":"    try testExtension(\"/foo/bar/bam/very-long-file.bruh\", \".bruh\");"},
{"lineNum":" 1281","line":"    try testExtension(\"/foo/bar/bam/a.b.c\", \".c\");"},
{"lineNum":" 1282","line":"    try testExtension(\"/foo/bar/bam/a.b.c/\", \".c\");"},
{"lineNum":" 1283","line":"}"},
{"lineNum":" 1284","line":""},
{"lineNum":" 1285","line":"/// Returns the last component of this path without its extension (if any):"},
{"lineNum":" 1286","line":"/// - \"hello/world/lib.tar.gz\" ⇒ \"lib.tar\""},
{"lineNum":" 1287","line":"/// - \"hello/world/lib.tar\"    ⇒ \"lib\""},
{"lineNum":" 1288","line":"/// - \"hello/world/lib\"        ⇒ \"lib\""},
{"lineNum":" 1289","line":"pub fn stem(path: []const u8) []const u8 {"},
{"lineNum":" 1290","line":"    const filename = basename(path);"},
{"lineNum":" 1291","line":"    const index = mem.lastIndexOfScalar(u8, filename, \'.\') orelse return filename[0..];"},
{"lineNum":" 1292","line":"    if (index == 0) return path;"},
{"lineNum":" 1293","line":"    return filename[0..index];"},
{"lineNum":" 1294","line":"}"},
{"lineNum":" 1295","line":""},
{"lineNum":" 1296","line":"fn testStem(path: []const u8, expected: []const u8) !void {"},
{"lineNum":" 1297","line":"    try testing.expectEqualStrings(expected, stem(path));"},
{"lineNum":" 1298","line":"}"},
{"lineNum":" 1299","line":""},
{"lineNum":" 1300","line":"test \"stem\" {"},
{"lineNum":" 1301","line":"    try testStem(\"hello/world/lib.tar.gz\", \"lib.tar\");"},
{"lineNum":" 1302","line":"    try testStem(\"hello/world/lib.tar\", \"lib\");"},
{"lineNum":" 1303","line":"    try testStem(\"hello/world/lib\", \"lib\");"},
{"lineNum":" 1304","line":"    try testStem(\"hello/lib/\", \"lib\");"},
{"lineNum":" 1305","line":"    try testStem(\"hello...\", \"hello..\");"},
{"lineNum":" 1306","line":"    try testStem(\"hello.\", \"hello\");"},
{"lineNum":" 1307","line":"    try testStem(\"/hello.\", \"hello\");"},
{"lineNum":" 1308","line":"    try testStem(\".gitignore\", \".gitignore\");"},
{"lineNum":" 1309","line":"    try testStem(\".image.png\", \".image\");"},
{"lineNum":" 1310","line":"    try testStem(\"file.ext\", \"file\");"},
{"lineNum":" 1311","line":"    try testStem(\"file.ext.\", \"file.ext\");"},
{"lineNum":" 1312","line":"    try testStem(\"a.b.c\", \"a.b\");"},
{"lineNum":" 1313","line":"    try testStem(\"a.b.c/\", \"a.b\");"},
{"lineNum":" 1314","line":"    try testStem(\".a\", \".a\");"},
{"lineNum":" 1315","line":"    try testStem(\"///\", \"\");"},
{"lineNum":" 1316","line":"    try testStem(\"..\", \".\");"},
{"lineNum":" 1317","line":"    try testStem(\".\", \".\");"},
{"lineNum":" 1318","line":"    try testStem(\" \", \" \");"},
{"lineNum":" 1319","line":"    try testStem(\"\", \"\");"},
{"lineNum":" 1320","line":"}"},
]};
var percent_low = 25;var percent_high = 75;
var header = { "command" : "test", "date" : "2023-04-18 20:41:50", "instrumented" : 50, "covered" : 0,};
var merged_data = [];
