var data = {lines:[
{"lineNum":"    1","line":"//! This API non-allocating, non-fallible, and thread-safe."},
{"lineNum":"    2","line":"//! The tradeoff is that users of this API must provide the storage"},
{"lineNum":"    3","line":"//! for each `Progress.Node`."},
{"lineNum":"    4","line":"//!"},
{"lineNum":"    5","line":"//! Initialize the struct directly, overriding these fields as desired:"},
{"lineNum":"    6","line":"//! * `refresh_rate_ms`"},
{"lineNum":"    7","line":"//! * `initial_delay_ms`"},
{"lineNum":"    8","line":""},
{"lineNum":"    9","line":"const std = @import(\"std\");"},
{"lineNum":"   10","line":"const builtin = @import(\"builtin\");"},
{"lineNum":"   11","line":"const windows = std.os.windows;"},
{"lineNum":"   12","line":"const testing = std.testing;"},
{"lineNum":"   13","line":"const assert = std.debug.assert;"},
{"lineNum":"   14","line":"const Progress = @This();"},
{"lineNum":"   15","line":""},
{"lineNum":"   16","line":"/// `null` if the current node (and its children) should"},
{"lineNum":"   17","line":"/// not print on update()"},
{"lineNum":"   18","line":"terminal: ?std.fs.File = undefined,"},
{"lineNum":"   19","line":""},
{"lineNum":"   20","line":"/// Is this a windows API terminal (note: this is not the same as being run on windows"},
{"lineNum":"   21","line":"/// because other terminals exist like MSYS/git-bash)"},
{"lineNum":"   22","line":"is_windows_terminal: bool = false,"},
{"lineNum":"   23","line":""},
{"lineNum":"   24","line":"/// Whether the terminal supports ANSI escape codes."},
{"lineNum":"   25","line":"supports_ansi_escape_codes: bool = false,"},
{"lineNum":"   26","line":""},
{"lineNum":"   27","line":"/// If the terminal is \"dumb\", don\'t print output."},
{"lineNum":"   28","line":"/// This can be useful if you don\'t want to print all"},
{"lineNum":"   29","line":"/// the stages of code generation if there are a lot."},
{"lineNum":"   30","line":"/// You should not use it if the user should see output"},
{"lineNum":"   31","line":"/// for example showing the user what tests run."},
{"lineNum":"   32","line":"dont_print_on_dumb: bool = false,"},
{"lineNum":"   33","line":""},
{"lineNum":"   34","line":"root: Node = undefined,"},
{"lineNum":"   35","line":""},
{"lineNum":"   36","line":"/// Keeps track of how much time has passed since the beginning."},
{"lineNum":"   37","line":"/// Used to compare with `initial_delay_ms` and `refresh_rate_ms`."},
{"lineNum":"   38","line":"timer: ?std.time.Timer = null,"},
{"lineNum":"   39","line":""},
{"lineNum":"   40","line":"/// When the previous refresh was written to the terminal."},
{"lineNum":"   41","line":"/// Used to compare with `refresh_rate_ms`."},
{"lineNum":"   42","line":"prev_refresh_timestamp: u64 = undefined,"},
{"lineNum":"   43","line":""},
{"lineNum":"   44","line":"/// This buffer represents the maximum number of bytes written to the terminal"},
{"lineNum":"   45","line":"/// with each refresh."},
{"lineNum":"   46","line":"output_buffer: [100]u8 = undefined,"},
{"lineNum":"   47","line":""},
{"lineNum":"   48","line":"/// How many nanoseconds between writing updates to the terminal."},
{"lineNum":"   49","line":"refresh_rate_ns: u64 = 50 * std.time.ns_per_ms,"},
{"lineNum":"   50","line":""},
{"lineNum":"   51","line":"/// How many nanoseconds to keep the output hidden"},
{"lineNum":"   52","line":"initial_delay_ns: u64 = 500 * std.time.ns_per_ms,"},
{"lineNum":"   53","line":""},
{"lineNum":"   54","line":"done: bool = true,"},
{"lineNum":"   55","line":""},
{"lineNum":"   56","line":"/// Protects the `refresh` function, as well as `node.recently_updated_child`."},
{"lineNum":"   57","line":"/// Without this, callsites would call `Node.end` and then free `Node` memory"},
{"lineNum":"   58","line":"/// while it was still being accessed by the `refresh` function."},
{"lineNum":"   59","line":"update_mutex: std.Thread.Mutex = .{},"},
{"lineNum":"   60","line":""},
{"lineNum":"   61","line":"/// Keeps track of how many columns in the terminal have been output, so that"},
{"lineNum":"   62","line":"/// we can move the cursor back later."},
{"lineNum":"   63","line":"columns_written: usize = undefined,"},
{"lineNum":"   64","line":""},
{"lineNum":"   65","line":"/// Represents one unit of progress. Each node can have children nodes, or"},
{"lineNum":"   66","line":"/// one can use integers with `update`."},
{"lineNum":"   67","line":"pub const Node = struct {"},
{"lineNum":"   68","line":"    context: *Progress,"},
{"lineNum":"   69","line":"    parent: ?*Node,"},
{"lineNum":"   70","line":"    name: []const u8,"},
{"lineNum":"   71","line":"    /// Must be handled atomically to be thread-safe."},
{"lineNum":"   72","line":"    recently_updated_child: ?*Node = null,"},
{"lineNum":"   73","line":"    /// Must be handled atomically to be thread-safe. 0 means null."},
{"lineNum":"   74","line":"    unprotected_estimated_total_items: usize,"},
{"lineNum":"   75","line":"    /// Must be handled atomically to be thread-safe."},
{"lineNum":"   76","line":"    unprotected_completed_items: usize,"},
{"lineNum":"   77","line":""},
{"lineNum":"   78","line":"    /// Create a new child progress node. Thread-safe."},
{"lineNum":"   79","line":"    /// Call `Node.end` when done."},
{"lineNum":"   80","line":"    /// TODO solve https://github.com/ziglang/zig/issues/2765 and then change this"},
{"lineNum":"   81","line":"    /// API to set `self.parent.recently_updated_child` with the return value."},
{"lineNum":"   82","line":"    /// Until that is fixed you probably want to call `activate` on the return value."},
{"lineNum":"   83","line":"    /// Passing 0 for `estimated_total_items` means unknown."},
{"lineNum":"   84","line":"    pub fn start(self: *Node, name: []const u8, estimated_total_items: usize) Node {","class":"lineCov","hits":"1","order":"487","possible_hits":"1",},
{"lineNum":"   85","line":"        return Node{","class":"lineCov","hits":"1","order":"489","possible_hits":"1",},
{"lineNum":"   86","line":"            .context = self.context,","class":"lineCov","hits":"1","order":"488","possible_hits":"1",},
{"lineNum":"   87","line":"            .parent = self,"},
{"lineNum":"   88","line":"            .name = name,"},
{"lineNum":"   89","line":"            .unprotected_estimated_total_items = estimated_total_items,"},
{"lineNum":"   90","line":"            .unprotected_completed_items = 0,"},
{"lineNum":"   91","line":"        };"},
{"lineNum":"   92","line":"    }"},
{"lineNum":"   93","line":""},
{"lineNum":"   94","line":"    /// This is the same as calling `start` and then `end` on the returned `Node`. Thread-safe."},
{"lineNum":"   95","line":"    pub fn completeOne(self: *Node) void {","class":"lineCov","hits":"1","order":"1619","possible_hits":"1",},
{"lineNum":"   96","line":"        if (self.parent) |parent| {","class":"lineCov","hits":"1","order":"1620","possible_hits":"1",},
{"lineNum":"   97","line":"            @atomicStore(?*Node, &parent.recently_updated_child, self, .Release);","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"   98","line":"        }"},
{"lineNum":"   99","line":"        _ = @atomicRmw(usize, &self.unprotected_completed_items, .Add, 1, .Monotonic);","class":"lineCov","hits":"1","order":"1621","possible_hits":"1",},
{"lineNum":"  100","line":"        self.context.maybeRefresh();","class":"lineCov","hits":"1","order":"1622","possible_hits":"1",},
{"lineNum":"  101","line":"    }"},
{"lineNum":"  102","line":""},
{"lineNum":"  103","line":"    /// Finish a started `Node`. Thread-safe."},
{"lineNum":"  104","line":"    pub fn end(self: *Node) void {","class":"lineCov","hits":"1","order":"1612","possible_hits":"1",},
{"lineNum":"  105","line":"        self.context.maybeRefresh();","class":"lineCov","hits":"1","order":"1613","possible_hits":"1",},
{"lineNum":"  106","line":"        if (self.parent) |parent| {","class":"lineCov","hits":"1","order":"1614","possible_hits":"1",},
{"lineNum":"  107","line":"            {"},
{"lineNum":"  108","line":"                self.context.update_mutex.lock();","class":"lineCov","hits":"1","order":"1615","possible_hits":"1",},
{"lineNum":"  109","line":"                defer self.context.update_mutex.unlock();","class":"lineCov","hits":"1","order":"1617","possible_hits":"1",},
{"lineNum":"  110","line":"                _ = @cmpxchgStrong(?*Node, &parent.recently_updated_child, self, null, .Monotonic, .Monotonic);","class":"lineCov","hits":"1","order":"1616","possible_hits":"1",},
{"lineNum":"  111","line":"            }"},
{"lineNum":"  112","line":"            parent.completeOne();","class":"lineCov","hits":"1","order":"1618","possible_hits":"1",},
{"lineNum":"  113","line":"        } else {"},
{"lineNum":"  114","line":"            self.context.update_mutex.lock();","class":"lineCov","hits":"1","order":"2077","possible_hits":"1",},
{"lineNum":"  115","line":"            defer self.context.update_mutex.unlock();","class":"lineCov","hits":"1","order":"2080","possible_hits":"1",},
{"lineNum":"  116","line":"            self.context.done = true;","class":"lineCov","hits":"1","order":"2078","possible_hits":"1",},
{"lineNum":"  117","line":"            self.context.refreshWithHeldLock();","class":"lineCov","hits":"1","order":"2079","possible_hits":"1",},
{"lineNum":"  118","line":"        }"},
{"lineNum":"  119","line":"    }"},
{"lineNum":"  120","line":""},
{"lineNum":"  121","line":"    /// Tell the parent node that this node is actively being worked on. Thread-safe."},
{"lineNum":"  122","line":"    pub fn activate(self: *Node) void {","class":"lineCov","hits":"1","order":"491","possible_hits":"1",},
{"lineNum":"  123","line":"        if (self.parent) |parent| {","class":"lineCov","hits":"1","order":"492","possible_hits":"1",},
{"lineNum":"  124","line":"            @atomicStore(?*Node, &parent.recently_updated_child, self, .Release);","class":"lineCov","hits":"1","order":"493","possible_hits":"1",},
{"lineNum":"  125","line":"            self.context.maybeRefresh();","class":"lineCov","hits":"1","order":"494","possible_hits":"1",},
{"lineNum":"  126","line":"        }"},
{"lineNum":"  127","line":"    }"},
{"lineNum":"  128","line":""},
{"lineNum":"  129","line":"    /// Thread-safe."},
{"lineNum":"  130","line":"    pub fn setName(self: *Node, name: []const u8) void {"},
{"lineNum":"  131","line":"        const progress = self.context;"},
{"lineNum":"  132","line":"        progress.update_mutex.lock();"},
{"lineNum":"  133","line":"        defer progress.update_mutex.unlock();"},
{"lineNum":"  134","line":"        self.name = name;"},
{"lineNum":"  135","line":"        if (self.parent) |parent| {"},
{"lineNum":"  136","line":"            @atomicStore(?*Node, &parent.recently_updated_child, self, .Release);"},
{"lineNum":"  137","line":"            if (parent.parent) |grand_parent| {"},
{"lineNum":"  138","line":"                @atomicStore(?*Node, &grand_parent.recently_updated_child, parent, .Release);"},
{"lineNum":"  139","line":"            }"},
{"lineNum":"  140","line":"            if (progress.timer) |*timer| progress.maybeRefreshWithHeldLock(timer);"},
{"lineNum":"  141","line":"        }"},
{"lineNum":"  142","line":"    }"},
{"lineNum":"  143","line":""},
{"lineNum":"  144","line":"    /// Thread-safe. 0 means unknown."},
{"lineNum":"  145","line":"    pub fn setEstimatedTotalItems(self: *Node, count: usize) void {"},
{"lineNum":"  146","line":"        @atomicStore(usize, &self.unprotected_estimated_total_items, count, .Monotonic);"},
{"lineNum":"  147","line":"    }"},
{"lineNum":"  148","line":""},
{"lineNum":"  149","line":"    /// Thread-safe."},
{"lineNum":"  150","line":"    pub fn setCompletedItems(self: *Node, completed_items: usize) void {"},
{"lineNum":"  151","line":"        @atomicStore(usize, &self.unprotected_completed_items, completed_items, .Monotonic);"},
{"lineNum":"  152","line":"    }"},
{"lineNum":"  153","line":"};"},
{"lineNum":"  154","line":""},
{"lineNum":"  155","line":"/// Create a new progress node."},
{"lineNum":"  156","line":"/// Call `Node.end` when done."},
{"lineNum":"  157","line":"/// TODO solve https://github.com/ziglang/zig/issues/2765 and then change this"},
{"lineNum":"  158","line":"/// API to return Progress rather than accept it as a parameter."},
{"lineNum":"  159","line":"/// `estimated_total_items` value of 0 means unknown."},
{"lineNum":"  160","line":"pub fn start(self: *Progress, name: []const u8, estimated_total_items: usize) *Node {","class":"lineCov","hits":"1","order":"344","possible_hits":"1",},
{"lineNum":"  161","line":"    const stderr = std.io.getStdErr();","class":"lineCov","hits":"1","order":"345","possible_hits":"1",},
{"lineNum":"  162","line":"    self.terminal = null;","class":"lineCov","hits":"1","order":"351","possible_hits":"1",},
{"lineNum":"  163","line":"    if (stderr.supportsAnsiEscapeCodes()) {","class":"lineCov","hits":"1","order":"352","possible_hits":"1",},
{"lineNum":"  164","line":"        self.terminal = stderr;","class":"lineCov","hits":"1","order":"388","possible_hits":"1",},
{"lineNum":"  165","line":"        self.supports_ansi_escape_codes = true;","class":"lineCov","hits":"1","order":"389","possible_hits":"1",},
{"lineNum":"  166","line":"    } else if (builtin.os.tag == .windows and stderr.isTty()) {"},
{"lineNum":"  167","line":"        self.is_windows_terminal = true;"},
{"lineNum":"  168","line":"        self.terminal = stderr;"},
{"lineNum":"  169","line":"    } else if (builtin.os.tag != .windows) {"},
{"lineNum":"  170","line":"        // we are in a \"dumb\" terminal like in acme or writing to a file"},
{"lineNum":"  171","line":"        self.terminal = stderr;","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"  172","line":"    }"},
{"lineNum":"  173","line":"    self.root = Node{","class":"lineCov","hits":"1","order":"390","possible_hits":"1",},
{"lineNum":"  174","line":"        .context = self,"},
{"lineNum":"  175","line":"        .parent = null,"},
{"lineNum":"  176","line":"        .name = name,"},
{"lineNum":"  177","line":"        .unprotected_estimated_total_items = estimated_total_items,"},
{"lineNum":"  178","line":"        .unprotected_completed_items = 0,"},
{"lineNum":"  179","line":"    };"},
{"lineNum":"  180","line":"    self.columns_written = 0;","class":"lineCov","hits":"1","order":"391","possible_hits":"1",},
{"lineNum":"  181","line":"    self.prev_refresh_timestamp = 0;","class":"lineCov","hits":"1","order":"392","possible_hits":"1",},
{"lineNum":"  182","line":"    self.timer = std.time.Timer.start() catch null;","class":"lineCov","hits":"1","order":"393","possible_hits":"1",},
{"lineNum":"  183","line":"    self.done = false;","class":"lineCov","hits":"1","order":"476","possible_hits":"1",},
{"lineNum":"  184","line":"    return &self.root;","class":"lineCov","hits":"1","order":"477","possible_hits":"1",},
{"lineNum":"  185","line":"}"},
{"lineNum":"  186","line":""},
{"lineNum":"  187","line":"/// Updates the terminal if enough time has passed since last update. Thread-safe."},
{"lineNum":"  188","line":"pub fn maybeRefresh(self: *Progress) void {","class":"lineCov","hits":"1","order":"495","possible_hits":"1",},
{"lineNum":"  189","line":"    if (self.timer) |*timer| {","class":"lineCov","hits":"1","order":"496","possible_hits":"1",},
{"lineNum":"  190","line":"        if (!self.update_mutex.tryLock()) return;","class":"linePartCov","hits":"1","order":"497","possible_hits":"2",},
{"lineNum":"  191","line":"        defer self.update_mutex.unlock();","class":"linePartCov","hits":"1","order":"555","possible_hits":"2",},
{"lineNum":"  192","line":"        maybeRefreshWithHeldLock(self, timer);","class":"lineCov","hits":"1","order":"528","possible_hits":"1",},
{"lineNum":"  193","line":"    }"},
{"lineNum":"  194","line":"}"},
{"lineNum":"  195","line":""},
{"lineNum":"  196","line":"fn maybeRefreshWithHeldLock(self: *Progress, timer: *std.time.Timer) void {","class":"lineCov","hits":"1","order":"529","possible_hits":"1",},
{"lineNum":"  197","line":"    const now = timer.read();","class":"lineCov","hits":"1","order":"530","possible_hits":"1",},
{"lineNum":"  198","line":"    if (now < self.initial_delay_ns) return;","class":"lineCov","hits":"1","order":"554","possible_hits":"1",},
{"lineNum":"  199","line":"    // TODO I have observed this to happen sometimes. I think we need to follow Rust\'s"},
{"lineNum":"  200","line":"    // lead and guarantee monotonically increasing times in the std lib itself."},
{"lineNum":"  201","line":"    if (now < self.prev_refresh_timestamp) return;","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"  202","line":"    if (now - self.prev_refresh_timestamp < self.refresh_rate_ns) return;","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"  203","line":"    return self.refreshWithHeldLock();","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"  204","line":"}"},
{"lineNum":"  205","line":""},
{"lineNum":"  206","line":"/// Updates the terminal and resets `self.next_refresh_timestamp`. Thread-safe."},
{"lineNum":"  207","line":"pub fn refresh(self: *Progress) void {","class":"lineCov","hits":"1","order":"569","possible_hits":"1",},
{"lineNum":"  208","line":"    if (!self.update_mutex.tryLock()) return;","class":"lineCov","hits":"1","order":"570","possible_hits":"1",},
{"lineNum":"  209","line":"    defer self.update_mutex.unlock();","class":"lineCov","hits":"1","order":"692","possible_hits":"1",},
{"lineNum":"  210","line":""},
{"lineNum":"  211","line":"    return self.refreshWithHeldLock();","class":"lineCov","hits":"2","order":"571","possible_hits":"2",},
{"lineNum":"  212","line":"}"},
{"lineNum":"  213","line":""},
{"lineNum":"  214","line":"fn clearWithHeldLock(p: *Progress, end_ptr: *usize) void {","class":"lineCov","hits":"1","order":"578","possible_hits":"1",},
{"lineNum":"  215","line":"    const file = p.terminal orelse return;","class":"lineCov","hits":"1","order":"579","possible_hits":"1",},
{"lineNum":"  216","line":"    var end = end_ptr.*;","class":"lineCov","hits":"1","order":"580","possible_hits":"1",},
{"lineNum":"  217","line":"    if (p.columns_written > 0) {","class":"lineCov","hits":"1","order":"581","possible_hits":"1",},
{"lineNum":"  218","line":"        // restore the cursor position by moving the cursor"},
{"lineNum":"  219","line":"        // `columns_written` cells to the left, then clear the rest of the"},
{"lineNum":"  220","line":"        // line"},
{"lineNum":"  221","line":"        if (p.supports_ansi_escape_codes) {","class":"lineCov","hits":"1","order":"1657","possible_hits":"1",},
{"lineNum":"  222","line":"            end += (std.fmt.bufPrint(p.output_buffer[end..], \"\\x1b[{d}D\", .{p.columns_written}) catch unreachable).len;","class":"lineCov","hits":"2","order":"1658","possible_hits":"2",},
{"lineNum":"  223","line":"            end += (std.fmt.bufPrint(p.output_buffer[end..], \"\\x1b[0K\", .{}) catch unreachable).len;","class":"lineCov","hits":"1","order":"1659","possible_hits":"1",},
{"lineNum":"  224","line":"        } else if (builtin.os.tag == .windows) winapi: {"},
{"lineNum":"  225","line":"            std.debug.assert(p.is_windows_terminal);"},
{"lineNum":"  226","line":""},
{"lineNum":"  227","line":"            var info: windows.CONSOLE_SCREEN_BUFFER_INFO = undefined;"},
{"lineNum":"  228","line":"            if (windows.kernel32.GetConsoleScreenBufferInfo(file.handle, &info) != windows.TRUE) {"},
{"lineNum":"  229","line":"                // stop trying to write to this file"},
{"lineNum":"  230","line":"                p.terminal = null;"},
{"lineNum":"  231","line":"                break :winapi;"},
{"lineNum":"  232","line":"            }"},
{"lineNum":"  233","line":""},
{"lineNum":"  234","line":"            var cursor_pos = windows.COORD{"},
{"lineNum":"  235","line":"                .X = info.dwCursorPosition.X - @intCast(windows.SHORT, p.columns_written),"},
{"lineNum":"  236","line":"                .Y = info.dwCursorPosition.Y,"},
{"lineNum":"  237","line":"            };"},
{"lineNum":"  238","line":""},
{"lineNum":"  239","line":"            if (cursor_pos.X < 0)"},
{"lineNum":"  240","line":"                cursor_pos.X = 0;"},
{"lineNum":"  241","line":""},
{"lineNum":"  242","line":"            const fill_chars = @intCast(windows.DWORD, info.dwSize.X - cursor_pos.X);"},
{"lineNum":"  243","line":""},
{"lineNum":"  244","line":"            var written: windows.DWORD = undefined;"},
{"lineNum":"  245","line":"            if (windows.kernel32.FillConsoleOutputAttribute("},
{"lineNum":"  246","line":"                file.handle,"},
{"lineNum":"  247","line":"                info.wAttributes,"},
{"lineNum":"  248","line":"                fill_chars,"},
{"lineNum":"  249","line":"                cursor_pos,"},
{"lineNum":"  250","line":"                &written,"},
{"lineNum":"  251","line":"            ) != windows.TRUE) {"},
{"lineNum":"  252","line":"                // stop trying to write to this file"},
{"lineNum":"  253","line":"                p.terminal = null;"},
{"lineNum":"  254","line":"                break :winapi;"},
{"lineNum":"  255","line":"            }"},
{"lineNum":"  256","line":"            if (windows.kernel32.FillConsoleOutputCharacterW("},
{"lineNum":"  257","line":"                file.handle,"},
{"lineNum":"  258","line":"                \' \',"},
{"lineNum":"  259","line":"                fill_chars,"},
{"lineNum":"  260","line":"                cursor_pos,"},
{"lineNum":"  261","line":"                &written,"},
{"lineNum":"  262","line":"            ) != windows.TRUE) {"},
{"lineNum":"  263","line":"                // stop trying to write to this file"},
{"lineNum":"  264","line":"                p.terminal = null;"},
{"lineNum":"  265","line":"                break :winapi;"},
{"lineNum":"  266","line":"            }"},
{"lineNum":"  267","line":"            if (windows.kernel32.SetConsoleCursorPosition(file.handle, cursor_pos) != windows.TRUE) {"},
{"lineNum":"  268","line":"                // stop trying to write to this file"},
{"lineNum":"  269","line":"                p.terminal = null;"},
{"lineNum":"  270","line":"                break :winapi;"},
{"lineNum":"  271","line":"            }"},
{"lineNum":"  272","line":"        } else {"},
{"lineNum":"  273","line":"            // we are in a \"dumb\" terminal like in acme or writing to a file"},
{"lineNum":"  274","line":"            p.output_buffer[end] = \'\\n\';","class":"lineNoCov","hits":"0","possible_hits":"2",},
{"lineNum":"  275","line":"            end += 1;","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"  276","line":"        }"},
{"lineNum":"  277","line":""},
{"lineNum":"  278","line":"        p.columns_written = 0;","class":"lineCov","hits":"2","order":"582","possible_hits":"2",},
{"lineNum":"  279","line":"    }"},
{"lineNum":"  280","line":"    end_ptr.* = end;","class":"lineCov","hits":"1","order":"583","possible_hits":"1",},
{"lineNum":"  281","line":"}"},
{"lineNum":"  282","line":""},
{"lineNum":"  283","line":"fn refreshWithHeldLock(self: *Progress) void {","class":"lineCov","hits":"1","order":"572","possible_hits":"1",},
{"lineNum":"  284","line":"    const is_dumb = !self.supports_ansi_escape_codes and !self.is_windows_terminal;","class":"lineCov","hits":"1","order":"573","possible_hits":"1",},
{"lineNum":"  285","line":"    if (is_dumb and self.dont_print_on_dumb) return;","class":"lineCov","hits":"1","order":"574","possible_hits":"1",},
{"lineNum":"  286","line":""},
{"lineNum":"  287","line":"    const file = self.terminal orelse return;","class":"lineCov","hits":"1","order":"575","possible_hits":"1",},
{"lineNum":"  288","line":""},
{"lineNum":"  289","line":"    var end: usize = 0;","class":"lineCov","hits":"1","order":"576","possible_hits":"1",},
{"lineNum":"  290","line":"    clearWithHeldLock(self, &end);","class":"lineCov","hits":"1","order":"577","possible_hits":"1",},
{"lineNum":"  291","line":""},
{"lineNum":"  292","line":"    if (!self.done) {","class":"lineCov","hits":"1","order":"584","possible_hits":"1",},
{"lineNum":"  293","line":"        var need_ellipse = false;","class":"lineCov","hits":"1","order":"585","possible_hits":"1",},
{"lineNum":"  294","line":"        var maybe_node: ?*Node = &self.root;","class":"lineCov","hits":"1","order":"586","possible_hits":"1",},
{"lineNum":"  295","line":"        while (maybe_node) |node| {","class":"lineCov","hits":"1","order":"587","possible_hits":"1",},
{"lineNum":"  296","line":"            if (need_ellipse) {","class":"lineCov","hits":"1","order":"588","possible_hits":"1",},
{"lineNum":"  297","line":"                self.bufWrite(&end, \"... \", .{});","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"  298","line":"            }"},
{"lineNum":"  299","line":"            need_ellipse = false;","class":"lineCov","hits":"1","order":"589","possible_hits":"1",},
{"lineNum":"  300","line":"            const eti = @atomicLoad(usize, &node.unprotected_estimated_total_items, .Monotonic);","class":"lineCov","hits":"1","order":"590","possible_hits":"1",},
{"lineNum":"  301","line":"            const completed_items = @atomicLoad(usize, &node.unprotected_completed_items, .Monotonic);","class":"lineCov","hits":"1","order":"591","possible_hits":"1",},
{"lineNum":"  302","line":"            const current_item = completed_items + 1;","class":"lineCov","hits":"1","order":"592","possible_hits":"1",},
{"lineNum":"  303","line":"            if (node.name.len != 0 or eti > 0) {","class":"lineCov","hits":"1","order":"593","possible_hits":"1",},
{"lineNum":"  304","line":"                if (node.name.len != 0) {","class":"lineCov","hits":"1","order":"594","possible_hits":"1",},
{"lineNum":"  305","line":"                    self.bufWrite(&end, \"{s}\", .{node.name});","class":"lineCov","hits":"1","order":"595","possible_hits":"1",},
{"lineNum":"  306","line":"                    need_ellipse = true;","class":"lineCov","hits":"1","order":"638","possible_hits":"1",},
{"lineNum":"  307","line":"                }"},
{"lineNum":"  308","line":"                if (eti > 0) {","class":"lineCov","hits":"1","order":"639","possible_hits":"1",},
{"lineNum":"  309","line":"                    if (need_ellipse) self.bufWrite(&end, \" \", .{});","class":"lineCov","hits":"2","order":"640","possible_hits":"2",},
{"lineNum":"  310","line":"                    self.bufWrite(&end, \"[{d}/{d}] \", .{ current_item, eti });","class":"lineCov","hits":"1","order":"642","possible_hits":"1",},
{"lineNum":"  311","line":"                    need_ellipse = false;","class":"lineCov","hits":"1","order":"673","possible_hits":"1",},
{"lineNum":"  312","line":"                } else if (completed_items != 0) {","class":"lineCov","hits":"1","order":"675","possible_hits":"1",},
{"lineNum":"  313","line":"                    if (need_ellipse) self.bufWrite(&end, \" \", .{});","class":"lineNoCov","hits":"0","possible_hits":"2",},
{"lineNum":"  314","line":"                    self.bufWrite(&end, \"[{d}] \", .{current_item});","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"  315","line":"                    need_ellipse = false;","class":"linePartCov","hits":"1","order":"676","possible_hits":"3",},
{"lineNum":"  316","line":"                }"},
{"lineNum":"  317","line":"            }"},
{"lineNum":"  318","line":"            maybe_node = @atomicLoad(?*Node, &node.recently_updated_child, .Acquire);","class":"lineCov","hits":"2","order":"674","possible_hits":"2",},
{"lineNum":"  319","line":"        }"},
{"lineNum":"  320","line":"        if (need_ellipse) {","class":"lineCov","hits":"1","order":"677","possible_hits":"1",},
{"lineNum":"  321","line":"            self.bufWrite(&end, \"... \", .{});","class":"lineCov","hits":"2","order":"678","possible_hits":"2",},
{"lineNum":"  322","line":"        }"},
{"lineNum":"  323","line":"    }"},
{"lineNum":"  324","line":""},
{"lineNum":"  325","line":"    _ = file.write(self.output_buffer[0..end]) catch {","class":"lineCov","hits":"1","order":"679","possible_hits":"1",},
{"lineNum":"  326","line":"        // stop trying to write to this file"},
{"lineNum":"  327","line":"        self.terminal = null;","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"  328","line":"    };"},
{"lineNum":"  329","line":"    if (self.timer) |*timer| {","class":"lineCov","hits":"1","order":"690","possible_hits":"1",},
{"lineNum":"  330","line":"        self.prev_refresh_timestamp = timer.read();","class":"lineCov","hits":"1","order":"691","possible_hits":"1",},
{"lineNum":"  331","line":"    }"},
{"lineNum":"  332","line":"}"},
{"lineNum":"  333","line":""},
{"lineNum":"  334","line":"pub fn log(self: *Progress, comptime format: []const u8, args: anytype) void {","class":"lineNoCov","hits":"0","possible_hits":"3",},
{"lineNum":"  335","line":"    const file = self.terminal orelse {","class":"lineNoCov","hits":"0","possible_hits":"3",},
{"lineNum":"  336","line":"        std.debug.print(format, args);","class":"lineNoCov","hits":"0","possible_hits":"3",},
{"lineNum":"  337","line":"        return;","class":"lineNoCov","hits":"0","possible_hits":"3",},
{"lineNum":"  338","line":"    };"},
{"lineNum":"  339","line":"    self.refresh();","class":"lineNoCov","hits":"0","possible_hits":"3",},
{"lineNum":"  340","line":"    file.writer().print(format, args) catch {","class":"lineNoCov","hits":"0","possible_hits":"3",},
{"lineNum":"  341","line":"        self.terminal = null;","class":"lineNoCov","hits":"0","possible_hits":"3",},
{"lineNum":"  342","line":"        return;","class":"lineNoCov","hits":"0","possible_hits":"3",},
{"lineNum":"  343","line":"    };"},
{"lineNum":"  344","line":"    self.columns_written = 0;","class":"lineNoCov","hits":"0","possible_hits":"3",},
{"lineNum":"  345","line":"}"},
{"lineNum":"  346","line":""},
{"lineNum":"  347","line":"/// Allows the caller to freely write to stderr until unlock_stderr() is called."},
{"lineNum":"  348","line":"/// During the lock, the progress information is cleared from the terminal."},
{"lineNum":"  349","line":"pub fn lock_stderr(p: *Progress) void {"},
{"lineNum":"  350","line":"    p.update_mutex.lock();"},
{"lineNum":"  351","line":"    if (p.terminal) |file| {"},
{"lineNum":"  352","line":"        var end: usize = 0;"},
{"lineNum":"  353","line":"        clearWithHeldLock(p, &end);"},
{"lineNum":"  354","line":"        _ = file.write(p.output_buffer[0..end]) catch {"},
{"lineNum":"  355","line":"            // stop trying to write to this file"},
{"lineNum":"  356","line":"            p.terminal = null;"},
{"lineNum":"  357","line":"        };"},
{"lineNum":"  358","line":"    }"},
{"lineNum":"  359","line":"    std.debug.getStderrMutex().lock();"},
{"lineNum":"  360","line":"}"},
{"lineNum":"  361","line":""},
{"lineNum":"  362","line":"pub fn unlock_stderr(p: *Progress) void {"},
{"lineNum":"  363","line":"    std.debug.getStderrMutex().unlock();"},
{"lineNum":"  364","line":"    p.update_mutex.unlock();"},
{"lineNum":"  365","line":"}"},
{"lineNum":"  366","line":""},
{"lineNum":"  367","line":"fn bufWrite(self: *Progress, end: *usize, comptime format: []const u8, args: anytype) void {","class":"linePartCov","hits":"4","order":"596","possible_hits":"7",},
{"lineNum":"  368","line":"    if (std.fmt.bufPrint(self.output_buffer[end.*..], format, args)) |written| {","class":"linePartCov","hits":"4","order":"597","possible_hits":"7",},
{"lineNum":"  369","line":"        const amt = written.len;","class":"linePartCov","hits":"4","order":"635","possible_hits":"7",},
{"lineNum":"  370","line":"        end.* += amt;","class":"linePartCov","hits":"8","order":"636","possible_hits":"14",},
{"lineNum":"  371","line":"        self.columns_written += amt;","class":"linePartCov","hits":"4","order":"637","possible_hits":"14",},
{"lineNum":"  372","line":"    } else |err| switch (err) {","class":"lineNoCov","hits":"0","possible_hits":"21",},
{"lineNum":"  373","line":"        error.NoSpaceLeft => {"},
{"lineNum":"  374","line":"            self.columns_written += self.output_buffer.len - end.*;","class":"lineNoCov","hits":"0","possible_hits":"7",},
{"lineNum":"  375","line":"            end.* = self.output_buffer.len;","class":"lineNoCov","hits":"0","possible_hits":"7",},
{"lineNum":"  376","line":"            const suffix = \"... \";","class":"lineNoCov","hits":"0","possible_hits":"7",},
{"lineNum":"  377","line":"            std.mem.copy(u8, self.output_buffer[self.output_buffer.len - suffix.len ..], suffix);","class":"lineNoCov","hits":"0","possible_hits":"7",},
{"lineNum":"  378","line":"        },"},
{"lineNum":"  379","line":"    }"},
{"lineNum":"  380","line":"}"},
{"lineNum":"  381","line":""},
{"lineNum":"  382","line":"test \"basic functionality\" {"},
{"lineNum":"  383","line":"    var disable = true;"},
{"lineNum":"  384","line":"    if (disable) {"},
{"lineNum":"  385","line":"        // This test is disabled because it uses time.sleep() and is therefore slow. It also"},
{"lineNum":"  386","line":"        // prints bogus progress data to stderr."},
{"lineNum":"  387","line":"        return error.SkipZigTest;"},
{"lineNum":"  388","line":"    }"},
{"lineNum":"  389","line":"    var progress = Progress{};"},
{"lineNum":"  390","line":"    const root_node = progress.start(\"\", 100);"},
{"lineNum":"  391","line":"    defer root_node.end();"},
{"lineNum":"  392","line":""},
{"lineNum":"  393","line":"    const speed_factor = std.time.ns_per_ms;"},
{"lineNum":"  394","line":""},
{"lineNum":"  395","line":"    const sub_task_names = [_][]const u8{"},
{"lineNum":"  396","line":"        \"reticulating splines\","},
{"lineNum":"  397","line":"        \"adjusting shoes\","},
{"lineNum":"  398","line":"        \"climbing towers\","},
{"lineNum":"  399","line":"        \"pouring juice\","},
{"lineNum":"  400","line":"    };"},
{"lineNum":"  401","line":"    var next_sub_task: usize = 0;"},
{"lineNum":"  402","line":""},
{"lineNum":"  403","line":"    var i: usize = 0;"},
{"lineNum":"  404","line":"    while (i < 100) : (i += 1) {"},
{"lineNum":"  405","line":"        var node = root_node.start(sub_task_names[next_sub_task], 5);"},
{"lineNum":"  406","line":"        node.activate();"},
{"lineNum":"  407","line":"        next_sub_task = (next_sub_task + 1) % sub_task_names.len;"},
{"lineNum":"  408","line":""},
{"lineNum":"  409","line":"        node.completeOne();"},
{"lineNum":"  410","line":"        std.time.sleep(5 * speed_factor);"},
{"lineNum":"  411","line":"        node.completeOne();"},
{"lineNum":"  412","line":"        node.completeOne();"},
{"lineNum":"  413","line":"        std.time.sleep(5 * speed_factor);"},
{"lineNum":"  414","line":"        node.completeOne();"},
{"lineNum":"  415","line":"        node.completeOne();"},
{"lineNum":"  416","line":"        std.time.sleep(5 * speed_factor);"},
{"lineNum":"  417","line":""},
{"lineNum":"  418","line":"        node.end();"},
{"lineNum":"  419","line":""},
{"lineNum":"  420","line":"        std.time.sleep(5 * speed_factor);"},
{"lineNum":"  421","line":"    }"},
{"lineNum":"  422","line":"    {"},
{"lineNum":"  423","line":"        var node = root_node.start(\"this is a really long name designed to activate the truncation code. let\'s find out if it works\", 0);"},
{"lineNum":"  424","line":"        node.activate();"},
{"lineNum":"  425","line":"        std.time.sleep(10 * speed_factor);"},
{"lineNum":"  426","line":"        progress.refresh();"},
{"lineNum":"  427","line":"        std.time.sleep(10 * speed_factor);"},
{"lineNum":"  428","line":"        node.end();"},
{"lineNum":"  429","line":"    }"},
{"lineNum":"  430","line":"}"},
]};
var percent_low = 25;var percent_high = 75;
var header = { "command" : "test", "date" : "2023-04-18 20:41:50", "instrumented" : 116, "covered" : 91,};
var merged_data = [];
