var data = {lines:[
{"lineNum":"    1","line":"//! This file contains various semantic checks relating to arguments and fields, including default arguments/fields, and"},
{"lineNum":"    2","line":"//! named arguments/fields."},
{"lineNum":"    3","line":""},
{"lineNum":"    4","line":"const std = @import(\"std\");"},
{"lineNum":"    5","line":"const ast_ = @import(\"../ast/ast.zig\");"},
{"lineNum":"    6","line":"const errs_ = @import(\"../util/errors.zig\");"},
{"lineNum":"    7","line":"const Span = @import(\"../util/span.zig\");"},
{"lineNum":"    8","line":"const Type_AST = @import(\"../types/type.zig\").Type_AST;"},
{"lineNum":"    9","line":""},
{"lineNum":"   10","line":"const Validate_Error_Enum = error{CompileError};"},
{"lineNum":"   11","line":""},
{"lineNum":"   12","line":"pub const Validate_Args_Thing = enum {"},
{"lineNum":"   13","line":"    function,"},
{"lineNum":"   14","line":"    method,"},
{"lineNum":"   15","line":"    context,"},
{"lineNum":"   16","line":"    @\"struct\","},
{"lineNum":"   17","line":"    tuple,"},
{"lineNum":"   18","line":"    array,"},
{"lineNum":"   19","line":""},
{"lineNum":"   20","line":"    fn thing_name(self: @This()) []const u8 {","class":"lineCov","hits":"2","order":"5179","possible_hits":"2",},
{"lineNum":"   21","line":"        return @tagName(self);","class":"lineCov","hits":"1","order":"5180","possible_hits":"1",},
{"lineNum":"   22","line":"    }"},
{"lineNum":"   23","line":""},
{"lineNum":"   24","line":"    fn takes_name(self: @This()) []const u8 {","class":"lineCov","hits":"2","order":"5182","possible_hits":"2",},
{"lineNum":"   25","line":"        return switch (self) {","class":"lineCov","hits":"1","order":"5183","possible_hits":"1",},
{"lineNum":"   26","line":"            .context, .function, .method => \"parameter\","},
{"lineNum":"   27","line":"            .@\"struct\" => \"field\","},
{"lineNum":"   28","line":"            .tuple, .array => \"element\","},
{"lineNum":"   29","line":"        };"},
{"lineNum":"   30","line":"    }"},
{"lineNum":"   31","line":""},
{"lineNum":"   32","line":"    fn given_name(self: @This()) []const u8 {","class":"lineCov","hits":"2","order":"5185","possible_hits":"2",},
{"lineNum":"   33","line":"        return switch (self) {","class":"lineCov","hits":"1","order":"5186","possible_hits":"1",},
{"lineNum":"   34","line":"            .context, .function, .method => \"argument\","},
{"lineNum":"   35","line":"            .@\"struct\" => \"value\","},
{"lineNum":"   36","line":"            .tuple, .array => \"element\","},
{"lineNum":"   37","line":"        };"},
{"lineNum":"   38","line":"    }"},
{"lineNum":"   39","line":"};"},
{"lineNum":"   40","line":""},
{"lineNum":"   41","line":"// This has to be ok to do twice for the same args, because stamps have to do it internally."},
{"lineNum":"   42","line":"pub fn default_args("},
{"lineNum":"   43","line":"    thing: Validate_Args_Thing,"},
{"lineNum":"   44","line":"    asts: std.array_list.Managed(*ast_.AST), // The args for a call, or the terms for a struct"},
{"lineNum":"   45","line":"    call_span: Span,"},
{"lineNum":"   46","line":"    expected: *Type_AST,"},
{"lineNum":"   47","line":"    errors: *errs_.Errors,"},
{"lineNum":"   48","line":"    allocator: std.mem.Allocator,"},
{"lineNum":"   49","line":") Validate_Error_Enum!std.array_list.Managed(*ast_.AST) {","class":"lineCov","hits":"2","order":"2284","possible_hits":"2",},
{"lineNum":"   50","line":"    if (try args_are_named(asts, errors) and expected.* != .unit_type) {","class":"lineCov","hits":"1","order":"2285","possible_hits":"1",},
{"lineNum":"   51","line":"        return named_args(thing, asts, call_span, expected, errors, allocator) catch |err| switch (err) {","class":"lineCov","hits":"2","order":"6609","possible_hits":"2",},
{"lineNum":"   52","line":"            error.NoDefault => error.CompileError,"},
{"lineNum":"   53","line":"            error.CompileError => error.CompileError,"},
{"lineNum":"   54","line":"        };"},
{"lineNum":"   55","line":"    } else {"},
{"lineNum":"   56","line":"        return positional_args(thing, asts, call_span, expected, errors, allocator) catch |err| switch (err) {","class":"lineCov","hits":"2","order":"2297","possible_hits":"2",},
{"lineNum":"   57","line":"            error.NoDefault => error.CompileError,"},
{"lineNum":"   58","line":"        };"},
{"lineNum":"   59","line":"    }"},
{"lineNum":"   60","line":"}"},
{"lineNum":"   61","line":""},
{"lineNum":"   62","line":"/// Determines if there are named arguments in an argument list. If there are no arguments, there are"},
{"lineNum":"   63","line":"/// no named arguments."},
{"lineNum":"   64","line":"///"},
{"lineNum":"   65","line":"/// Throws `error.CompileError` if there is a mix of positional and named arguments."},
{"lineNum":"   66","line":"fn args_are_named("},
{"lineNum":"   67","line":"    asts: std.array_list.Managed(*ast_.AST),"},
{"lineNum":"   68","line":"    errors: *errs_.Errors,"},
{"lineNum":"   69","line":") Validate_Error_Enum!bool {","class":"lineCov","hits":"2","order":"2286","possible_hits":"2",},
{"lineNum":"   70","line":"    if (asts.items.len == 0) {","class":"lineCov","hits":"1","order":"2287","possible_hits":"1",},
{"lineNum":"   71","line":"        return false;","class":"lineCov","hits":"1","order":"5174","possible_hits":"1",},
{"lineNum":"   72","line":"    }"},
{"lineNum":"   73","line":""},
{"lineNum":"   74","line":"    var has_named_arg = false;","class":"lineCov","hits":"1","order":"2288","possible_hits":"1",},
{"lineNum":"   75","line":"    var has_pos_arg = false;","class":"lineCov","hits":"1","order":"2289","possible_hits":"1",},
{"lineNum":"   76","line":"    for (asts.items) |term| {","class":"lineCov","hits":"3","order":"2290","possible_hits":"3",},
{"lineNum":"   77","line":"        if (term.* == .assign) {","class":"lineCov","hits":"1","order":"2291","possible_hits":"1",},
{"lineNum":"   78","line":"            has_named_arg = true;","class":"lineCov","hits":"1","order":"6608","possible_hits":"1",},
{"lineNum":"   79","line":"        } else {"},
{"lineNum":"   80","line":"            has_pos_arg = true;","class":"lineCov","hits":"1","order":"2292","possible_hits":"1",},
{"lineNum":"   81","line":"        }"},
{"lineNum":"   82","line":"    }","class":"lineCov","hits":"2","order":"2293","possible_hits":"2",},
{"lineNum":"   83","line":"    std.debug.assert(has_named_arg or has_pos_arg);","class":"lineCov","hits":"3","order":"2294","possible_hits":"3",},
{"lineNum":"   84","line":"    if (has_named_arg and has_pos_arg) {","class":"lineCov","hits":"2","order":"2295","possible_hits":"2",},
{"lineNum":"   85","line":"        const arg_span = asts.items[0].token().span;","class":"lineCov","hits":"3","order":"6645","possible_hits":"3",},
{"lineNum":"   86","line":"        errors.add_error(errs_.Error{ .basic = .{ .span = arg_span, .msg = \"mixed positional and named arguments are not allowed\" } });","class":"lineCov","hits":"1","order":"6646","possible_hits":"1",},
{"lineNum":"   87","line":"        return error.CompileError;","class":"lineCov","hits":"1","order":"6647","possible_hits":"1",},
{"lineNum":"   88","line":"    } else {"},
{"lineNum":"   89","line":"        return has_named_arg;","class":"lineCov","hits":"1","order":"2296","possible_hits":"1",},
{"lineNum":"   90","line":"    }"},
{"lineNum":"   91","line":"}"},
{"lineNum":"   92","line":""},
{"lineNum":"   93","line":"/// Accepts a list of AST arguments, the expected parameter type, and if the ASTs list isn\'t long enough for the parameters, prepends the"},
{"lineNum":"   94","line":"/// default values for each missing argument."},
{"lineNum":"   95","line":"///"},
{"lineNum":"   96","line":"/// Returns NoDefault when a default value cannot be created"},
{"lineNum":"   97","line":"fn positional_args("},
{"lineNum":"   98","line":"    thing: Validate_Args_Thing,"},
{"lineNum":"   99","line":"    asts: std.array_list.Managed(*ast_.AST),"},
{"lineNum":"  100","line":"    call_span: Span,"},
{"lineNum":"  101","line":"    expected: *Type_AST,"},
{"lineNum":"  102","line":"    errors: *errs_.Errors,"},
{"lineNum":"  103","line":"    allocator: std.mem.Allocator,"},
{"lineNum":"  104","line":") error{NoDefault}!std.array_list.Managed(*ast_.AST) {","class":"lineCov","hits":"2","order":"2298","possible_hits":"2",},
{"lineNum":"  105","line":"    // TODO: Too long"},
{"lineNum":"  106","line":"    var filled_args = std.array_list.Managed(*ast_.AST).init(allocator);","class":"lineCov","hits":"1","order":"2299","possible_hits":"1",},
{"lineNum":"  107","line":"    errdefer filled_args.deinit();","class":"lineCov","hits":"2","order":"6644","possible_hits":"2",},
{"lineNum":"  108","line":""},
{"lineNum":"  109","line":"    switch (expected.*) {","class":"lineCov","hits":"3","order":"2300","possible_hits":"3",},
{"lineNum":"  110","line":"        .annotation => {"},
{"lineNum":"  111","line":"            if (asts.items.len == 0 and expected.annotation.init != null) {","class":"lineCov","hits":"2","order":"5596","possible_hits":"2",},
{"lineNum":"  112","line":"                // Use expected\'s init, asts are empty"},
{"lineNum":"  113","line":"                filled_args.append(expected.annotation.init.?) catch unreachable;","class":"lineNoCov","hits":"0","possible_hits":"2",},
{"lineNum":"  114","line":"            } else if (asts.items.len > 0) {","class":"lineCov","hits":"2","order":"5597","possible_hits":"2",},
{"lineNum":"  115","line":"                // Copy asts over to filled_args"},
{"lineNum":"  116","line":"                for (asts.items) |item| {","class":"lineCov","hits":"3","order":"5598","possible_hits":"3",},
{"lineNum":"  117","line":"                    filled_args.append(item) catch unreachable;","class":"lineCov","hits":"2","order":"5599","possible_hits":"2",},
{"lineNum":"  118","line":"                }","class":"lineCov","hits":"3","order":"5600","possible_hits":"3",},
{"lineNum":"  119","line":"            } else {"},
{"lineNum":"  120","line":"                // empty args, no default init in parameter. No default possible!"},
{"lineNum":"  121","line":"                errors.add_error(errs_.Error{ .mismatch_arity = .{","class":"lineCov","hits":"2","order":"6775","possible_hits":"2",},
{"lineNum":"  122","line":"                    .span = call_span,"},
{"lineNum":"  123","line":"                    .takes = 1,"},
{"lineNum":"  124","line":"                    .given = 0,"},
{"lineNum":"  125","line":"                    .thing_name = thing.thing_name(),","class":"lineCov","hits":"1","order":"6776","possible_hits":"1",},
{"lineNum":"  126","line":"                    .takes_name = thing.takes_name(),","class":"lineCov","hits":"1","order":"6777","possible_hits":"1",},
{"lineNum":"  127","line":"                    .given_name = thing.given_name(),","class":"lineCov","hits":"1","order":"6778","possible_hits":"1",},
{"lineNum":"  128","line":"                } });"},
{"lineNum":"  129","line":"                return error.NoDefault;","class":"lineCov","hits":"4","order":"2301","possible_hits":"4",},
{"lineNum":"  130","line":"            }"},
{"lineNum":"  131","line":"        },"},
{"lineNum":"  132","line":""},
{"lineNum":"  133","line":"        .struct_type, .tuple_type => {"},
{"lineNum":"  134","line":"            for (expected.children().items, 0..) |term, i| {","class":"lineCov","hits":"3","order":"2302","possible_hits":"3",},
{"lineNum":"  135","line":"                // ast is struct, append ast\'s corresponding term"},
{"lineNum":"  136","line":"                if (asts.items.len > 1 and i < asts.items.len) {","class":"lineCov","hits":"2","order":"2303","possible_hits":"2",},
{"lineNum":"  137","line":"                    filled_args.append(asts.items[i]) catch unreachable;","class":"lineCov","hits":"2","order":"2304","possible_hits":"2",},
{"lineNum":"  138","line":"                }"},
{"lineNum":"  139","line":"                // ast is unit or ast isn\'t a struct and i > 0 or ast is a struct and off the edge of ast\'s terms"},
{"lineNum":"  140","line":"                // try to fill with the default"},
{"lineNum":"  141","line":"                else if (asts.items.len == 0 or (asts.items.len <= 1 and i > 0) or (asts.items.len > 1 and i >= asts.items.len)) {","class":"lineCov","hits":"2","order":"2306","possible_hits":"2",},
{"lineNum":"  142","line":"                    if (term.* == .annotation and term.annotation.init != null) {","class":"lineCov","hits":"2","order":"2307","possible_hits":"2",},
{"lineNum":"  143","line":"                        filled_args.append(term.annotation.init.?) catch unreachable;","class":"lineCov","hits":"2","order":"2308","possible_hits":"2",},
{"lineNum":"  144","line":"                    } else {"},
{"lineNum":"  145","line":"                        errors.add_error(errs_.Error{ .mismatch_arity = .{","class":"lineCov","hits":"2","order":"6638","possible_hits":"2",},
{"lineNum":"  146","line":"                            .span = call_span,"},
{"lineNum":"  147","line":"                            .takes = expected.children().items.len,","class":"lineCov","hits":"1","order":"6639","possible_hits":"1",},
{"lineNum":"  148","line":"                            .given = asts.items.len,","class":"lineCov","hits":"1","order":"6640","possible_hits":"1",},
{"lineNum":"  149","line":"                            .thing_name = thing.thing_name(),","class":"lineCov","hits":"1","order":"6641","possible_hits":"1",},
{"lineNum":"  150","line":"                            .takes_name = thing.takes_name(),","class":"lineCov","hits":"1","order":"6642","possible_hits":"1",},
{"lineNum":"  151","line":"                            .given_name = thing.given_name(),","class":"lineCov","hits":"1","order":"6643","possible_hits":"1",},
{"lineNum":"  152","line":"                        } });"},
{"lineNum":"  153","line":"                        return error.NoDefault;","class":"lineCov","hits":"2","order":"2309","possible_hits":"2",},
{"lineNum":"  154","line":"                    }"},
{"lineNum":"  155","line":"                }"},
{"lineNum":"  156","line":"                // ast is not struct, i != 0, append ast as first term"},
{"lineNum":"  157","line":"                else {"},
{"lineNum":"  158","line":"                    filled_args.append(asts.items[0]) catch unreachable;","class":"lineCov","hits":"3","order":"2310","possible_hits":"3",},
{"lineNum":"  159","line":"                }"},
{"lineNum":"  160","line":"            }","class":"lineCov","hits":"3","order":"2305","possible_hits":"3",},
{"lineNum":"  161","line":"        },"},
{"lineNum":"  162","line":""},
{"lineNum":"  163","line":"        else => filled_args = asts,","class":"lineCov","hits":"1","order":"5175","possible_hits":"1",},
{"lineNum":"  164","line":""},
{"lineNum":"  165","line":"        // else => std.debug.panic(\"compiler error: positional_args(): unimplemented for {s}\", .{@tagName(expected.*)}),"},
{"lineNum":"  166","line":"    }"},
{"lineNum":"  167","line":"    if (filled_args.items.len < asts.items.len) {","class":"linePartCov","hits":"1","order":"2311","possible_hits":"2",},
{"lineNum":"  168","line":"        // Add the rest, for extern variadic function calls"},
{"lineNum":"  169","line":"        for (filled_args.items.len..asts.items.len) |i| {","class":"lineNoCov","hits":"0","possible_hits":"5",},
{"lineNum":"  170","line":"            filled_args.append(asts.items[i]) catch unreachable;","class":"lineNoCov","hits":"0","possible_hits":"2",},
{"lineNum":"  171","line":"        }","class":"linePartCov","hits":"1","order":"2312","possible_hits":"5",},
{"lineNum":"  172","line":"    }"},
{"lineNum":"  173","line":"    return filled_args;","class":"lineCov","hits":"1","order":"2313","possible_hits":"1",},
{"lineNum":"  174","line":"}"},
{"lineNum":"  175","line":""},
{"lineNum":"  176","line":"fn named_args("},
{"lineNum":"  177","line":"    thing: Validate_Args_Thing,"},
{"lineNum":"  178","line":"    asts: std.array_list.Managed(*ast_.AST),"},
{"lineNum":"  179","line":"    call_span: Span,"},
{"lineNum":"  180","line":"    expected: *Type_AST,"},
{"lineNum":"  181","line":"    errors: *errs_.Errors,"},
{"lineNum":"  182","line":"    allocator: std.mem.Allocator,"},
{"lineNum":"  183","line":") (Validate_Error_Enum || error{NoDefault})!std.array_list.Managed(*ast_.AST) {","class":"lineCov","hits":"2","order":"6610","possible_hits":"2",},
{"lineNum":"  184","line":"    // FIXME: High cyclo"},
{"lineNum":"  185","line":"    std.debug.assert(asts.items.len > 0);","class":"lineCov","hits":"1","order":"6611","possible_hits":"1",},
{"lineNum":"  186","line":"    // Maps assign.lhs name to assign.rhs"},
{"lineNum":"  187","line":"    var arg_name_to_val_map = std.StringArrayHashMap(*ast_.AST).init(allocator);","class":"lineCov","hits":"1","order":"6612","possible_hits":"1",},
{"lineNum":"  188","line":"    defer arg_name_to_val_map.deinit();","class":"linePartCov","hits":"4","order":"6619","possible_hits":"6",},
{"lineNum":"  189","line":""},
{"lineNum":"  190","line":"    // Associate argument names with their values"},
{"lineNum":"  191","line":"    for (asts.items) |term| {","class":"lineCov","hits":"3","order":"6613","possible_hits":"3",},
{"lineNum":"  192","line":"        put_assign(term, &arg_name_to_val_map, errors) catch |err| switch (err) {","class":"lineCov","hits":"2","order":"6614","possible_hits":"2",},
{"lineNum":"  193","line":"            error.CompileError => return error.NoDefault,","class":"lineCov","hits":"1","order":"6620","possible_hits":"1",},
{"lineNum":"  194","line":"            else => return err,","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"  195","line":"        };"},
{"lineNum":"  196","line":"    }","class":"lineCov","hits":"2","order":"6625","possible_hits":"2",},
{"lineNum":"  197","line":""},
{"lineNum":"  198","line":"    // Construct positional args in the order specified by `expected`"},
{"lineNum":"  199","line":"    var filled_args = std.array_list.Managed(*ast_.AST).init(allocator);","class":"lineCov","hits":"1","order":"6626","possible_hits":"1",},
{"lineNum":"  200","line":"    errdefer filled_args.deinit();","class":"linePartCov","hits":"2","order":"6635","possible_hits":"3",},
{"lineNum":"  201","line":"    switch (expected.*) {","class":"linePartCov","hits":"1","order":"6627","possible_hits":"3",},
{"lineNum":"  202","line":"        .annotation => {"},
{"lineNum":"  203","line":"            if (arg_name_to_val_map.keys().len > 1) { // Cannot be 0, since that is technically a positional arglist","class":"lineCov","hits":"1","order":"6628","possible_hits":"1",},
{"lineNum":"  204","line":"                errors.add_error(errs_.Error{ .mismatch_arity = .{","class":"lineCov","hits":"2","order":"6629","possible_hits":"2",},
{"lineNum":"  205","line":"                    .span = asts.items[0].token().span,","class":"lineCov","hits":"3","order":"6630","possible_hits":"3",},
{"lineNum":"  206","line":"                    .takes = 1,"},
{"lineNum":"  207","line":"                    .given = arg_name_to_val_map.keys().len,","class":"lineCov","hits":"1","order":"6631","possible_hits":"1",},
{"lineNum":"  208","line":"                    .thing_name = thing.thing_name(),","class":"lineCov","hits":"1","order":"6632","possible_hits":"1",},
{"lineNum":"  209","line":"                    .takes_name = thing.takes_name(),","class":"lineCov","hits":"1","order":"6633","possible_hits":"1",},
{"lineNum":"  210","line":"                    .given_name = thing.given_name(),","class":"lineCov","hits":"1","order":"6634","possible_hits":"1",},
{"lineNum":"  211","line":"                } });"},
{"lineNum":"  212","line":"                return error.NoDefault;","class":"lineCov","hits":"1","order":"6636","possible_hits":"1",},
{"lineNum":"  213","line":"            } else {"},
{"lineNum":"  214","line":"                filled_args.append(arg_name_to_val_map.values()[0]) catch unreachable;","class":"linePartCov","hits":"1","order":"6649","possible_hits":"4",},
{"lineNum":"  215","line":"            }"},
{"lineNum":"  216","line":"        },"},
{"lineNum":"  217","line":""},
{"lineNum":"  218","line":"        .struct_type, .tuple_type => {"},
{"lineNum":"  219","line":"            for (expected.children().items) |term| {","class":"lineCov","hits":"3","order":"6650","possible_hits":"3",},
{"lineNum":"  220","line":"                if (term.* != .annotation) {","class":"lineCov","hits":"1","order":"6651","possible_hits":"1",},
{"lineNum":"  221","line":"                    errors.add_error(errs_.Error{ .basic = .{","class":"lineNoCov","hits":"0","possible_hits":"2",},
{"lineNum":"  222","line":"                        .span = asts.items[0].token().span,","class":"lineNoCov","hits":"0","possible_hits":"3",},
{"lineNum":"  223","line":"                        .msg = \"expected type does not accept named fields\","},
{"lineNum":"  224","line":"                    } });"},
{"lineNum":"  225","line":"                    return error.NoDefault;","class":"linePartCov","hits":"1","order":"6652","possible_hits":"2",},
{"lineNum":"  226","line":"                }"},
{"lineNum":"  227","line":"                const arg = arg_name_to_val_map.get(term.annotation.pattern.token().data);","class":"lineCov","hits":"3","order":"6653","possible_hits":"3",},
{"lineNum":"  228","line":"                if (arg == null) {","class":"lineCov","hits":"1","order":"6654","possible_hits":"1",},
{"lineNum":"  229","line":"                    if (term.annotation.init != null) {","class":"lineCov","hits":"2","order":"6659","possible_hits":"2",},
{"lineNum":"  230","line":"                        filled_args.append(term.annotation.init.?) catch unreachable;","class":"lineNoCov","hits":"0","possible_hits":"2",},
{"lineNum":"  231","line":"                    } else {"},
{"lineNum":"  232","line":"                        // Value is not provided, and there is no default init, ERROR!"},
{"lineNum":"  233","line":"                        errors.add_error(errs_.Error{ .mismatch_arity = .{","class":"lineCov","hits":"2","order":"6660","possible_hits":"2",},
{"lineNum":"  234","line":"                            .span = call_span,"},
{"lineNum":"  235","line":"                            .takes = expected.children().items.len,","class":"lineCov","hits":"1","order":"6661","possible_hits":"1",},
{"lineNum":"  236","line":"                            .given = arg_name_to_val_map.keys().len,","class":"lineCov","hits":"1","order":"6662","possible_hits":"1",},
{"lineNum":"  237","line":"                            .thing_name = thing.thing_name(),","class":"lineCov","hits":"1","order":"6663","possible_hits":"1",},
{"lineNum":"  238","line":"                            .takes_name = thing.takes_name(),","class":"lineCov","hits":"1","order":"6664","possible_hits":"1",},
{"lineNum":"  239","line":"                            .given_name = thing.given_name(),","class":"lineCov","hits":"1","order":"6665","possible_hits":"1",},
{"lineNum":"  240","line":"                        } });"},
{"lineNum":"  241","line":"                        return error.NoDefault;","class":"linePartCov","hits":"1","order":"6666","possible_hits":"2",},
{"lineNum":"  242","line":"                    }"},
{"lineNum":"  243","line":"                } else {"},
{"lineNum":"  244","line":"                    filled_args.append(arg.?) catch unreachable;","class":"lineCov","hits":"2","order":"6655","possible_hits":"2",},
{"lineNum":"  245","line":"                }"},
{"lineNum":"  246","line":"            }","class":"lineCov","hits":"4","order":"6656","possible_hits":"4",},
{"lineNum":"  247","line":"        },"},
{"lineNum":"  248","line":""},
{"lineNum":"  249","line":"        else => std.debug.panic(\"compiler error: unimplemented named_args() for `{f}`\", .{expected.*}),","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"  250","line":"    }"},
{"lineNum":"  251","line":"    return filled_args;","class":"lineCov","hits":"2","order":"6657","possible_hits":"2",},
{"lineNum":"  252","line":"}"},
{"lineNum":"  253","line":""},
{"lineNum":"  254","line":"fn put_assign(ast: *ast_.AST, arg_map: *std.StringArrayHashMap(*ast_.AST), errors: *errs_.Errors) Validate_Error_Enum!void {","class":"lineCov","hits":"2","order":"6615","possible_hits":"2",},
{"lineNum":"  255","line":"    if (ast.lhs().* != .enum_value) {","class":"lineCov","hits":"1","order":"6616","possible_hits":"1",},
{"lineNum":"  256","line":"        errors.add_error(errs_.Error{ .expected_basic_token = .{ .expected = \"an named argument\", .got = ast.lhs().token() } });","class":"lineCov","hits":"1","order":"6617","possible_hits":"1",},
{"lineNum":"  257","line":"        return error.CompileError;","class":"lineCov","hits":"1","order":"6618","possible_hits":"1",},
{"lineNum":"  258","line":"    }"},
{"lineNum":"  259","line":"    try put_ast_map(ast.rhs(), ast.lhs().enum_value.get_name(), ast.token().span, arg_map, errors);","class":"lineCov","hits":"2","order":"6621","possible_hits":"2",},
{"lineNum":"  260","line":"}"},
{"lineNum":"  261","line":""},
{"lineNum":"  262","line":"/// Puts an ast into a String->AST map, if a given name isn\'t already in the map."},
{"lineNum":"  263","line":"pub fn put_ast_map("},
{"lineNum":"  264","line":"    ast: *ast_.AST,"},
{"lineNum":"  265","line":"    name: []const u8,"},
{"lineNum":"  266","line":"    span: Span,"},
{"lineNum":"  267","line":"    map: *std.StringArrayHashMap(*ast_.AST),"},
{"lineNum":"  268","line":"    errors: *errs_.Errors,"},
{"lineNum":"  269","line":") Validate_Error_Enum!void {","class":"lineCov","hits":"2","order":"6622","possible_hits":"2",},
{"lineNum":"  270","line":"    if (map.get(name)) |_| {","class":"lineCov","hits":"1","order":"6623","possible_hits":"1",},
{"lineNum":"  271","line":"        errors.add_error(errs_.Error{ .duplicate = .{","class":"lineCov","hits":"1","order":"6648","possible_hits":"1",},
{"lineNum":"  272","line":"            .span = span,"},
{"lineNum":"  273","line":"            .identifier = name,"},
{"lineNum":"  274","line":"            .first = null,"},
{"lineNum":"  275","line":"        } });"},
{"lineNum":"  276","line":"    } else {"},
{"lineNum":"  277","line":"        map.put(name, ast) catch unreachable;","class":"lineCov","hits":"2","order":"6624","possible_hits":"2",},
{"lineNum":"  278","line":"    }"},
{"lineNum":"  279","line":"}"},
{"lineNum":"  280","line":""},
{"lineNum":"  281","line":"/// Checks to see if an argument is meant for a method with a value receiver, and if so, implicitly takes the"},
{"lineNum":"  282","line":"/// address of the argument."},
{"lineNum":"  283","line":"pub fn implicit_ref("},
{"lineNum":"  284","line":"    args: *std.array_list.Managed(*ast_.AST),"},
{"lineNum":"  285","line":"    expected: *Type_AST,"},
{"lineNum":"  286","line":"    allocator: std.mem.Allocator,"},
{"lineNum":"  287","line":") void {","class":"lineCov","hits":"2","order":"4513","possible_hits":"2",},
{"lineNum":"  288","line":"    const param_type = if (expected.* == .struct_type or expected.* == .tuple_type or expected.* == .context_type) expected.children().items[0] else expected;","class":"lineCov","hits":"2","order":"4514","possible_hits":"2",},
{"lineNum":"  289","line":"    if (param_type.* == .annotation and","class":"lineCov","hits":"1","order":"4515","possible_hits":"1",},
{"lineNum":"  290","line":"        param_type.annotation.pattern.* == .receiver and","class":"lineCov","hits":"1","order":"4516","possible_hits":"1",},
{"lineNum":"  291","line":"        param_type.child().* == .addr_of and","class":"lineCov","hits":"1","order":"4517","possible_hits":"1",},
{"lineNum":"  292","line":"        param_type.annotation.pattern.receiver.kind == .value)","class":"lineCov","hits":"1","order":"4518","possible_hits":"1",},
{"lineNum":"  293","line":"    {"},
{"lineNum":"  294","line":"        const old_arg = args.items[0];","class":"lineNoCov","hits":"0","possible_hits":"3",},
{"lineNum":"  295","line":"        args.items[0] = ast_.AST.create_addr_of(old_arg.token(), old_arg, false, false, allocator);","class":"linePartCov","hits":"2","order":"4519","possible_hits":"4",},
{"lineNum":"  296","line":"    }"},
{"lineNum":"  297","line":"}"},
{"lineNum":"  298","line":""},
{"lineNum":"  299","line":"/// Validates that the number of arguments matches the number of parameters"},
{"lineNum":"  300","line":"pub fn validate_args_arity("},
{"lineNum":"  301","line":"    thing: Validate_Args_Thing,"},
{"lineNum":"  302","line":"    args: *std.array_list.Managed(*ast_.AST),"},
{"lineNum":"  303","line":"    expected: *Type_AST,"},
{"lineNum":"  304","line":"    variadic: bool,"},
{"lineNum":"  305","line":"    span: Span,"},
{"lineNum":"  306","line":"    errors: *errs_.Errors,"},
{"lineNum":"  307","line":") Validate_Error_Enum!void {","class":"lineCov","hits":"2","order":"2319","possible_hits":"2",},
{"lineNum":"  308","line":"    const expected_length = if (expected.* == .unit_type) 0 else if (expected.* == .struct_type or expected.* == .tuple_type) expected.children().items.len else 1;","class":"lineCov","hits":"2","order":"2320","possible_hits":"2",},
{"lineNum":"  309","line":"    if (variadic) {","class":"lineCov","hits":"1","order":"2321","possible_hits":"1",},
{"lineNum":"  310","line":"        if (args.items.len < expected_length) {","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"  311","line":"            errors.add_error(errs_.Error{ .mismatch_arity = .{","class":"lineNoCov","hits":"0","possible_hits":"2",},
{"lineNum":"  312","line":"                .span = span,"},
{"lineNum":"  313","line":"                .takes = expected_length,"},
{"lineNum":"  314","line":"                .given = args.items.len,","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"  315","line":"                .thing_name = thing.thing_name(),","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"  316","line":"                .takes_name = thing.takes_name(),","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"  317","line":"                .given_name = thing.given_name(),","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"  318","line":"            } });"},
{"lineNum":"  319","line":"            return error.CompileError;","class":"lineNoCov","hits":"0","possible_hits":"2",},
{"lineNum":"  320","line":"        }"},
{"lineNum":"  321","line":"    } else if (args.items.len != expected_length) {","class":"lineCov","hits":"1","order":"2322","possible_hits":"1",},
{"lineNum":"  322","line":"        errors.add_error(errs_.Error{ .mismatch_arity = .{","class":"lineCov","hits":"2","order":"5176","possible_hits":"2",},
{"lineNum":"  323","line":"            .span = span,"},
{"lineNum":"  324","line":"            .takes = expected_length,"},
{"lineNum":"  325","line":"            .given = args.items.len,","class":"lineCov","hits":"1","order":"5177","possible_hits":"1",},
{"lineNum":"  326","line":"            .thing_name = thing.thing_name(),","class":"lineCov","hits":"1","order":"5178","possible_hits":"1",},
{"lineNum":"  327","line":"            .takes_name = thing.takes_name(),","class":"lineCov","hits":"1","order":"5181","possible_hits":"1",},
{"lineNum":"  328","line":"            .given_name = thing.given_name(),","class":"lineCov","hits":"1","order":"5184","possible_hits":"1",},
{"lineNum":"  329","line":"        } });"},
{"lineNum":"  330","line":"        return error.CompileError;","class":"lineCov","hits":"3","order":"2323","possible_hits":"3",},
{"lineNum":"  331","line":"    }"},
{"lineNum":"  332","line":"}"},
]};
var percent_low = 25;var percent_high = 75;
var header = { "command" : "orng-test", "date" : "2025-11-10 15:43:08", "instrumented" : 137, "covered" : 121,};
var merged_data = [];
