var data = {lines:[
{"lineNum":"    1","line":"const std = @import(\"std\");"},
{"lineNum":"    2","line":"const AST = @import(\"../ast/ast.zig\").AST;"},
{"lineNum":"    3","line":"const CFG = @import(\"../ir/cfg.zig\");"},
{"lineNum":"    4","line":"const prelude_ = @import(\"../hierarchy/prelude.zig\");"},
{"lineNum":"    5","line":"const Type_AST = @import(\"../types/type.zig\").Type_AST;"},
{"lineNum":"    6","line":"const Symbol = @import(\"../symbol/symbol.zig\");"},
{"lineNum":"    7","line":"const Canonical_Type_Fmt = @import(\"../types/canonical_type_fmt.zig\");"},
{"lineNum":"    8","line":""},
{"lineNum":"    9","line":"pub const CodeGen_Error = error{ OutOfMemory, WriteFailed };"},
{"lineNum":"   10","line":""},
{"lineNum":"   11","line":"const Self: type = @This();"},
{"lineNum":"   12","line":""},
{"lineNum":"   13","line":"writer: *std.array_list.Managed(u8),"},
{"lineNum":"   14","line":""},
{"lineNum":"   15","line":"pub fn init(writer: *std.array_list.Managed(u8)) Self {","class":"lineNoCov","hits":"0","possible_hits":"2",},
{"lineNum":"   16","line":"    return Self{","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"   17","line":"        .writer = writer,"},
{"lineNum":"   18","line":"    };"},
{"lineNum":"   19","line":"}"},
{"lineNum":"   20","line":""},
{"lineNum":"   21","line":"/// Outputs the C type which corresponds to an AST type."},
{"lineNum":"   22","line":"pub fn output_type(self: *Self, old_type: *Type_AST) CodeGen_Error!void {","class":"lineNoCov","hits":"0","possible_hits":"2",},
{"lineNum":"   23","line":"    if (old_type.unexpand_type() != old_type) {","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"   24","line":"        return try self.output_type(old_type.unexpand_type());","class":"lineNoCov","hits":"0","possible_hits":"2",},
{"lineNum":"   25","line":"    }"},
{"lineNum":"   26","line":"    if (old_type.* == .identifier and old_type.symbol() != null and old_type.symbol().?.storage == .@\"extern\") {","class":"lineNoCov","hits":"0","possible_hits":"2",},
{"lineNum":"   27","line":"        try self.writer.print(\"{s}\", .{old_type.symbol().?.storage.@\"extern\".c_name.?.string.data});","class":"lineNoCov","hits":"0","possible_hits":"2",},
{"lineNum":"   28","line":"        return;","class":"lineNoCov","hits":"0","possible_hits":"2",},
{"lineNum":"   29","line":"    }"},
{"lineNum":"   30","line":"    var _type = old_type.expand_identifier();","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"   31","line":""},
{"lineNum":"   32","line":"    switch (_type.*) {","class":"lineNoCov","hits":"0","possible_hits":"3",},
{"lineNum":"   33","line":"        .identifier => if (_type.common()._expanded_type != null and _type.common()._expanded_type.? != _type) {","class":"lineNoCov","hits":"0","possible_hits":"2",},
{"lineNum":"   34","line":"            try self.output_type(_type.common()._expanded_type.?);","class":"lineNoCov","hits":"0","possible_hits":"2",},
{"lineNum":"   35","line":"        } else {"},
{"lineNum":"   36","line":"            const info = prelude_.info_from_name(_type.token().data);","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"   37","line":"            if (info != null) {","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"   38","line":"                try self.writer.print(\"{s}\", .{info.?.c_name});","class":"lineNoCov","hits":"0","possible_hits":"2",},
{"lineNum":"   39","line":"            } else {"},
{"lineNum":"   40","line":"                try self.writer.print(","class":"lineNoCov","hits":"0","possible_hits":"5",},
{"lineNum":"   41","line":"                    \"{s} /*{?f}*/\","},
{"lineNum":"   42","line":"                    .{ _type.token().data, _type.symbol().?.init_typedef() },","class":"lineNoCov","hits":"0","possible_hits":"3",},
{"lineNum":"   43","line":"                );"},
{"lineNum":"   44","line":"            }"},
{"lineNum":"   45","line":"        },"},
{"lineNum":"   46","line":"        .addr_of => {"},
{"lineNum":"   47","line":"            try self.output_type(_type.child());","class":"lineNoCov","hits":"0","possible_hits":"2",},
{"lineNum":"   48","line":"            try self.writer.print(\" *\", .{});","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"   49","line":"        },"},
{"lineNum":"   50","line":"        .anyptr_type => try self.writer.print(\"void *\", .{}),","class":"lineNoCov","hits":"0","possible_hits":"2",},
{"lineNum":"   51","line":"        .unit_type => try self.writer.print(\"void\", .{}),","class":"lineNoCov","hits":"0","possible_hits":"2",},
{"lineNum":"   52","line":"        .annotation => try self.output_type(_type.child()),","class":"lineNoCov","hits":"0","possible_hits":"2",},
{"lineNum":"   53","line":""},
{"lineNum":"   54","line":"        .function => try self.writer.print(\"{f}\", .{Canonical_Type_Fmt{ .type = _type }}),","class":"lineNoCov","hits":"0","possible_hits":"2",},
{"lineNum":"   55","line":"        .enum_type,"},
{"lineNum":"   56","line":"        .tuple_type,"},
{"lineNum":"   57","line":"        .struct_type,"},
{"lineNum":"   58","line":"        .array_of,"},
{"lineNum":"   59","line":"        .dyn_type,"},
{"lineNum":"   60","line":"        .context_type,"},
{"lineNum":"   61","line":"        => try self.writer.print(\"struct {f}\", .{Canonical_Type_Fmt{ .type = _type }}),","class":"lineNoCov","hits":"0","possible_hits":"2",},
{"lineNum":"   62","line":"        .untagged_sum_type => try self.writer.print(\"union {f}\", .{Canonical_Type_Fmt{ .type = _type }}),","class":"lineNoCov","hits":"0","possible_hits":"2",},
{"lineNum":"   63","line":"        else => std.debug.panic(\"compiler error: unimplemented output_type() for {f}\", .{_type.*}),","class":"lineNoCov","hits":"0","possible_hits":"2",},
{"lineNum":"   64","line":"    }"},
{"lineNum":"   65","line":"}"},
{"lineNum":"   66","line":""},
{"lineNum":"   67","line":"/// Applies a function to all CFGs in a list of CFGs."},
{"lineNum":"   68","line":"///"},
{"lineNum":"   69","line":"/// ### Params:"},
{"lineNum":"   70","line":"/// - `self`: The Emitter object"},
{"lineNum":"   71","line":"/// - `sub`: Reference back to the sub-emitter (ie source, header, type, etc)"},
{"lineNum":"   72","line":"/// - `cfgs`: Slice of CFGs"},
{"lineNum":"   73","line":"/// - `header_comment`: Header comment to output, if `cfgs` is non-empy"},
{"lineNum":"   74","line":"/// - `f`: Function to apply to each CFG in `cfgs`"},
{"lineNum":"   75","line":"pub fn forall_functions("},
{"lineNum":"   76","line":"    self: *Self,"},
{"lineNum":"   77","line":"    sub: anytype,"},
{"lineNum":"   78","line":"    cfgs: []const *CFG,"},
{"lineNum":"   79","line":"    header_comment: []const u8,"},
{"lineNum":"   80","line":"    comptime f: fn (@TypeOf(sub), *CFG) CodeGen_Error!void,"},
{"lineNum":"   81","line":") CodeGen_Error!void {","class":"lineNoCov","hits":"0","possible_hits":"8",},
{"lineNum":"   82","line":"    if (cfgs.len > 0) {","class":"lineNoCov","hits":"0","possible_hits":"4",},
{"lineNum":"   83","line":"        try self.writer.print(\"\\n/* {s} */\\n\", .{header_comment});","class":"lineNoCov","hits":"0","possible_hits":"12",},
{"lineNum":"   84","line":"    }"},
{"lineNum":"   85","line":""},
{"lineNum":"   86","line":"    // apply the function `f` to all CFGs in the `cfgs` list"},
{"lineNum":"   87","line":"    for (cfgs) |cfg| {","class":"lineNoCov","hits":"0","possible_hits":"12",},
{"lineNum":"   88","line":"        if (!cfg.needed_at_runtime) {","class":"lineNoCov","hits":"0","possible_hits":"4",},
{"lineNum":"   89","line":"            continue;","class":"lineNoCov","hits":"0","possible_hits":"8",},
{"lineNum":"   90","line":"        }"},
{"lineNum":"   91","line":"        if (cfg.symbol.decl.?.* == .fn_decl or cfg.symbol.decl.?.* == .method_decl) { // Don\'t output for `_comptime` decls","class":"lineNoCov","hits":"0","possible_hits":"8",},
{"lineNum":"   92","line":"            try f(sub, cfg);","class":"lineNoCov","hits":"0","possible_hits":"8",},
{"lineNum":"   93","line":"        }"},
{"lineNum":"   94","line":"    }","class":"lineNoCov","hits":"0","possible_hits":"16",},
{"lineNum":"   95","line":"}"},
{"lineNum":"   96","line":""},
{"lineNum":"   97","line":"/// Outputs the prototype of a function"},
{"lineNum":"   98","line":"pub fn output_function_prototype("},
{"lineNum":"   99","line":"    self: *Self,"},
{"lineNum":"  100","line":"    cfg: *CFG, // TODO: Accept cfg symbol"},
{"lineNum":"  101","line":") CodeGen_Error!void {","class":"lineNoCov","hits":"0","possible_hits":"2",},
{"lineNum":"  102","line":"    // Output function return type and name"},
{"lineNum":"  103","line":"    try self.output_type(cfg.symbol.expanded_type().rhs());","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"  104","line":"    try self.writer.print(\" \", .{});","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"  105","line":"    try self.output_symbol(cfg.symbol);","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"  106","line":""},
{"lineNum":"  107","line":"    // Output function parameters"},
{"lineNum":"  108","line":"    const decl = cfg.symbol.decl.?;","class":"lineNoCov","hits":"0","possible_hits":"2",},
{"lineNum":"  109","line":"    const param_symbols = decl.param_symbols();","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"  110","line":"    const context_param_symbols = decl.context_param_symbols();","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"  111","line":""},
{"lineNum":"  112","line":"    const has_params = param_symbols != null and param_symbols.?.items.len > 0;","class":"lineNoCov","hits":"0","possible_hits":"3",},
{"lineNum":"  113","line":"    const has_contexts = context_param_symbols != null and context_param_symbols.?.items.len > 0;","class":"lineNoCov","hits":"0","possible_hits":"3",},
{"lineNum":"  114","line":""},
{"lineNum":"  115","line":"    var num_non_unit_params: i64 = 0;","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"  116","line":"    try self.writer.print(\"(\", .{});","class":"lineNoCov","hits":"0","possible_hits":"2",},
{"lineNum":"  117","line":"    if (param_symbols != null) {","class":"lineNoCov","hits":"0","possible_hits":"2",},
{"lineNum":"  118","line":"        for (param_symbols.?.items, 0..) |term, i| {","class":"lineNoCov","hits":"0","possible_hits":"4",},
{"lineNum":"  119","line":"            if (!term.expanded_type().is_c_void_type()) {","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"  120","line":"                if (decl.* == .method_decl and decl.method_decl.receiver != null and i == 0) {","class":"lineNoCov","hits":"0","possible_hits":"2",},
{"lineNum":"  121","line":"                    // Print out method receiver"},
{"lineNum":"  122","line":"                    try self.writer.print(\"void *\", .{});","class":"lineNoCov","hits":"0","possible_hits":"2",},
{"lineNum":"  123","line":"                    try self.output_symbol(term);","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"  124","line":"                } else {"},
{"lineNum":"  125","line":"                    // Print out parameter declarations"},
{"lineNum":"  126","line":"                    try self.output_var_decl(term, true);","class":"lineNoCov","hits":"0","possible_hits":"2",},
{"lineNum":"  127","line":"                }"},
{"lineNum":"  128","line":"                if (i + 1 < param_symbols.?.items.len and !param_symbols.?.items[i + 1].expanded_type().is_c_void_type()) {","class":"lineNoCov","hits":"0","possible_hits":"2",},
{"lineNum":"  129","line":"                    try self.writer.print(\", \", .{});","class":"lineNoCov","hits":"0","possible_hits":"2",},
{"lineNum":"  130","line":"                }"},
{"lineNum":"  131","line":"                num_non_unit_params += 1;","class":"lineNoCov","hits":"0","possible_hits":"3",},
{"lineNum":"  132","line":"            }"},
{"lineNum":"  133","line":"        }","class":"lineNoCov","hits":"0","possible_hits":"5",},
{"lineNum":"  134","line":"    }"},
{"lineNum":"  135","line":"    if (context_param_symbols != null) {","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"  136","line":"        if (has_contexts and has_params) {","class":"lineNoCov","hits":"0","possible_hits":"2",},
{"lineNum":"  137","line":"            try self.writer.print(\", \", .{});","class":"lineNoCov","hits":"0","possible_hits":"3",},
{"lineNum":"  138","line":"        }"},
{"lineNum":"  139","line":"        for (context_param_symbols.?.items, 0..) |term, i| {","class":"lineNoCov","hits":"0","possible_hits":"4",},
{"lineNum":"  140","line":"            try self.output_var_decl(term, true);","class":"lineNoCov","hits":"0","possible_hits":"2",},
{"lineNum":"  141","line":"            if (i + 1 < context_param_symbols.?.items.len and !context_param_symbols.?.items[i + 1].expanded_type().is_c_void_type()) {","class":"lineNoCov","hits":"0","possible_hits":"2",},
{"lineNum":"  142","line":"                try self.writer.print(\", \", .{});","class":"lineNoCov","hits":"0","possible_hits":"2",},
{"lineNum":"  143","line":"            }"},
{"lineNum":"  144","line":"            num_non_unit_params += 1;","class":"lineNoCov","hits":"0","possible_hits":"2",},
{"lineNum":"  145","line":"        }","class":"lineNoCov","hits":"0","possible_hits":"5",},
{"lineNum":"  146","line":"    }"},
{"lineNum":"  147","line":""},
{"lineNum":"  148","line":"    if (num_non_unit_params == 0) {","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"  149","line":"        // If there are no parameters, mark parameter list as void"},
{"lineNum":"  150","line":"        try self.writer.print(\"void\", .{});","class":"lineNoCov","hits":"0","possible_hits":"2",},
{"lineNum":"  151","line":"    }"},
{"lineNum":"  152","line":"    try self.writer.print(\")\", .{});","class":"lineNoCov","hits":"0","possible_hits":"2",},
{"lineNum":"  153","line":"}"},
{"lineNum":"  154","line":""},
{"lineNum":"  155","line":"/// Outputs a symbol\'s declaration. Parameters are not formatted with a preceding tab, nor a"},
{"lineNum":"  156","line":"/// semicolon nor newline."},
{"lineNum":"  157","line":"pub fn output_var_decl("},
{"lineNum":"  158","line":"    self: *Self,"},
{"lineNum":"  159","line":"    symbol: *Symbol,"},
{"lineNum":"  160","line":"    is_parameter: bool, // TODO: New function, that surrounds output_var_decl"},
{"lineNum":"  161","line":") CodeGen_Error!void {","class":"lineNoCov","hits":"0","possible_hits":"2",},
{"lineNum":"  162","line":"    if (!is_parameter) {","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"  163","line":"        try self.writer.print(\"    \", .{});","class":"lineNoCov","hits":"0","possible_hits":"2",},
{"lineNum":"  164","line":"    }"},
{"lineNum":"  165","line":"    try self.output_type(symbol.type());","class":"lineNoCov","hits":"0","possible_hits":"2",},
{"lineNum":"  166","line":"    try self.writer.print(\" /*{f}*/ \", .{symbol.type()});","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"  167","line":"    try self.output_symbol(symbol);","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"  168","line":"    if (!is_parameter) {","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"  169","line":"        try self.writer.print(\";\\n\", .{});","class":"lineNoCov","hits":"0","possible_hits":"3",},
{"lineNum":"  170","line":"    }"},
{"lineNum":"  171","line":"}"},
{"lineNum":"  172","line":""},
{"lineNum":"  173","line":"/// Outputs a symbol with it\'s file\'s unique identifier"},
{"lineNum":"  174","line":"pub fn output_symbol(self: *Self, symbol: *Symbol) CodeGen_Error!void {","class":"lineNoCov","hits":"0","possible_hits":"2",},
{"lineNum":"  175","line":"    if (symbol.storage == .@\"extern\") {","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"  176","line":"        try self.writer.print(\"{s}\", .{symbol.storage.@\"extern\".c_name.?.string.data});","class":"lineNoCov","hits":"0","possible_hits":"2",},
{"lineNum":"  177","line":"    } else if (symbol.decl != null and symbol.decl.?.* != .receiver and symbol.decl.?.top_level()) {","class":"lineNoCov","hits":"0","possible_hits":"2",},
{"lineNum":"  178","line":"        if (symbol.decl.?.* == .method_decl or !symbol.decl.?.top_level()) {","class":"lineNoCov","hits":"0","possible_hits":"2",},
{"lineNum":"  179","line":"            try self.writer.print(\"{s}__{s}__{}_{s}\", .{ symbol.scope.module.?.package_name, symbol.scope.module.?.name(), symbol.scope.uid, symbol.name });","class":"lineNoCov","hits":"0","possible_hits":"2",},
{"lineNum":"  180","line":"        } else {"},
{"lineNum":"  181","line":"            try self.writer.print(\"{s}__{s}__{s}\", .{ symbol.scope.module.?.package_name, symbol.scope.module.?.name(), symbol.name });","class":"lineNoCov","hits":"0","possible_hits":"3",},
{"lineNum":"  182","line":"        }"},
{"lineNum":"  183","line":"    } else {"},
{"lineNum":"  184","line":"        // The leading underscore here should be OK, C spec allows leading underscores for auto storage variables"},
{"lineNum":"  185","line":"        try self.writer.print(\"_{}_{s}\", .{ symbol.scope.uid, symbol.name });","class":"lineNoCov","hits":"0","possible_hits":"4",},
{"lineNum":"  186","line":"    }"},
{"lineNum":"  187","line":"}"},
]};
var percent_low = 25;var percent_high = 75;
var header = { "command" : "orng-test", "date" : "2025-11-10 15:43:08", "instrumented" : 85, "covered" : 0,};
var merged_data = [];
