var data = {lines:[
{"lineNum":"    1","line":"//! This file defines a generic data pipeline framework. It allows a sequence of processing steps to be applied, where"},
{"lineNum":"    2","line":"//! each step builds off the results of the previous. This design allows modular and reusable components, and simplifies"},
{"lineNum":"    3","line":"//! complex transformations."},
{"lineNum":"    4","line":"const std = @import(\"std\");"},
{"lineNum":"    5","line":""},
{"lineNum":"    6","line":"/// The main function to execute a pipeline."},
{"lineNum":"    7","line":"///"},
{"lineNum":"    8","line":"/// Takes a pipeline (anonymous struct value) of steps (values of struct types which implement the `run` method, and an"},
{"lineNum":"    9","line":"/// inital value. The function feeds the initial value to the first step, which produces an output. Then feeds that"},
{"lineNum":"   10","line":"/// output to the next step, and so on. Returns the final output, or an error if any occured."},
{"lineNum":"   11","line":"pub fn run(initial_value: anytype, pipeline: anytype) !ProcessResult(@TypeOf(pipeline), @TypeOf(initial_value), pipeline.len -| 1) {"},
{"lineNum":"   12","line":"    if (pipeline.len == 0) {"},
{"lineNum":"   13","line":"        // If the pipeline is empty, the initial value is unchanged"},
{"lineNum":"   14","line":"        return initial_value;"},
{"lineNum":"   15","line":"    } else {"},
{"lineNum":"   16","line":"        // Run the first pipeline"},
{"lineNum":"   17","line":"        return run_inner(initial_value, pipeline, 0);","class":"lineCov","hits":"1","order":"529","possible_hits":"1",},
{"lineNum":"   18","line":"    }"},
{"lineNum":"   19","line":"}"},
{"lineNum":"   20","line":""},
{"lineNum":"   21","line":"/// Recursive helper function to process the step at `step_index` in the `pipeline` struct."},
{"lineNum":"   22","line":"fn run_inner(previous_value: anytype, pipeline: anytype, comptime step_index: usize) !ProcessResult(@TypeOf(pipeline), @TypeOf(previous_value), pipeline.len -| 1) {"},
{"lineNum":"   23","line":"    // Get the step struct for this step"},
{"lineNum":"   24","line":"    const PipelineType = @TypeOf(pipeline);"},
{"lineNum":"   25","line":"    const fields = std.meta.fields(PipelineType);"},
{"lineNum":"   26","line":"    const field = fields[step_index];"},
{"lineNum":"   27","line":"    var step = @field(pipeline, field.name);","class":"lineCov","hits":"10","order":"531","possible_hits":"10",},
{"lineNum":"   28","line":"    // std.debug.print(\"step: {}\\n\", .{@TypeOf(step)});"},
{"lineNum":"   29","line":""},
{"lineNum":"   30","line":"    // Run the step on the previous value"},
{"lineNum":"   31","line":"    if (!@hasDecl(@TypeOf(step), \"run\")) {"},
{"lineNum":"   32","line":"        @compileError(std.fmt.comptimePrint(\"the step `{}` does not have a public run() method!\", .{@TypeOf(step)}));"},
{"lineNum":"   33","line":"    }"},
{"lineNum":"   34","line":"    const run_result = try step.run(previous_value);","class":"lineCov","hits":"11","order":"532","possible_hits":"11",},
{"lineNum":"   35","line":""},
{"lineNum":"   36","line":"    if (step_index + 1 == fields.len) {"},
{"lineNum":"   37","line":"        // If this is the last step, just return the run result","class":"lineCov","hits":"2","order":"528","possible_hits":"2",},
{"lineNum":"   38","line":"        return run_result;","class":"lineCov","hits":"1","order":"2049","possible_hits":"1",},
{"lineNum":"   39","line":"    } else {"},
{"lineNum":"   40","line":"        // Otherwise, pass run result to next step"},
{"lineNum":"   41","line":"        return run_inner(run_result, pipeline, step_index + 1);","class":"lineCov","hits":"10","order":"536","possible_hits":"10",},
{"lineNum":"   42","line":"    }"},
{"lineNum":"   43","line":"}"},
{"lineNum":"   44","line":""},
{"lineNum":"   45","line":"/// Helper function to get the return type of the pipeline, and each intermediate step."},
{"lineNum":"   46","line":"fn ProcessResult(comptime PipelineType: type, comptime InitialType: type, comptime i: usize) type {"},
{"lineNum":"   47","line":"    const fields = std.meta.fields(PipelineType);"},
{"lineNum":"   48","line":""},
{"lineNum":"   49","line":"    if (fields.len == 0) {"},
{"lineNum":"   50","line":"        return InitialType;"},
{"lineNum":"   51","line":"    }"},
{"lineNum":"   52","line":""},
{"lineNum":"   53","line":"    const Step_Type = fields[i].type;"},
{"lineNum":"   54","line":"    const RunFnType = @TypeOf(Step_Type.run);"},
{"lineNum":"   55","line":"    const fn_info = @typeInfo(RunFnType).@\"fn\";"},
{"lineNum":"   56","line":"    // Get the return type, extracting from error union if needed"},
{"lineNum":"   57","line":"    const return_type = fn_info.return_type.?;"},
{"lineNum":"   58","line":"    return switch (@typeInfo(return_type)) {"},
{"lineNum":"   59","line":"        .error_union => |eu| eu.payload,"},
{"lineNum":"   60","line":"        else => return_type,"},
{"lineNum":"   61","line":"    };"},
{"lineNum":"   62","line":"}"},
{"lineNum":"   63","line":""},
{"lineNum":"   64","line":"test \"test-pipeline\" {"},
{"lineNum":"   65","line":"    const Get_Length: type = struct {"},
{"lineNum":"   66","line":"        const Self: type = @This();"},
{"lineNum":"   67","line":""},
{"lineNum":"   68","line":"        pub fn init() Self {"},
{"lineNum":"   69","line":"            return .{};"},
{"lineNum":"   70","line":"        }"},
{"lineNum":"   71","line":""},
{"lineNum":"   72","line":"        pub fn run(self: *Self, str: []const u8) error{CompileError}!usize {"},
{"lineNum":"   73","line":"            _ = self;"},
{"lineNum":"   74","line":"            return str.len;"},
{"lineNum":"   75","line":"        }"},
{"lineNum":"   76","line":"    };"},
{"lineNum":"   77","line":""},
{"lineNum":"   78","line":"    const Add: type = struct {"},
{"lineNum":"   79","line":"        const Self: type = @This();"},
{"lineNum":"   80","line":"        addend: usize,"},
{"lineNum":"   81","line":""},
{"lineNum":"   82","line":"        pub fn init(addend: usize) Self {"},
{"lineNum":"   83","line":"            return .{ .addend = addend };"},
{"lineNum":"   84","line":"        }"},
{"lineNum":"   85","line":""},
{"lineNum":"   86","line":"        pub fn run(self: *Self, x: usize) error{CompileError}!usize {"},
{"lineNum":"   87","line":"            return self.addend + x;"},
{"lineNum":"   88","line":"        }"},
{"lineNum":"   89","line":"    };"},
{"lineNum":"   90","line":""},
{"lineNum":"   91","line":"    const res = try run(\"Hello, World!\", .{ Get_Length.init(), Add.init(4) });"},
{"lineNum":"   92","line":""},
{"lineNum":"   93","line":"    try std.testing.expectEqual(res, 17);"},
{"lineNum":"   94","line":"}"},
{"lineNum":"   95","line":""},
{"lineNum":"   96","line":"test \"empty-pipeline\" {"},
{"lineNum":"   97","line":"    const res = try run(435, .{});"},
{"lineNum":"   98","line":"    try std.testing.expectEqual(res, 435);"},
{"lineNum":"   99","line":"}"},
]};
var percent_low = 25;var percent_high = 75;
var header = { "command" : "orng-test", "date" : "2025-11-10 15:43:08", "instrumented" : 6, "covered" : 6,};
var merged_data = [];
