var data = {lines:[
{"lineNum":"    1","line":"//! This file contains the semantic validation logic for scopes."},
{"lineNum":"    2","line":""},
{"lineNum":"    3","line":"const std = @import(\"std\");"},
{"lineNum":"    4","line":"const ast_ = @import(\"../ast/ast.zig\");"},
{"lineNum":"    5","line":"const Compiler_Context = @import(\"../hierarchy/compiler.zig\");"},
{"lineNum":"    6","line":"const errs_ = @import(\"../util/errors.zig\");"},
{"lineNum":"    7","line":"const Scope = @import(\"../symbol/scope.zig\");"},
{"lineNum":"    8","line":"const Symbol = @import(\"../symbol/symbol.zig\");"},
{"lineNum":"    9","line":"const Type_AST = @import(\"../types/type.zig\").Type_AST;"},
{"lineNum":"   10","line":""},
{"lineNum":"   11","line":"const Validate_Error_Enum = error{ OutOfMemory, CompileError };"},
{"lineNum":"   12","line":""},
{"lineNum":"   13","line":"const Self: type = @This();"},
{"lineNum":"   14","line":""},
{"lineNum":"   15","line":"ctx: *Compiler_Context,"},
{"lineNum":"   16","line":""},
{"lineNum":"   17","line":"pub fn init(ctx: *Compiler_Context) Self {","class":"lineCov","hits":"2","order":"101","possible_hits":"2",},
{"lineNum":"   18","line":"    return Self{ .ctx = ctx };","class":"lineCov","hits":"1","order":"102","possible_hits":"1",},
{"lineNum":"   19","line":"}"},
{"lineNum":"   20","line":""},
{"lineNum":"   21","line":"pub fn validate_scope(self: *Self, scope: *Scope) Validate_Error_Enum!void {","class":"lineCov","hits":"2","order":"2060","possible_hits":"2",},
{"lineNum":"   22","line":"    for (scope.symbols.keys()) |key| {","class":"lineCov","hits":"3","order":"2061","possible_hits":"3",},
{"lineNum":"   23","line":"        const symbol = scope.symbols.get(key).?;","class":"lineCov","hits":"3","order":"2062","possible_hits":"3",},
{"lineNum":"   24","line":""},
{"lineNum":"   25","line":"        try self.ctx.validate_symbol.validate_symbol(symbol);","class":"lineCov","hits":"2","order":"2063","possible_hits":"2",},
{"lineNum":"   26","line":"    }","class":"lineCov","hits":"3","order":"2221","possible_hits":"3",},
{"lineNum":"   27","line":"    var i: usize = 0;","class":"lineCov","hits":"1","order":"2265","possible_hits":"1",},
{"lineNum":"   28","line":"    while (i < scope.children.items.len) : (i += 1) {","class":"linePartCov","hits":"4","order":"2266","possible_hits":"5",},
{"lineNum":"   29","line":"        const child = scope.children.items[i];","class":"lineCov","hits":"3","order":"2267","possible_hits":"3",},
{"lineNum":"   30","line":"        try self.validate_scope(child);","class":"lineCov","hits":"2","order":"2268","possible_hits":"2",},
{"lineNum":"   31","line":"    }","class":"lineCov","hits":"1","order":"2271","possible_hits":"1",},
{"lineNum":"   32","line":"    for (scope.impls.items) |impl| {","class":"lineCov","hits":"3","order":"2269","possible_hits":"3",},
{"lineNum":"   33","line":"        try self.validate_impl(impl);","class":"lineCov","hits":"2","order":"3442","possible_hits":"2",},
{"lineNum":"   34","line":"    }","class":"lineCov","hits":"4","order":"2270","possible_hits":"4",},
{"lineNum":"   35","line":"}"},
{"lineNum":"   36","line":""},
{"lineNum":"   37","line":"// TODO: Split up into smaller functions"},
{"lineNum":"   38","line":"fn validate_impl(self: *Self, impl: *ast_.AST) Validate_Error_Enum!void {","class":"lineCov","hits":"2","order":"3443","possible_hits":"2",},
{"lineNum":"   39","line":"    if (impl.impl._type.* == .addr_of) {","class":"lineCov","hits":"2","order":"3444","possible_hits":"2",},
{"lineNum":"   40","line":"        self.ctx.errors.add_error(errs_.Error{ .basic = .{","class":"lineCov","hits":"2","order":"6414","possible_hits":"2",},
{"lineNum":"   41","line":"            .span = impl.impl._type.token().span,","class":"lineCov","hits":"3","order":"6415","possible_hits":"3",},
{"lineNum":"   42","line":"            .msg = \"cannot implement method for address types\","},
{"lineNum":"   43","line":"        } });"},
{"lineNum":"   44","line":"        return error.CompileError;","class":"lineCov","hits":"2","order":"3445","possible_hits":"2",},
{"lineNum":"   45","line":"    }"},
{"lineNum":"   46","line":""},
{"lineNum":"   47","line":"    _ = self.ctx.typecheck.typecheck_AST(impl.impl.trait.?, null) catch |e| switch (e) {","class":"lineCov","hits":"3","order":"3446","possible_hits":"3",},
{"lineNum":"   48","line":"        error.UnexpectedTypeType => {"},
{"lineNum":"   49","line":"            self.ctx.errors.add_error(errs_.Error{ .basic = .{","class":"lineCov","hits":"2","order":"6417","possible_hits":"2",},
{"lineNum":"   50","line":"                .span = impl.impl.trait.?.token().span,","class":"lineCov","hits":"3","order":"6418","possible_hits":"3",},
{"lineNum":"   51","line":"                .msg = \"cannot implement for this, not a trait\","},
{"lineNum":"   52","line":"            } });"},
{"lineNum":"   53","line":"            return error.CompileError;","class":"lineCov","hits":"1","order":"6419","possible_hits":"1",},
{"lineNum":"   54","line":"        },"},
{"lineNum":"   55","line":"        else => return error.CompileError,","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"   56","line":"    };"},
{"lineNum":"   57","line":"    try self.ctx.validate_type.validate_type(impl.impl._type);","class":"lineCov","hits":"2","order":"3447","possible_hits":"2",},
{"lineNum":"   58","line":""},
{"lineNum":"   59","line":"    const trait_symbol: *Symbol = impl.impl.trait.?.symbol().?;","class":"lineCov","hits":"2","order":"3448","possible_hits":"2",},
{"lineNum":"   60","line":"    if (trait_symbol.kind != .trait) {","class":"lineCov","hits":"1","order":"3449","possible_hits":"1",},
{"lineNum":"   61","line":"        self.ctx.errors.add_error(errs_.Error{ .basic = .{","class":"lineNoCov","hits":"0","possible_hits":"2",},
{"lineNum":"   62","line":"            .span = trait_symbol.span(),","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"   63","line":"            .msg = \"cannot implement for this, not a trait\","},
{"lineNum":"   64","line":"        } });"},
{"lineNum":"   65","line":"        return error.CompileError;","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"   66","line":"    }"},
{"lineNum":"   67","line":"    const trait_ast = trait_symbol.decl.?;","class":"lineCov","hits":"3","order":"3450","possible_hits":"3",},
{"lineNum":"   68","line":""},
{"lineNum":"   69","line":"    // Check that the (trait, type) pair is unique for this scope"},
{"lineNum":"   70","line":"    const lookup_res = impl.scope().?.impl_trait_lookup(impl.impl._type, trait_symbol);","class":"lineCov","hits":"3","order":"3451","possible_hits":"3",},
{"lineNum":"   71","line":"    if (lookup_res.count > 1) {","class":"lineCov","hits":"1","order":"3472","possible_hits":"1",},
{"lineNum":"   72","line":"        // Check if there\'s already an implementation for the same trait and type"},
{"lineNum":"   73","line":"        self.ctx.errors.add_error(errs_.Error{ .reimpl = .{","class":"lineCov","hits":"2","order":"6556","possible_hits":"2",},
{"lineNum":"   74","line":"            .first_defined_span = lookup_res.ast.?.token().span,","class":"lineCov","hits":"3","order":"6557","possible_hits":"3",},
{"lineNum":"   75","line":"            .redefined_span = impl.token().span,","class":"lineCov","hits":"1","order":"6558","possible_hits":"1",},
{"lineNum":"   76","line":"            .name = if (!impl.impl.impls_anon_trait) trait_symbol.name else null,","class":"lineCov","hits":"2","order":"6559","possible_hits":"2",},
{"lineNum":"   77","line":"            ._type = impl.impl._type,","class":"lineCov","hits":"3","order":"6560","possible_hits":"3",},
{"lineNum":"   78","line":"        } });"},
{"lineNum":"   79","line":"        return error.CompileError;","class":"lineCov","hits":"2","order":"3473","possible_hits":"2",},
{"lineNum":"   80","line":"    }"},
{"lineNum":"   81","line":""},
{"lineNum":"   82","line":"    // Construct a map of all trait decls"},
{"lineNum":"   83","line":"    var trait_decls = std.StringArrayHashMap(*ast_.AST).init(self.ctx.allocator()); // Map name -> Method Decl","class":"lineCov","hits":"1","order":"3474","possible_hits":"1",},
{"lineNum":"   84","line":"    defer trait_decls.deinit();","class":"linePartCov","hits":"8","order":"3526","possible_hits":"9",},
{"lineNum":"   85","line":"    for (trait_ast.trait.method_decls.items) |decl| {","class":"lineCov","hits":"4","order":"3475","possible_hits":"4",},
{"lineNum":"   86","line":"        trait_decls.put(decl.method_decl.name.token().data, decl) catch unreachable;","class":"lineCov","hits":"2","order":"3476","possible_hits":"2",},
{"lineNum":"   87","line":"    }","class":"lineCov","hits":"4","order":"3477","possible_hits":"4",},
{"lineNum":"   88","line":""},
{"lineNum":"   89","line":"    // Subtract trait defs - impl decls"},
{"lineNum":"   90","line":"    for (impl.impl.method_defs.items) |def| {","class":"lineCov","hits":"4","order":"3478","possible_hits":"4",},
{"lineNum":"   91","line":"        const def_key = def.method_decl.name.token().data;","class":"lineCov","hits":"3","order":"3479","possible_hits":"3",},
{"lineNum":"   92","line":"        const trait_decl = trait_decls.get(def_key);","class":"lineCov","hits":"1","order":"3480","possible_hits":"1",},
{"lineNum":"   93","line":""},
{"lineNum":"   94","line":"        // Check that the trait defines the method"},
{"lineNum":"   95","line":"        if (trait_decl == null) {","class":"lineCov","hits":"1","order":"3481","possible_hits":"1",},
{"lineNum":"   96","line":"            self.ctx.errors.add_error(errs_.Error{ .method_not_in_trait = .{","class":"lineCov","hits":"2","order":"6468","possible_hits":"2",},
{"lineNum":"   97","line":"                .method_span = def.token().span,","class":"lineCov","hits":"1","order":"6469","possible_hits":"1",},
{"lineNum":"   98","line":"                .method_name = def.method_decl.name.token().data,","class":"lineCov","hits":"3","order":"6470","possible_hits":"3",},
{"lineNum":"   99","line":"                .trait_name = trait_ast.token().data,","class":"lineCov","hits":"1","order":"6471","possible_hits":"1",},
{"lineNum":"  100","line":"            } });"},
{"lineNum":"  101","line":"            return error.CompileError;","class":"lineCov","hits":"2","order":"3482","possible_hits":"2",},
{"lineNum":"  102","line":"        }"},
{"lineNum":"  103","line":""},
{"lineNum":"  104","line":"        // Check that receivers match"},
{"lineNum":"  105","line":"        if (!receivers_match(def.method_decl.receiver, trait_decl.?.method_decl.receiver)) {","class":"lineCov","hits":"2","order":"3483","possible_hits":"2",},
{"lineNum":"  106","line":"            self.ctx.errors.add_error(errs_.Error{ .impl_receiver_mismatch = .{","class":"lineCov","hits":"2","order":"6510","possible_hits":"2",},
{"lineNum":"  107","line":"                .receiver_span = if (def.method_decl.receiver != null) def.method_decl.receiver.?.token().span else def.token().span,","class":"lineCov","hits":"2","order":"6511","possible_hits":"2",},
{"lineNum":"  108","line":"                .method_name = def.method_decl.name.token().data,","class":"lineCov","hits":"3","order":"6512","possible_hits":"3",},
{"lineNum":"  109","line":"                .trait_name = trait_ast.token().data,","class":"lineCov","hits":"1","order":"6513","possible_hits":"1",},
{"lineNum":"  110","line":"                .trait_receiver = if (trait_decl.?.method_decl.receiver != null) trait_decl.?.method_decl.receiver.?.receiver.kind else null,","class":"lineCov","hits":"2","order":"6514","possible_hits":"2",},
{"lineNum":"  111","line":"                .impl_receiver = if (def.method_decl.receiver != null) def.method_decl.receiver.?.receiver.kind else null,","class":"lineCov","hits":"3","order":"6515","possible_hits":"3",},
{"lineNum":"  112","line":"            } });"},
{"lineNum":"  113","line":"            return error.CompileError;","class":"lineCov","hits":"2","order":"3489","possible_hits":"2",},
{"lineNum":"  114","line":"        }"},
{"lineNum":"  115","line":""},
{"lineNum":"  116","line":"        // Check that paramter arity matches"},
{"lineNum":"  117","line":"        if (def.children().items.len != trait_decl.?.children().items.len) {","class":"lineCov","hits":"2","order":"3490","possible_hits":"2",},
{"lineNum":"  118","line":"            self.ctx.errors.add_error(errs_.Error{ .mismatch_method_param_arity = .{","class":"lineCov","hits":"2","order":"6486","possible_hits":"2",},
{"lineNum":"  119","line":"                .span = def.token().span,","class":"lineCov","hits":"1","order":"6487","possible_hits":"1",},
{"lineNum":"  120","line":"                .method_name = def.method_decl.name.token().data,","class":"lineCov","hits":"3","order":"6488","possible_hits":"3",},
{"lineNum":"  121","line":"                .trait_name = trait_ast.token().data,","class":"lineCov","hits":"1","order":"6489","possible_hits":"1",},
{"lineNum":"  122","line":"                .trait_arity = trait_decl.?.children().items.len + @intFromBool(trait_decl.?.method_decl.receiver != null),","class":"lineCov","hits":"2","order":"6490","possible_hits":"2",},
{"lineNum":"  123","line":"                .impl_arity = def.children().items.len + @intFromBool(def.method_decl.receiver != null),","class":"lineCov","hits":"1","order":"6491","possible_hits":"1",},
{"lineNum":"  124","line":"            } });"},
{"lineNum":"  125","line":"            return error.CompileError;","class":"lineCov","hits":"2","order":"3491","possible_hits":"2",},
{"lineNum":"  126","line":"        }"},
{"lineNum":"  127","line":""},
{"lineNum":"  128","line":"        // Check that parameters match"},
{"lineNum":"  129","line":"        var subst = std.StringArrayHashMap(*Type_AST).init(self.ctx.allocator());","class":"lineCov","hits":"1","order":"3492","possible_hits":"1",},
{"lineNum":"  130","line":"        defer subst.deinit();","class":"lineCov","hits":"4","order":"3510","possible_hits":"4",},
{"lineNum":"  131","line":"        subst.put(\"Self\", impl.impl._type) catch unreachable;","class":"lineCov","hits":"3","order":"3493","possible_hits":"3",},
{"lineNum":"  132","line":""},
{"lineNum":"  133","line":"        for (def.children().items, trait_decl.?.children().items) |impl_param, trait_param| {","class":"lineCov","hits":"4","order":"3494","possible_hits":"4",},
{"lineNum":"  134","line":"            const impl_type = impl_param.binding.type;","class":"lineCov","hits":"3","order":"3495","possible_hits":"3",},
{"lineNum":"  135","line":"            const trait_type = Type_AST.clone(trait_param.binding.type, &subst, self.ctx.allocator());","class":"lineCov","hits":"3","order":"3496","possible_hits":"3",},
{"lineNum":"  136","line":"            if (!impl_type.types_match(trait_type)) {","class":"lineCov","hits":"1","order":"3497","possible_hits":"1",},
{"lineNum":"  137","line":"                self.ctx.errors.add_error(errs_.Error{ .mismatch_method_type = .{","class":"lineCov","hits":"2","order":"6500","possible_hits":"2",},
{"lineNum":"  138","line":"                    .span = impl_param.binding.type.token().span,","class":"lineCov","hits":"3","order":"6501","possible_hits":"3",},
{"lineNum":"  139","line":"                    .method_name = def.method_decl.name.token().data,","class":"lineCov","hits":"3","order":"6502","possible_hits":"3",},
{"lineNum":"  140","line":"                    .trait_name = trait_ast.token().data,","class":"lineCov","hits":"1","order":"6503","possible_hits":"1",},
{"lineNum":"  141","line":"                    .trait_type = trait_type,"},
{"lineNum":"  142","line":"                    .impl_type = impl_type,"},
{"lineNum":"  143","line":"                } });"},
{"lineNum":"  144","line":"                return error.CompileError;","class":"lineCov","hits":"2","order":"3498","possible_hits":"2",},
{"lineNum":"  145","line":"            }"},
{"lineNum":"  146","line":"        }","class":"lineCov","hits":"3","order":"3499","possible_hits":"3",},
{"lineNum":"  147","line":""},
{"lineNum":"  148","line":"        // Check that return type matches"},
{"lineNum":"  149","line":"        const trait_method_ret_type = Type_AST.clone(trait_decl.?.method_decl.ret_type, &subst, self.ctx.allocator());","class":"lineCov","hits":"3","order":"3500","possible_hits":"3",},
{"lineNum":"  150","line":"        const def_method_ret_type = Type_AST.clone(def.method_decl.ret_type, &subst, self.ctx.allocator());","class":"lineCov","hits":"3","order":"3501","possible_hits":"3",},
{"lineNum":"  151","line":"        if (!def_method_ret_type.types_match(trait_method_ret_type)) {","class":"lineCov","hits":"1","order":"3502","possible_hits":"1",},
{"lineNum":"  152","line":"            self.ctx.errors.add_error(errs_.Error{ .mismatch_method_type = .{","class":"lineCov","hits":"2","order":"6538","possible_hits":"2",},
{"lineNum":"  153","line":"                .span = def.method_decl.ret_type.token().span,","class":"lineCov","hits":"3","order":"6539","possible_hits":"3",},
{"lineNum":"  154","line":"                .method_name = def.method_decl.name.token().data,","class":"lineCov","hits":"3","order":"6540","possible_hits":"3",},
{"lineNum":"  155","line":"                .trait_name = trait_ast.token().data,","class":"lineCov","hits":"1","order":"6541","possible_hits":"1",},
{"lineNum":"  156","line":"                .trait_type = trait_method_ret_type,"},
{"lineNum":"  157","line":"                .impl_type = def.method_decl.ret_type,","class":"lineCov","hits":"3","order":"6542","possible_hits":"3",},
{"lineNum":"  158","line":"            } });"},
{"lineNum":"  159","line":"            return error.CompileError;","class":"lineCov","hits":"2","order":"3503","possible_hits":"2",},
{"lineNum":"  160","line":"        }"},
{"lineNum":"  161","line":""},
{"lineNum":"  162","line":"        // Copy over the c_type from trait method decl"},
{"lineNum":"  163","line":"        def.method_decl.c_type = trait_decl.?.method_decl.c_type;","class":"lineCov","hits":"3","order":"3504","possible_hits":"3",},
{"lineNum":"  164","line":""},
{"lineNum":"  165","line":"        // Verify that impl virtuality matches trait virtuality"},
{"lineNum":"  166","line":"        if (def.method_decl.is_virtual != trait_decl.?.method_decl.is_virtual) {","class":"lineCov","hits":"2","order":"3505","possible_hits":"2",},
{"lineNum":"  167","line":"            self.ctx.errors.add_error(errs_.Error{ .mismatch_method_virtuality = .{","class":"lineCov","hits":"2","order":"6543","possible_hits":"2",},
{"lineNum":"  168","line":"                .span = def.token().span,","class":"lineCov","hits":"1","order":"6544","possible_hits":"1",},
{"lineNum":"  169","line":"                .method_name = def.method_decl.name.token().data,","class":"lineCov","hits":"3","order":"6545","possible_hits":"3",},
{"lineNum":"  170","line":"                .trait_name = trait_ast.token().data,","class":"lineCov","hits":"1","order":"6546","possible_hits":"1",},
{"lineNum":"  171","line":"                .trait_method_is_virtual = trait_decl.?.method_decl.is_virtual,","class":"lineCov","hits":"3","order":"6547","possible_hits":"3",},
{"lineNum":"  172","line":"                .impl_method_is_virtual = def.method_decl.is_virtual,","class":"lineCov","hits":"3","order":"6548","possible_hits":"3",},
{"lineNum":"  173","line":"            } });"},
{"lineNum":"  174","line":"            return error.CompileError;","class":"lineCov","hits":"2","order":"3506","possible_hits":"2",},
{"lineNum":"  175","line":"        }"},
{"lineNum":"  176","line":""},
{"lineNum":"  177","line":"        if (def.method_decl.is_virtual) {","class":"lineCov","hits":"2","order":"3507","possible_hits":"2",},
{"lineNum":"  178","line":"            impl.impl.num_virtual_methods += 1;","class":"linePartCov","hits":"1","order":"3508","possible_hits":"2",},
{"lineNum":"  179","line":"        }"},
{"lineNum":"  180","line":""},
{"lineNum":"  181","line":"        // Subtract the method from the set"},
{"lineNum":"  182","line":"        _ = trait_decls.swapRemove(def_key);","class":"lineCov","hits":"1","order":"3509","possible_hits":"1",},
{"lineNum":"  183","line":"    }","class":"lineCov","hits":"3","order":"3511","possible_hits":"3",},
{"lineNum":"  184","line":""},
{"lineNum":"  185","line":"    var errant = false;","class":"lineCov","hits":"1","order":"3513","possible_hits":"1",},
{"lineNum":"  186","line":"    for (trait_decls.keys()) |trait_key| {","class":"lineCov","hits":"3","order":"3514","possible_hits":"3",},
{"lineNum":"  187","line":"        const trait_decl = trait_decls.get(trait_key).?;","class":"lineCov","hits":"3","order":"6449","possible_hits":"3",},
{"lineNum":"  188","line":"        self.ctx.errors.add_error(errs_.Error{ .method_not_in_impl = .{","class":"lineCov","hits":"2","order":"6450","possible_hits":"2",},
{"lineNum":"  189","line":"            .impl_span = impl.token().span,","class":"lineCov","hits":"1","order":"6451","possible_hits":"1",},
{"lineNum":"  190","line":"            .method_span = trait_decl.token().span,","class":"lineCov","hits":"1","order":"6452","possible_hits":"1",},
{"lineNum":"  191","line":"            .method_name = trait_decl.method_decl.name.token().data,","class":"lineCov","hits":"3","order":"6453","possible_hits":"3",},
{"lineNum":"  192","line":"            .trait_name = trait_ast.token().data,","class":"lineCov","hits":"1","order":"6454","possible_hits":"1",},
{"lineNum":"  193","line":"        } });"},
{"lineNum":"  194","line":"        errant = true;","class":"lineCov","hits":"1","order":"6455","possible_hits":"1",},
{"lineNum":"  195","line":"    }","class":"lineCov","hits":"3","order":"3515","possible_hits":"3",},
{"lineNum":"  196","line":"    if (errant) {","class":"lineCov","hits":"1","order":"3516","possible_hits":"1",},
{"lineNum":"  197","line":"        return error.CompileError;","class":"lineCov","hits":"2","order":"3517","possible_hits":"2",},
{"lineNum":"  198","line":"    }"},
{"lineNum":"  199","line":""},
{"lineNum":"  200","line":"    for (impl.impl.method_defs.items) |def| {","class":"lineCov","hits":"4","order":"3518","possible_hits":"4",},
{"lineNum":"  201","line":"        _ = self.ctx.typecheck.typecheck_AST(def, null) catch return error.CompileError;","class":"linePartCov","hits":"2","order":"3519","possible_hits":"3",},
{"lineNum":"  202","line":"    }","class":"lineCov","hits":"3","order":"3525","possible_hits":"3",},
{"lineNum":"  203","line":"}"},
{"lineNum":"  204","line":""},
{"lineNum":"  205","line":"fn receivers_match(a: ?*ast_.AST, b: ?*ast_.AST) bool {","class":"lineCov","hits":"2","order":"3484","possible_hits":"2",},
{"lineNum":"  206","line":"    if (a == null and b != null) {","class":"lineCov","hits":"1","order":"3485","possible_hits":"1",},
{"lineNum":"  207","line":"        return false;","class":"lineCov","hits":"1","order":"6532","possible_hits":"1",},
{"lineNum":"  208","line":"    } else if (a != null and b == null) {","class":"lineCov","hits":"1","order":"3486","possible_hits":"1",},
{"lineNum":"  209","line":"        return false;","class":"lineCov","hits":"1","order":"6525","possible_hits":"1",},
{"lineNum":"  210","line":"    } else if (a == null and b == null) {","class":"lineCov","hits":"1","order":"3487","possible_hits":"1",},
{"lineNum":"  211","line":"        return true;","class":"lineCov","hits":"1","order":"3488","possible_hits":"1",},
{"lineNum":"  212","line":"    } else {"},
{"lineNum":"  213","line":"        return a.?.receiver.kind == b.?.receiver.kind;","class":"lineCov","hits":"1","order":"3512","possible_hits":"1",},
{"lineNum":"  214","line":"    }"},
{"lineNum":"  215","line":"}"},
]};
var percent_low = 25;var percent_high = 75;
var header = { "command" : "orng-test", "date" : "2025-11-10 15:43:08", "instrumented" : 128, "covered" : 124,};
var merged_data = [];
