var data = {lines:[
{"lineNum":"    1","line":"const std = @import(\"std\");"},
{"lineNum":"    2","line":"const errs_ = @import(\"../util/errors.zig\");"},
{"lineNum":"    3","line":"const Span = @import(\"../util/span.zig\");"},
{"lineNum":"    4","line":""},
{"lineNum":"    5","line":"const Self: type = @This();"},
{"lineNum":"    6","line":"lines: std.array_list.Managed([]const u8),"},
{"lineNum":"    7","line":"errors: *errs_.Errors,"},
{"lineNum":"    8","line":""},
{"lineNum":"    9","line":"pub fn init(errors: *errs_.Errors, allocator: std.mem.Allocator) Self {","class":"lineCov","hits":"2","order":"489","possible_hits":"2",},
{"lineNum":"   10","line":"    return Self{","class":"lineCov","hits":"1","order":"491","possible_hits":"1",},
{"lineNum":"   11","line":"        .lines = std.array_list.Managed([]const u8).init(allocator),","class":"lineCov","hits":"1","order":"490","possible_hits":"1",},
{"lineNum":"   12","line":"        .errors = errors,"},
{"lineNum":"   13","line":"    };"},
{"lineNum":"   14","line":"}"},
{"lineNum":"   15","line":""},
{"lineNum":"   16","line":"// Has to be done separately from the lexer, because the lexer might throw errors, which would need to be printed out"},
{"lineNum":"   17","line":"// However, we couldn\'t print out the line for the error if we did tokens and lines at the same time"},
{"lineNum":"   18","line":"// It\'s desirable to print the line, therefore lines must be done before tokens"},
{"lineNum":"   19","line":"pub fn run(self: *Self, contents: []const u8) error{LexerError}!std.array_list.Managed([]const u8) {","class":"lineCov","hits":"2","order":"537","possible_hits":"2",},
{"lineNum":"   20","line":"    var start: usize = 0;","class":"lineCov","hits":"1","order":"538","possible_hits":"1",},
{"lineNum":"   21","line":"    if (contents.len == 0) {","class":"lineCov","hits":"1","order":"539","possible_hits":"1",},
{"lineNum":"   22","line":"        self.errors.add_error(errs_.Error{ .basic = .{","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"   23","line":"            .span = Span.phony,"},
{"lineNum":"   24","line":"            .msg = \"file is empty\","},
{"lineNum":"   25","line":"        } });"},
{"lineNum":"   26","line":"        return error.LexerError;","class":"linePartCov","hits":"1","order":"540","possible_hits":"2",},
{"lineNum":"   27","line":"    }"},
{"lineNum":"   28","line":"    for (1..contents.len) |end| {","class":"linePartCov","hits":"3","order":"541","possible_hits":"5",},
{"lineNum":"   29","line":"        if (contents[end] == \'\\n\') {","class":"lineCov","hits":"2","order":"542","possible_hits":"2",},
{"lineNum":"   30","line":"            self.lines.append(contents[start..end]) catch unreachable;","class":"lineCov","hits":"2","order":"545","possible_hits":"2",},
{"lineNum":"   31","line":"            start = end + 1;","class":"linePartCov","hits":"2","order":"543","possible_hits":"3",},
{"lineNum":"   32","line":"        }"},
{"lineNum":"   33","line":"    }","class":"lineCov","hits":"3","order":"544","possible_hits":"3",},
{"lineNum":"   34","line":"    self.lines.append(contents[start..contents.len]) catch unreachable;","class":"lineCov","hits":"2","order":"546","possible_hits":"2",},
{"lineNum":"   35","line":"    return self.lines;","class":"lineCov","hits":"1","order":"547","possible_hits":"1",},
{"lineNum":"   36","line":"}"},
]};
var percent_low = 25;var percent_high = 75;
var header = { "command" : "orng-test", "date" : "2025-11-10 15:43:08", "instrumented" : 15, "covered" : 14,};
var merged_data = [];
