var data = {lines:[
{"lineNum":"    1","line":"//! This file defines a generic way to walk over ASTs, applying a walk context to each node."},
{"lineNum":"    2","line":""},
{"lineNum":"    3","line":"const std = @import(\"std\");"},
{"lineNum":"    4","line":"const ast_ = @import(\"../ast/ast.zig\");"},
{"lineNum":"    5","line":"const Type_AST = @import(\"../types/type.zig\").Type_AST;"},
{"lineNum":"    6","line":""},
{"lineNum":"    7","line":"pub const Error = error{ OutOfMemory, CompileError };"},
{"lineNum":"    8","line":""},
{"lineNum":"    9","line":"pub fn Apply_Ast_Walk(Context_Type: type) type {"},
{"lineNum":"   10","line":"    return struct {"},
{"lineNum":"   11","line":"        const Self: type = @This();"},
{"lineNum":"   12","line":"        context: Context_Type,"},
{"lineNum":"   13","line":""},
{"lineNum":"   14","line":"        pub fn init(context: Context_Type) Self {","class":"lineCov","hits":"4","order":"506","possible_hits":"4",},
{"lineNum":"   15","line":"            return Self{ .context = context };","class":"lineCov","hits":"4","order":"507","possible_hits":"4",},
{"lineNum":"   16","line":"        }"},
{"lineNum":"   17","line":""},
{"lineNum":"   18","line":"        pub fn run(self: *Self, asts: *std.array_list.Managed(*ast_.AST)) Error!*std.array_list.Managed(*ast_.AST) {","class":"lineCov","hits":"8","order":"1398","possible_hits":"8",},
{"lineNum":"   19","line":"            try walk_asts(asts, self.context);","class":"lineCov","hits":"4","order":"1399","possible_hits":"4",},
{"lineNum":"   20","line":"            return asts;","class":"lineCov","hits":"4","order":"1519","possible_hits":"4",},
{"lineNum":"   21","line":"        }"},
{"lineNum":"   22","line":"    };"},
{"lineNum":"   23","line":"}"},
{"lineNum":"   24","line":""},
{"lineNum":"   25","line":"pub fn Apply_Flat_Ast_Walk(Context_Type: type) type {"},
{"lineNum":"   26","line":"    return struct {"},
{"lineNum":"   27","line":"        const Self: type = @This();"},
{"lineNum":"   28","line":"        context: Context_Type,"},
{"lineNum":"   29","line":""},
{"lineNum":"   30","line":"        pub fn init(context: Context_Type) Self {","class":"lineCov","hits":"2","order":"513","possible_hits":"2",},
{"lineNum":"   31","line":"            return Self{ .context = context };","class":"lineCov","hits":"2","order":"514","possible_hits":"2",},
{"lineNum":"   32","line":"        }"},
{"lineNum":"   33","line":""},
{"lineNum":"   34","line":"        pub fn run(self: *Self, asts: *std.array_list.Managed(*ast_.AST)) Error!*std.array_list.Managed(*ast_.AST) {","class":"lineCov","hits":"4","order":"1520","possible_hits":"4",},
{"lineNum":"   35","line":"            try walk_asts_flat(asts, self.context);","class":"lineCov","hits":"2","order":"1521","possible_hits":"2",},
{"lineNum":"   36","line":"            return asts;","class":"lineCov","hits":"2","order":"1533","possible_hits":"2",},
{"lineNum":"   37","line":"        }"},
{"lineNum":"   38","line":"    };"},
{"lineNum":"   39","line":"}"},
{"lineNum":"   40","line":""},
{"lineNum":"   41","line":"pub fn walk_asts(asts: *const std.array_list.Managed(*ast_.AST), context: anytype) Error!void {","class":"lineCov","hits":"10","order":"1400","possible_hits":"10",},
{"lineNum":"   42","line":"    for (asts.items) |ast| {","class":"lineCov","hits":"15","order":"1401","possible_hits":"15",},
{"lineNum":"   43","line":"        try walk_ast(ast, context);","class":"linePartCov","hits":"9","order":"1402","possible_hits":"10",},
{"lineNum":"   44","line":"    }","class":"lineCov","hits":"20","order":"1420","possible_hits":"20",},
{"lineNum":"   45","line":"}"},
{"lineNum":"   46","line":""},
{"lineNum":"   47","line":"pub fn walk_asts_flat(asts: *std.array_list.Managed(*ast_.AST), context: anytype) Error!void {","class":"lineCov","hits":"4","order":"1522","possible_hits":"4",},
{"lineNum":"   48","line":"    var i: usize = 0;","class":"lineCov","hits":"2","order":"1523","possible_hits":"2",},
{"lineNum":"   49","line":"    while (i < asts.items.len) : (i += 1) {","class":"linePartCov","hits":"8","order":"1524","possible_hits":"10",},
{"lineNum":"   50","line":"        const ast = asts.items[i];","class":"lineCov","hits":"6","order":"1525","possible_hits":"6",},
{"lineNum":"   51","line":"        i += try context.flat(ast, asts, i);","class":"linePartCov","hits":"3","order":"1526","possible_hits":"4",},
{"lineNum":"   52","line":"    }","class":"lineCov","hits":"2","order":"1532","possible_hits":"2",},
{"lineNum":"   53","line":"}"},
{"lineNum":"   54","line":""},
{"lineNum":"   55","line":"// A function that walks over an AST, applying prefix, postfix\'s function to each one"},
{"lineNum":"   56","line":"pub fn walk_ast(maybe_ast: ?*ast_.AST, context: anytype) Error!void {","class":"lineCov","hits":"10","order":"1403","possible_hits":"10",},
{"lineNum":"   57","line":"    if (maybe_ast == null) {","class":"lineCov","hits":"5","order":"1404","possible_hits":"5",},
{"lineNum":"   58","line":"        return;","class":"lineCov","hits":"5","order":"1445","possible_hits":"5",},
{"lineNum":"   59","line":"    }"},
{"lineNum":"   60","line":"    const ast = maybe_ast.?;","class":"lineCov","hits":"15","order":"1405","possible_hits":"15",},
{"lineNum":"   61","line":""},
{"lineNum":"   62","line":"    var new_context = context;","class":"lineCov","hits":"5","order":"1406","possible_hits":"5",},
{"lineNum":"   63","line":"    if (@hasDecl(@TypeOf(context), \"prefix\")) {"},
{"lineNum":"   64","line":"        const maybe_new_context = try new_context.prefix(ast);","class":"linePartCov","hits":"7","order":"1407","possible_hits":"8",},
{"lineNum":"   65","line":"        if (maybe_new_context == null) {","class":"lineCov","hits":"4","order":"1413","possible_hits":"4",},
{"lineNum":"   66","line":"            return;","class":"linePartCov","hits":"1","order":"5486","possible_hits":"4",},
{"lineNum":"   67","line":"        } else {"},
{"lineNum":"   68","line":"            new_context = maybe_new_context.?;","class":"lineCov","hits":"8","order":"1414","possible_hits":"8",},
{"lineNum":"   69","line":"        }"},
{"lineNum":"   70","line":"    }"},
{"lineNum":"   71","line":""},
{"lineNum":"   72","line":"    switch (ast.*) {","class":"linePartCov","hits":"5","order":"1415","possible_hits":"10",},
{"lineNum":"   73","line":"        .unit_value,"},
{"lineNum":"   74","line":"        .int,"},
{"lineNum":"   75","line":"        .float,"},
{"lineNum":"   76","line":"        .string,"},
{"lineNum":"   77","line":"        .field,"},
{"lineNum":"   78","line":"        .@\"unreachable\","},
{"lineNum":"   79","line":"        .true,"},
{"lineNum":"   80","line":"        .false,"},
{"lineNum":"   81","line":"        .@\"break\","},
{"lineNum":"   82","line":"        .@\"continue\","},
{"lineNum":"   83","line":"        .poison,"},
{"lineNum":"   84","line":"        .pattern_symbol,"},
{"lineNum":"   85","line":"        .receiver,"},
{"lineNum":"   86","line":"        .identifier,"},
{"lineNum":"   87","line":"        .type_param_decl,"},
{"lineNum":"   88","line":"        .import,"},
{"lineNum":"   89","line":"        => {},"},
{"lineNum":"   90","line":""},
{"lineNum":"   91","line":"        .context_value_decl => {"},
{"lineNum":"   92","line":"            try walk_ast(ast.context_value_decl.init, new_context);","class":"linePartCov","hits":"8","order":"4982","possible_hits":"10",},
{"lineNum":"   93","line":"            try walk_type(ast.context_value_decl.parent, new_context);","class":"linePartCov","hits":"4","order":"4983","possible_hits":"5",},
{"lineNum":"   94","line":"        },"},
{"lineNum":"   95","line":"        .context_decl => try walk_type(ast.decl_typedef(), new_context),","class":"linePartCov","hits":"4","order":"1516","possible_hits":"10",},
{"lineNum":"   96","line":""},
{"lineNum":"   97","line":"        .struct_decl,"},
{"lineNum":"   98","line":"        .enum_decl,"},
{"lineNum":"   99","line":"        .type_alias,"},
{"lineNum":"  100","line":"        => {"},
{"lineNum":"  101","line":"            try walk_asts(ast.generic_params(), new_context);","class":"linePartCov","hits":"5","order":"1416","possible_hits":"10",},
{"lineNum":"  102","line":"            try walk_type(ast.decl_typedef(), new_context);","class":"lineCov","hits":"5","order":"1421","possible_hits":"5",},
{"lineNum":"  103","line":"        },"},
{"lineNum":"  104","line":""},
{"lineNum":"  105","line":"        .module => {}, // std.debug.panic(\"compiler error: walking over modules not implemented!\\n\", .{}),"},
{"lineNum":"  106","line":""},
{"lineNum":"  107","line":"        .size_of, .default => try walk_type(ast.type(), new_context),","class":"linePartCov","hits":"4","order":"4916","possible_hits":"10",},
{"lineNum":"  108","line":""},
{"lineNum":"  109","line":"        .not,"},
{"lineNum":"  110","line":"        .negate,"},
{"lineNum":"  111","line":"        .dereference,"},
{"lineNum":"  112","line":"        .@\"try\","},
{"lineNum":"  113","line":"        .@\"comptime\","},
{"lineNum":"  114","line":"        .addr_of,"},
{"lineNum":"  115","line":"        .slice_of,"},
{"lineNum":"  116","line":"        .dyn_value,"},
{"lineNum":"  117","line":"        .bit_not,"},
{"lineNum":"  118","line":"        .cinclude,"},
{"lineNum":"  119","line":"        => try walk_ast(ast.expr(), new_context),","class":"linePartCov","hits":"6","order":"1447","possible_hits":"10",},
{"lineNum":"  120","line":""},
{"lineNum":"  121","line":"        .as => {"},
{"lineNum":"  122","line":"            try walk_ast(ast.expr(), new_context);","class":"linePartCov","hits":"5","order":"5251","possible_hits":"10",},
{"lineNum":"  123","line":"            try walk_type(ast.type(), new_context);","class":"lineCov","hits":"5","order":"5252","possible_hits":"5",},
{"lineNum":"  124","line":"        },"},
{"lineNum":"  125","line":""},
{"lineNum":"  126","line":"        .assign,"},
{"lineNum":"  127","line":"        .@\"or\","},
{"lineNum":"  128","line":"        .@\"and\","},
{"lineNum":"  129","line":"        .add,"},
{"lineNum":"  130","line":"        .sub,"},
{"lineNum":"  131","line":"        .mult,"},
{"lineNum":"  132","line":"        .div,"},
{"lineNum":"  133","line":"        .mod,"},
{"lineNum":"  134","line":"        .equal,"},
{"lineNum":"  135","line":"        .not_equal,"},
{"lineNum":"  136","line":"        .greater,"},
{"lineNum":"  137","line":"        .lesser,"},
{"lineNum":"  138","line":"        .greater_equal,"},
{"lineNum":"  139","line":"        .lesser_equal,"},
{"lineNum":"  140","line":"        .@\"catch\","},
{"lineNum":"  141","line":"        .@\"orelse\","},
{"lineNum":"  142","line":"        .select,"},
{"lineNum":"  143","line":"        .access,"},
{"lineNum":"  144","line":"        .left_shift,"},
{"lineNum":"  145","line":"        .right_shift,"},
{"lineNum":"  146","line":"        => {"},
{"lineNum":"  147","line":"            try walk_ast(ast.lhs(), new_context);","class":"linePartCov","hits":"5","order":"1491","possible_hits":"10",},
{"lineNum":"  148","line":"            try walk_ast(ast.rhs(), new_context);","class":"lineCov","hits":"5","order":"1492","possible_hits":"5",},
{"lineNum":"  149","line":"        },"},
{"lineNum":"  150","line":"        .invoke => {"},
{"lineNum":"  151","line":"            try walk_ast(ast.lhs(), new_context);","class":"linePartCov","hits":"5","order":"5254","possible_hits":"10",},
{"lineNum":"  152","line":"            try walk_ast(ast.rhs(), new_context);","class":"lineCov","hits":"5","order":"5255","possible_hits":"5",},
{"lineNum":"  153","line":"            try walk_asts(ast.children(), new_context);","class":"lineCov","hits":"5","order":"5256","possible_hits":"5",},
{"lineNum":"  154","line":"        },"},
{"lineNum":"  155","line":"        .call, .index => {"},
{"lineNum":"  156","line":"            try walk_ast(ast.lhs(), new_context);","class":"linePartCov","hits":"7","order":"1476","possible_hits":"10",},
{"lineNum":"  157","line":"            try walk_asts(ast.children(), new_context);","class":"lineCov","hits":"5","order":"1479","possible_hits":"5",},
{"lineNum":"  158","line":"        },"},
{"lineNum":"  159","line":"        .generic_apply => {"},
{"lineNum":"  160","line":"            try walk_ast(ast.lhs(), new_context);","class":"linePartCov","hits":"3","order":"5543","possible_hits":"10",},
{"lineNum":"  161","line":"            try walk_types(&ast.generic_apply._children, new_context);","class":"linePartCov","hits":"3","order":"5544","possible_hits":"5",},
{"lineNum":"  162","line":"        },"},
{"lineNum":"  163","line":""},
{"lineNum":"  164","line":"        .context_value => {"},
{"lineNum":"  165","line":"            try walk_asts(ast.children(), new_context);","class":"lineNoCov","hits":"0","possible_hits":"10",},
{"lineNum":"  166","line":"            try walk_type(ast.context_value.parent, new_context);","class":"lineNoCov","hits":"0","possible_hits":"5",},
{"lineNum":"  167","line":"        },"},
{"lineNum":"  168","line":""},
{"lineNum":"  169","line":"        .struct_value,"},
{"lineNum":"  170","line":"        .tuple_value,"},
{"lineNum":"  171","line":"        .array_value,"},
{"lineNum":"  172","line":"        .bit_and,"},
{"lineNum":"  173","line":"        .bit_or,"},
{"lineNum":"  174","line":"        .bit_xor,"},
{"lineNum":"  175","line":"        => try walk_asts(ast.children(), new_context),","class":"linePartCov","hits":"5","order":"1457","possible_hits":"10",},
{"lineNum":"  176","line":"        .binding => {"},
{"lineNum":"  177","line":"            try walk_asts(ast.children(), new_context);","class":"linePartCov","hits":"8","order":"1485","possible_hits":"10",},
{"lineNum":"  178","line":"            try walk_ast(ast.binding.init, new_context);","class":"lineCov","hits":"5","order":"1487","possible_hits":"5",},
{"lineNum":"  179","line":"            try walk_type(ast.binding.type, new_context);","class":"lineCov","hits":"5","order":"1488","possible_hits":"5",},
{"lineNum":"  180","line":"        },"},
{"lineNum":"  181","line":"        .enum_value => {"},
{"lineNum":"  182","line":"            try walk_ast(ast.enum_value.init, new_context);","class":"lineCov","hits":"10","order":"1461","possible_hits":"10",},
{"lineNum":"  183","line":"            if (ast.enum_value.base != null) {","class":"lineCov","hits":"10","order":"1462","possible_hits":"10",},
{"lineNum":"  184","line":"                try walk_type(ast.enum_value.base, new_context);","class":"linePartCov","hits":"8","order":"1463","possible_hits":"10",},
{"lineNum":"  185","line":"            }"},
{"lineNum":"  186","line":"        },"},
{"lineNum":"  187","line":"        .sub_slice => {"},
{"lineNum":"  188","line":"            try walk_ast(ast.sub_slice.super, new_context);","class":"linePartCov","hits":"8","order":"6831","possible_hits":"10",},
{"lineNum":"  189","line":"            try walk_ast(ast.sub_slice.lower, new_context);","class":"linePartCov","hits":"4","order":"6832","possible_hits":"5",},
{"lineNum":"  190","line":"            try walk_ast(ast.sub_slice.upper, new_context);","class":"linePartCov","hits":"4","order":"6833","possible_hits":"5",},
{"lineNum":"  191","line":"        },"},
{"lineNum":"  192","line":"        .@\"if\" => {"},
{"lineNum":"  193","line":"            try walk_ast(ast.@\"if\".let, new_context);","class":"lineCov","hits":"10","order":"1503","possible_hits":"10",},
{"lineNum":"  194","line":"            try walk_ast(ast.@\"if\".condition, new_context);","class":"lineCov","hits":"5","order":"1504","possible_hits":"5",},
{"lineNum":"  195","line":"            try walk_ast(ast.body_block(), new_context);","class":"lineCov","hits":"5","order":"1505","possible_hits":"5",},
{"lineNum":"  196","line":"            try walk_ast(ast.else_block(), new_context);","class":"lineCov","hits":"5","order":"1507","possible_hits":"5",},
{"lineNum":"  197","line":"        },"},
{"lineNum":"  198","line":"        .match => {"},
{"lineNum":"  199","line":"            try walk_ast(ast.match.let, new_context);","class":"linePartCov","hits":"8","order":"6007","possible_hits":"10",},
{"lineNum":"  200","line":"            try walk_ast(ast.expr(), new_context);","class":"linePartCov","hits":"4","order":"6008","possible_hits":"5",},
{"lineNum":"  201","line":"            try walk_asts(ast.children(), new_context);","class":"linePartCov","hits":"4","order":"6009","possible_hits":"5",},
{"lineNum":"  202","line":"        },"},
{"lineNum":"  203","line":"        .mapping => {"},
{"lineNum":"  204","line":"            try walk_ast(ast.lhs(), new_context);","class":"linePartCov","hits":"4","order":"6011","possible_hits":"10",},
{"lineNum":"  205","line":"            try walk_ast(ast.rhs(), new_context);","class":"linePartCov","hits":"4","order":"6012","possible_hits":"5",},
{"lineNum":"  206","line":"            try walk_asts(&ast.mapping.captures, new_context);","class":"linePartCov","hits":"4","order":"6013","possible_hits":"5",},
{"lineNum":"  207","line":"        },"},
{"lineNum":"  208","line":"        .@\"while\" => {"},
{"lineNum":"  209","line":"            try walk_ast(ast.@\"while\".let, new_context);","class":"lineCov","hits":"10","order":"1496","possible_hits":"10",},
{"lineNum":"  210","line":"            try walk_ast(ast.@\"while\".condition, new_context);","class":"lineCov","hits":"5","order":"1498","possible_hits":"5",},
{"lineNum":"  211","line":"            try walk_ast(ast.@\"while\".post, new_context);","class":"lineCov","hits":"5","order":"1499","possible_hits":"5",},
{"lineNum":"  212","line":"            try walk_ast(ast.body_block(), new_context);","class":"lineCov","hits":"5","order":"1500","possible_hits":"5",},
{"lineNum":"  213","line":"            try walk_ast(ast.else_block(), new_context);","class":"lineCov","hits":"5","order":"1510","possible_hits":"5",},
{"lineNum":"  214","line":"        },"},
{"lineNum":"  215","line":"        .@\"for\" => {"},
{"lineNum":"  216","line":"            try walk_ast(ast.@\"for\".let, new_context);","class":"lineNoCov","hits":"0","possible_hits":"10",},
{"lineNum":"  217","line":"            try walk_ast(ast.@\"for\".elem, new_context);","class":"lineNoCov","hits":"0","possible_hits":"5",},
{"lineNum":"  218","line":"            try walk_ast(ast.@\"for\".iterable, new_context);","class":"lineNoCov","hits":"0","possible_hits":"5",},
{"lineNum":"  219","line":"            try walk_ast(ast.body_block(), new_context);","class":"lineNoCov","hits":"0","possible_hits":"5",},
{"lineNum":"  220","line":"            try walk_ast(ast.else_block(), new_context);","class":"lineNoCov","hits":"0","possible_hits":"5",},
{"lineNum":"  221","line":"        },"},
{"lineNum":"  222","line":"        .with => {"},
{"lineNum":"  223","line":"            try walk_asts(&ast.with.contexts, new_context);","class":"lineNoCov","hits":"0","possible_hits":"10",},
{"lineNum":"  224","line":"            try walk_ast(ast.with._body_block, new_context);","class":"lineNoCov","hits":"0","possible_hits":"5",},
{"lineNum":"  225","line":"        },"},
{"lineNum":"  226","line":"        .block => {"},
{"lineNum":"  227","line":"            try walk_asts(ast.children(), new_context);","class":"linePartCov","hits":"9","order":"1474","possible_hits":"10",},
{"lineNum":"  228","line":"            if (ast.block.final) |final| {","class":"lineCov","hits":"10","order":"1481","possible_hits":"10",},
{"lineNum":"  229","line":"                try walk_ast(final, new_context);","class":"lineCov","hits":"10","order":"1482","possible_hits":"10",},
{"lineNum":"  230","line":"            }"},
{"lineNum":"  231","line":"        },"},
{"lineNum":"  232","line":"        .@\"return\" => try walk_ast(ast.@\"return\"._ret_expr, new_context),","class":"lineCov","hits":"10","order":"1506","possible_hits":"10",},
{"lineNum":"  233","line":"        .decl => {"},
{"lineNum":"  234","line":"            try walk_type(ast.decl.type, new_context);","class":"linePartCov","hits":"8","order":"1807","possible_hits":"10",},
{"lineNum":"  235","line":"            if (!(ast.decl.init != null and ast.decl.init.?.* == .default and ast.decl.init.?.default._type == ast.decl.type)) {","class":"linePartCov","hits":"8","order":"1808","possible_hits":"10",},
{"lineNum":"  236","line":"                // Don\'t double-walk when decl\'s init is a default of its type"},
{"lineNum":"  237","line":"                try walk_ast(ast.decl.init, new_context);","class":"linePartCov","hits":"8","order":"1809","possible_hits":"10",},
{"lineNum":"  238","line":"            }"},
{"lineNum":"  239","line":"        },"},
{"lineNum":"  240","line":"        .fn_decl => {"},
{"lineNum":"  241","line":"            try walk_asts(&ast.fn_decl.context_decls, new_context);","class":"linePartCov","hits":"8","order":"4450","possible_hits":"10",},
{"lineNum":"  242","line":"            try walk_asts(ast.generic_params(), new_context);","class":"linePartCov","hits":"4","order":"4451","possible_hits":"5",},
{"lineNum":"  243","line":"            try walk_type(ast.fn_decl._decl_type, new_context);","class":"linePartCov","hits":"4","order":"4453","possible_hits":"5",},
{"lineNum":"  244","line":"            try walk_ast(ast.fn_decl.init, new_context);","class":"linePartCov","hits":"4","order":"4454","possible_hits":"5",},
{"lineNum":"  245","line":"            try walk_asts(ast.children(), new_context);","class":"linePartCov","hits":"4","order":"4455","possible_hits":"5",},
{"lineNum":"  246","line":"            try walk_type(ast.fn_decl.ret_type, new_context);","class":"linePartCov","hits":"4","order":"4457","possible_hits":"5",},
{"lineNum":"  247","line":"        },"},
{"lineNum":"  248","line":"        .@\"test\" => {"},
{"lineNum":"  249","line":"            try walk_asts(&ast.@\"test\".context_decls, new_context);","class":"linePartCov","hits":"8","order":"5069","possible_hits":"10",},
{"lineNum":"  250","line":"            try walk_ast(ast.@\"test\".name, new_context);","class":"linePartCov","hits":"4","order":"5070","possible_hits":"5",},
{"lineNum":"  251","line":"            try walk_ast(ast.@\"test\".init, new_context);","class":"linePartCov","hits":"4","order":"5071","possible_hits":"5",},
{"lineNum":"  252","line":"        },"},
{"lineNum":"  253","line":"        .trait => {"},
{"lineNum":"  254","line":"            try walk_asts(&ast.trait.method_decls, new_context);","class":"lineCov","hits":"10","order":"1514","possible_hits":"10",},
{"lineNum":"  255","line":"            try walk_asts(&ast.trait.const_decls, new_context);","class":"lineCov","hits":"5","order":"1515","possible_hits":"5",},
{"lineNum":"  256","line":"        },"},
{"lineNum":"  257","line":"        .impl => {"},
{"lineNum":"  258","line":"            try walk_asts(ast.generic_params(), new_context);","class":"linePartCov","hits":"5","order":"1467","possible_hits":"10",},
{"lineNum":"  259","line":"            try walk_type(ast.impl._type, new_context);","class":"lineCov","hits":"5","order":"1469","possible_hits":"5",},
{"lineNum":"  260","line":"            try walk_ast(ast.impl.trait, new_context);","class":"lineCov","hits":"5","order":"1470","possible_hits":"5",},
{"lineNum":"  261","line":"            try walk_asts(&ast.impl.method_defs, new_context);","class":"lineCov","hits":"5","order":"1471","possible_hits":"5",},
{"lineNum":"  262","line":"            try walk_asts(&ast.impl.const_defs, new_context);","class":"lineCov","hits":"5","order":"1511","possible_hits":"5",},
{"lineNum":"  263","line":"        },"},
{"lineNum":"  264","line":"        .method_decl => {"},
{"lineNum":"  265","line":"            try walk_asts(&ast.method_decl.context_decls, new_context);","class":"lineCov","hits":"10","order":"1472","possible_hits":"10",},
{"lineNum":"  266","line":"            try walk_ast(ast.method_decl.init, new_context);","class":"lineCov","hits":"5","order":"1473","possible_hits":"5",},
{"lineNum":"  267","line":"            try walk_asts(ast.children(), new_context);","class":"lineCov","hits":"5","order":"1483","possible_hits":"5",},
{"lineNum":"  268","line":"            try walk_type(ast.method_decl._decl_type, new_context);","class":"lineCov","hits":"5","order":"1489","possible_hits":"5",},
{"lineNum":"  269","line":"            try walk_type(ast.method_decl.ret_type, new_context);","class":"lineCov","hits":"10","order":"1452","possible_hits":"10",},
{"lineNum":"  270","line":"        },"},
{"lineNum":"  271","line":"        .@\"defer\", .@\"errdefer\" => try walk_ast(ast.statement(), new_context),","class":"lineNoCov","hits":"0","possible_hits":"10",},
{"lineNum":"  272","line":"    }"},
{"lineNum":"  273","line":""},
{"lineNum":"  274","line":"    if (@hasDecl(@TypeOf(context), \"postfix\")) {","class":"lineCov","hits":"3","order":"1453","possible_hits":"3",},
{"lineNum":"  275","line":"        try context.postfix(ast);","class":"linePartCov","hits":"3","order":"1576","possible_hits":"4",},
{"lineNum":"  276","line":"    }"},
{"lineNum":"  277","line":"}"},
{"lineNum":"  278","line":""},
{"lineNum":"  279","line":"pub fn walk_types(types: *const std.array_list.Managed(*Type_AST), context: anytype) Error!void {","class":"lineCov","hits":"10","order":"1434","possible_hits":"10",},
{"lineNum":"  280","line":"    for (types.items) |_type| {","class":"lineCov","hits":"15","order":"1435","possible_hits":"15",},
{"lineNum":"  281","line":"        try walk_type(_type, context);","class":"linePartCov","hits":"5","order":"1436","possible_hits":"10",},
{"lineNum":"  282","line":"    }","class":"lineCov","hits":"20","order":"1446","possible_hits":"20",},
{"lineNum":"  283","line":"}"},
{"lineNum":"  284","line":""},
{"lineNum":"  285","line":"pub fn walk_types_flat(types: *std.array_list.Managed(*Type_AST), context: anytype) Error!void {"},
{"lineNum":"  286","line":"    var i: usize = 0;"},
{"lineNum":"  287","line":"    while (i < types.items.len) : (i += 1) {"},
{"lineNum":"  288","line":"        const _type = types.items[i];"},
{"lineNum":"  289","line":"        i += try context.flat_type(_type, types, i);"},
{"lineNum":"  290","line":"    }"},
{"lineNum":"  291","line":"}"},
{"lineNum":"  292","line":""},
{"lineNum":"  293","line":"// A function that walks over an AST, applying prefix, postfix\'s function to each one"},
{"lineNum":"  294","line":"pub fn walk_type(maybe_type: ?*Type_AST, context: anytype) Error!void {","class":"lineCov","hits":"10","order":"1425","possible_hits":"10",},
{"lineNum":"  295","line":"    if (maybe_type == null) {","class":"lineCov","hits":"5","order":"1426","possible_hits":"5",},
{"lineNum":"  296","line":"        return;","class":"linePartCov","hits":"4","order":"1490","possible_hits":"5",},
{"lineNum":"  297","line":"    }"},
{"lineNum":"  298","line":"    const _type = maybe_type.?;","class":"lineCov","hits":"15","order":"1427","possible_hits":"15",},
{"lineNum":"  299","line":""},
{"lineNum":"  300","line":"    var new_context = context;","class":"lineCov","hits":"5","order":"1428","possible_hits":"5",},
{"lineNum":"  301","line":"    if (@hasDecl(@TypeOf(context), \"prefix_type\")) {"},
{"lineNum":"  302","line":"        const maybe_new_context = try context.prefix_type(_type);","class":"lineCov","hits":"2","order":"1928","possible_hits":"2",},
{"lineNum":"  303","line":"        if (maybe_new_context == null) {","class":"lineCov","hits":"1","order":"1934","possible_hits":"1",},
{"lineNum":"  304","line":"            return;","class":"lineNoCov","hits":"0","possible_hits":"1",},
{"lineNum":"  305","line":"        } else {"},
{"lineNum":"  306","line":"            new_context = maybe_new_context.?;","class":"lineCov","hits":"2","order":"1935","possible_hits":"2",},
{"lineNum":"  307","line":"        }"},
{"lineNum":"  308","line":"    }"},
{"lineNum":"  309","line":""},
{"lineNum":"  310","line":"    switch (_type.*) {","class":"linePartCov","hits":"5","order":"1429","possible_hits":"10",},
{"lineNum":"  311","line":"        .poison, .anyptr_type, .unit_type, .identifier => {},"},
{"lineNum":"  312","line":""},
{"lineNum":"  313","line":"        .type_of => try walk_ast(_type.type_of._expr, new_context),","class":"linePartCov","hits":"8","order":"1497","possible_hits":"10",},
{"lineNum":"  314","line":""},
{"lineNum":"  315","line":"        .access => try walk_ast(_type.access.inner_access, new_context),","class":"linePartCov","hits":"6","order":"5763","possible_hits":"10",},
{"lineNum":"  316","line":""},
{"lineNum":"  317","line":"        .generic_apply => {"},
{"lineNum":"  318","line":"            try walk_type(_type.lhs(), new_context);","class":"linePartCov","hits":"5","order":"5248","possible_hits":"10",},
{"lineNum":"  319","line":"            try walk_types(_type.children(), new_context);","class":"lineCov","hits":"5","order":"5249","possible_hits":"5",},
{"lineNum":"  320","line":"        },"},
{"lineNum":"  321","line":""},
{"lineNum":"  322","line":"        .array_of => {"},
{"lineNum":"  323","line":"            try walk_type(_type.child(), new_context);","class":"linePartCov","hits":"5","order":"1454","possible_hits":"10",},
{"lineNum":"  324","line":"            try walk_ast(_type.array_of.len, new_context);","class":"lineCov","hits":"5","order":"1456","possible_hits":"5",},
{"lineNum":"  325","line":"        },"},
{"lineNum":"  326","line":""},
{"lineNum":"  327","line":"        .annotation => {"},
{"lineNum":"  328","line":"            try walk_type(_type.child(), new_context);","class":"linePartCov","hits":"5","order":"1437","possible_hits":"10",},
{"lineNum":"  329","line":"            try walk_ast(_type.annotation.init, new_context);","class":"lineCov","hits":"5","order":"1444","possible_hits":"5",},
{"lineNum":"  330","line":"        },"},
{"lineNum":"  331","line":""},
{"lineNum":"  332","line":"        .untagged_sum_type,"},
{"lineNum":"  333","line":"        .addr_of,"},
{"lineNum":"  334","line":"        .dyn_type,"},
{"lineNum":"  335","line":"        .index,"},
{"lineNum":"  336","line":"        .domain_of,"},
{"lineNum":"  337","line":"        => {"},
{"lineNum":"  338","line":"            try walk_type(_type.child(), new_context);","class":"linePartCov","hits":"6","order":"1466","possible_hits":"10",},
{"lineNum":"  339","line":"        },"},
{"lineNum":"  340","line":""},
{"lineNum":"  341","line":"        .function => {"},
{"lineNum":"  342","line":"            try walk_type(_type.lhs(), new_context);","class":"linePartCov","hits":"5","order":"1810","possible_hits":"10",},
{"lineNum":"  343","line":"            try walk_type(_type.rhs(), new_context);","class":"lineCov","hits":"5","order":"1813","possible_hits":"5",},
{"lineNum":"  344","line":"            try walk_types(&_type.function.contexts, new_context);","class":"lineCov","hits":"10","order":"1442","possible_hits":"10",},
{"lineNum":"  345","line":"        },"},
{"lineNum":"  346","line":""},
{"lineNum":"  347","line":"        .context_type,"},
{"lineNum":"  348","line":"        .enum_type,"},
{"lineNum":"  349","line":"        .struct_type,"},
{"lineNum":"  350","line":"        .tuple_type,"},
{"lineNum":"  351","line":"        => {"},
{"lineNum":"  352","line":"            try walk_types(_type.children(), new_context);","class":"linePartCov","hits":"5","order":"1430","possible_hits":"10",},
{"lineNum":"  353","line":"        },"},
{"lineNum":"  354","line":"    }"},
{"lineNum":"  355","line":""},
{"lineNum":"  356","line":"    if (@hasDecl(@TypeOf(context), \"postfix_type\")) {","class":"lineCov","hits":"3","order":"1443","possible_hits":"3",},
{"lineNum":"  357","line":"        try context.postfix_type(_type);","class":"linePartCov","hits":"3","order":"1947","possible_hits":"4",},
{"lineNum":"  358","line":"    }"},
{"lineNum":"  359","line":"}"},
]};
var percent_low = 25;var percent_high = 75;
var header = { "command" : "orng-test", "date" : "2025-11-10 15:43:08", "instrumented" : 142, "covered" : 131,};
var merged_data = [];
